// @generated
// This file is @generated by prost-build.
// ===== Request/response messages (from rpc-exch-gateway.proto, field numbers preserved) =====

#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SendOrderRequest {
    #[prost(int64, tag="1")]
    pub correlation_id: i64,
    #[prost(string, tag="2")]
    pub exch_account_id: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub instrument: ::prost::alloc::string::String,
    #[prost(enumeration="super::super::common::v1::BuySellType", tag="4")]
    pub buysell_type: i32,
    #[prost(enumeration="super::super::common::v1::OpenCloseType", tag="5")]
    pub openclose_type: i32,
    #[prost(enumeration="super::super::common::v1::BasicOrderType", tag="6")]
    pub order_type: i32,
    #[prost(double, tag="7")]
    pub scaled_price: f64,
    #[prost(double, tag="8")]
    pub scaled_qty: f64,
    #[prost(double, tag="9")]
    pub leverage: f64,
    #[prost(int64, tag="10")]
    pub timestamp: i64,
    #[prost(message, optional, tag="11")]
    pub exch_specific_params: ::core::option::Option<super::super::common::v1::ExtraData>,
    #[prost(enumeration="super::super::common::v1::TimeInForceType", tag="12")]
    pub time_inforce_type: i32,
    #[prost(enumeration="super::super::common::v1::ExtraOrderTagType", repeated, tag="13")]
    pub extra_order_tags: ::prost::alloc::vec::Vec<i32>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BatchSendOrdersRequest {
    #[prost(message, repeated, tag="1")]
    pub order_requests: ::prost::alloc::vec::Vec<SendOrderRequest>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExchOrder {
    #[prost(string, tag="1")]
    pub order_ref: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub instrument: ::prost::alloc::string::String,
    #[prost(enumeration="super::super::common::v1::BuySellType", tag="3")]
    pub buysell_type: i32,
    #[prost(enumeration="super::super::common::v1::OpenCloseType", tag="4")]
    pub openclose_type: i32,
    #[prost(enumeration="super::super::common::v1::BasicOrderType", tag="5")]
    pub order_type: i32,
    #[prost(message, optional, tag="6")]
    pub order_report: ::core::option::Option<super::super::exch_gw::v1::OrderReport>,
    #[prost(double, tag="11")]
    pub leverage: f64,
    #[prost(int64, tag="12")]
    pub timestamp: i64,
    #[prost(string, tag="13")]
    pub exch_order_original: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CancelOrderRequest {
    #[prost(string, tag="1")]
    pub exch_order_ref: ::prost::alloc::string::String,
    #[prost(int64, tag="2")]
    pub order_id: i64,
    #[prost(message, optional, tag="3")]
    pub exch_specific_params: ::core::option::Option<super::super::common::v1::ExtraData>,
    #[prost(int64, tag="4")]
    pub timestamp: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BatchCancelOrdersRequest {
    #[prost(message, repeated, tag="1")]
    pub cancel_requests: ::prost::alloc::vec::Vec<CancelOrderRequest>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AmendOrderRequest {
    /// TBA
    #[prost(string, tag="1")]
    pub exch_order_ref: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GatewayCommandRequest {
    #[prost(enumeration="gateway_command_request::CommandType", tag="1")]
    pub command_type: i32,
    #[prost(string, tag="2")]
    pub command_source_id: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub command_payload: ::prost::alloc::string::String,
}
/// Nested message and enum types in `GatewayCommandRequest`.
pub mod gateway_command_request {
    #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
    #[repr(i32)]
    pub enum CommandType {
        CmdTypeUnspecified = 0,
        CmdTypeReconnectExch = 1,
        CmdTypePublishAccount = 2,
        CmdTypeUserDefined = 3,
    }
    impl CommandType {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::CmdTypeUnspecified => "CMD_TYPE_UNSPECIFIED",
                Self::CmdTypeReconnectExch => "CMD_TYPE_RECONNECT_EXCH",
                Self::CmdTypePublishAccount => "CMD_TYPE_PUBLISH_ACCOUNT",
                Self::CmdTypeUserDefined => "CMD_TYPE_USER_DEFINED",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "CMD_TYPE_UNSPECIFIED" => Some(Self::CmdTypeUnspecified),
                "CMD_TYPE_RECONNECT_EXCH" => Some(Self::CmdTypeReconnectExch),
                "CMD_TYPE_PUBLISH_ACCOUNT" => Some(Self::CmdTypePublishAccount),
                "CMD_TYPE_USER_DEFINED" => Some(Self::CmdTypeUserDefined),
                _ => None,
            }
        }
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GatewayResponse {
    #[prost(int64, tag="1")]
    pub timestamp: i64,
    #[prost(enumeration="gateway_response::Status", tag="2")]
    pub status: i32,
    /// deprecated
    #[prost(int64, tag="4")]
    pub error_code: i64,
    /// deprecated
    #[prost(string, tag="5")]
    pub message: ::prost::alloc::string::String,
    #[prost(message, optional, tag="6")]
    pub rejection_info: ::core::option::Option<super::super::common::v1::Rejection>,
}
/// Nested message and enum types in `GatewayResponse`.
pub mod gateway_response {
    #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
    #[repr(i32)]
    pub enum Status {
        GwRespStatusUnspecified = 0,
        GwRespStatusSuccess = 1,
        GwRespStatusFail = 2,
    }
    impl Status {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::GwRespStatusUnspecified => "GW_RESP_STATUS_UNSPECIFIED",
                Self::GwRespStatusSuccess => "GW_RESP_STATUS_SUCCESS",
                Self::GwRespStatusFail => "GW_RESP_STATUS_FAIL",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "GW_RESP_STATUS_UNSPECIFIED" => Some(Self::GwRespStatusUnspecified),
                "GW_RESP_STATUS_SUCCESS" => Some(Self::GwRespStatusSuccess),
                "GW_RESP_STATUS_FAIL" => Some(Self::GwRespStatusFail),
                _ => None,
            }
        }
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SingleOrderQuery {
    #[prost(string, tag="1")]
    pub exch_order_ref: ::prost::alloc::string::String,
    #[prost(int64, tag="2")]
    pub order_id: i64,
    #[prost(string, tag="3")]
    pub symbol: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub exch_account: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct QueryAccountRequest {
    #[prost(string, repeated, tag="1")]
    pub explicit_symbols: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AccountResponse {
    #[prost(string, tag="1")]
    pub exch_account_code: ::prost::alloc::string::String,
    #[prost(message, optional, tag="4")]
    pub balance_update: ::core::option::Option<super::super::exch_gw::v1::BalanceUpdate>,
    #[prost(int64, tag="3")]
    pub timestamp: i64,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct QueryPositionRequest {
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PositionResponse {
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct QueryOpenOrderRequest {
    #[prost(string, tag="1")]
    pub exch_account_code: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QueryOrderDetailRequest {
    #[prost(message, repeated, tag="1")]
    pub order_queries: ::prost::alloc::vec::Vec<SingleOrderQuery>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OrderDetailResponse {
    #[prost(message, repeated, tag="1")]
    pub orders: ::prost::alloc::vec::Vec<ExchOrder>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct QueryTradeDetailRequest {
    #[prost(string, tag="1")]
    pub exch_account_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub instrument_code: ::prost::alloc::string::String,
    #[prost(int64, tag="3")]
    pub start_ts: i64,
    #[prost(int64, tag="4")]
    pub end_ts: i64,
    #[prost(int64, tag="5")]
    pub limit: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HistoryTradeRecord {
    #[prost(string, tag="1")]
    pub exch_order_ref: ::prost::alloc::string::String,
    #[prost(message, optional, tag="2")]
    pub order_info: ::core::option::Option<super::super::exch_gw::v1::OrderInfo>,
    #[prost(message, optional, tag="3")]
    pub trade: ::core::option::Option<super::super::exch_gw::v1::TradeReport>,
    #[prost(message, optional, tag="4")]
    pub fee: ::core::option::Option<super::super::exch_gw::v1::FeeReport>,
    #[prost(message, repeated, tag="5")]
    pub extra_fees: ::prost::alloc::vec::Vec<super::super::exch_gw::v1::FeeReport>,
    #[prost(int64, tag="6")]
    pub timestamp: i64,
    #[prost(string, tag="7")]
    pub idx: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TradeDetailResponse {
    #[prost(message, repeated, tag="1")]
    pub history_trades: ::prost::alloc::vec::Vec<HistoryTradeRecord>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct QueryFeeRequest {
    #[prost(string, tag="1")]
    pub instrument_code: ::prost::alloc::string::String,
    #[prost(int64, tag="2")]
    pub start_ts: i64,
    #[prost(int64, tag="3")]
    pub end_ts: i64,
    #[prost(string, tag="4")]
    pub exch_account_id: ::prost::alloc::string::String,
    #[prost(enumeration="super::super::common::v1::FeeType", tag="5")]
    pub fee_types: i32,
    #[prost(int64, tag="6")]
    pub limit: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FeeResponse {
    #[prost(message, repeated, tag="1")]
    pub fees: ::prost::alloc::vec::Vec<super::super::exch_gw::v1::FeeReport>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct QueryOrderTradesRequest {
    #[prost(string, tag="1")]
    pub exch_order_ref: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub instrument_exch: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OrderTradesResponse {
    #[prost(string, tag="1")]
    pub order_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub exch_order_ref: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub instrument_exch: ::prost::alloc::string::String,
    #[prost(enumeration="super::super::common::v1::BuySellType", tag="4")]
    pub buysell_type: i32,
    #[prost(message, repeated, tag="5")]
    pub exch_trades: ::prost::alloc::vec::Vec<ExchTrade>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExchTrade {
    #[prost(message, optional, tag="1")]
    pub trade_report: ::core::option::Option<super::super::exch_gw::v1::TradeReport>,
    #[prost(message, optional, tag="2")]
    pub fee_report: ::core::option::Option<super::super::exch_gw::v1::FeeReport>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GenericRequest {
    #[prost(string, tag="1")]
    pub request_json: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GenericResponse {
    #[prost(string, tag="1")]
    pub response_json: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AccountSettingRequest {
    #[prost(message, optional, tag="1")]
    pub account_setting_entry: ::core::option::Option<super::super::exch_gw::v1::AccountSettingEntry>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AccountSettingUpdateResponse {
    #[prost(bool, tag="1")]
    pub margin_mode_changed: bool,
    #[prost(bool, tag="2")]
    pub leverage_changed: bool,
    #[prost(string, tag="3")]
    pub err_msg: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct QueryAccountSettingRequest {
    #[prost(string, tag="1")]
    pub exch_account_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub instrument: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AccountSettingResponse {
    #[prost(message, optional, tag="1")]
    pub account_setting_entry: ::core::option::Option<super::super::exch_gw::v1::AccountSettingEntry>,
    #[prost(string, tag="2")]
    pub original_info: ::prost::alloc::string::String,
}
// @@protoc_insertion_point(module)
