# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from zk.rtmd.v1 import rtmd_query_service_pb2 as zk_dot_rtmd_dot_v1_dot_rtmd__query__service__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in zk/rtmd/v1/rtmd_query_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RtmdQueryServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.QueryCurrentTick = channel.unary_unary(
                '/zk.rtmd.v1.RtmdQueryService/QueryCurrentTick',
                request_serializer=zk_dot_rtmd_dot_v1_dot_rtmd__query__service__pb2.QueryTickRequest.SerializeToString,
                response_deserializer=zk_dot_rtmd_dot_v1_dot_rtmd__query__service__pb2.QueryTickResponse.FromString,
                _registered_method=True)
        self.QueryCurrentOrderBook = channel.unary_unary(
                '/zk.rtmd.v1.RtmdQueryService/QueryCurrentOrderBook',
                request_serializer=zk_dot_rtmd_dot_v1_dot_rtmd__query__service__pb2.QueryOrderBookRequest.SerializeToString,
                response_deserializer=zk_dot_rtmd_dot_v1_dot_rtmd__query__service__pb2.QueryOrderBookResponse.FromString,
                _registered_method=True)
        self.QueryCurrentFunding = channel.unary_unary(
                '/zk.rtmd.v1.RtmdQueryService/QueryCurrentFunding',
                request_serializer=zk_dot_rtmd_dot_v1_dot_rtmd__query__service__pb2.QueryFundingRequest.SerializeToString,
                response_deserializer=zk_dot_rtmd_dot_v1_dot_rtmd__query__service__pb2.QueryFundingResponse.FromString,
                _registered_method=True)
        self.QueryKlines = channel.unary_unary(
                '/zk.rtmd.v1.RtmdQueryService/QueryKlines',
                request_serializer=zk_dot_rtmd_dot_v1_dot_rtmd__query__service__pb2.QueryKlinesRequest.SerializeToString,
                response_deserializer=zk_dot_rtmd_dot_v1_dot_rtmd__query__service__pb2.QueryKlinesResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/zk.rtmd.v1.RtmdQueryService/HealthCheck',
                request_serializer=zk_dot_rtmd_dot_v1_dot_rtmd__query__service__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=zk_dot_rtmd_dot_v1_dot_rtmd__query__service__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class RtmdQueryServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def QueryCurrentTick(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryCurrentOrderBook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryCurrentFunding(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryKlines(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RtmdQueryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'QueryCurrentTick': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryCurrentTick,
                    request_deserializer=zk_dot_rtmd_dot_v1_dot_rtmd__query__service__pb2.QueryTickRequest.FromString,
                    response_serializer=zk_dot_rtmd_dot_v1_dot_rtmd__query__service__pb2.QueryTickResponse.SerializeToString,
            ),
            'QueryCurrentOrderBook': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryCurrentOrderBook,
                    request_deserializer=zk_dot_rtmd_dot_v1_dot_rtmd__query__service__pb2.QueryOrderBookRequest.FromString,
                    response_serializer=zk_dot_rtmd_dot_v1_dot_rtmd__query__service__pb2.QueryOrderBookResponse.SerializeToString,
            ),
            'QueryCurrentFunding': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryCurrentFunding,
                    request_deserializer=zk_dot_rtmd_dot_v1_dot_rtmd__query__service__pb2.QueryFundingRequest.FromString,
                    response_serializer=zk_dot_rtmd_dot_v1_dot_rtmd__query__service__pb2.QueryFundingResponse.SerializeToString,
            ),
            'QueryKlines': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryKlines,
                    request_deserializer=zk_dot_rtmd_dot_v1_dot_rtmd__query__service__pb2.QueryKlinesRequest.FromString,
                    response_serializer=zk_dot_rtmd_dot_v1_dot_rtmd__query__service__pb2.QueryKlinesResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=zk_dot_rtmd_dot_v1_dot_rtmd__query__service__pb2.HealthCheckRequest.FromString,
                    response_serializer=zk_dot_rtmd_dot_v1_dot_rtmd__query__service__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'zk.rtmd.v1.RtmdQueryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('zk.rtmd.v1.RtmdQueryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RtmdQueryService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def QueryCurrentTick(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/zk.rtmd.v1.RtmdQueryService/QueryCurrentTick',
            zk_dot_rtmd_dot_v1_dot_rtmd__query__service__pb2.QueryTickRequest.SerializeToString,
            zk_dot_rtmd_dot_v1_dot_rtmd__query__service__pb2.QueryTickResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryCurrentOrderBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/zk.rtmd.v1.RtmdQueryService/QueryCurrentOrderBook',
            zk_dot_rtmd_dot_v1_dot_rtmd__query__service__pb2.QueryOrderBookRequest.SerializeToString,
            zk_dot_rtmd_dot_v1_dot_rtmd__query__service__pb2.QueryOrderBookResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryCurrentFunding(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/zk.rtmd.v1.RtmdQueryService/QueryCurrentFunding',
            zk_dot_rtmd_dot_v1_dot_rtmd__query__service__pb2.QueryFundingRequest.SerializeToString,
            zk_dot_rtmd_dot_v1_dot_rtmd__query__service__pb2.QueryFundingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryKlines(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/zk.rtmd.v1.RtmdQueryService/QueryKlines',
            zk_dot_rtmd_dot_v1_dot_rtmd__query__service__pb2.QueryKlinesRequest.SerializeToString,
            zk_dot_rtmd_dot_v1_dot_rtmd__query__service__pb2.QueryKlinesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/zk.rtmd.v1.RtmdQueryService/HealthCheck',
            zk_dot_rtmd_dot_v1_dot_rtmd__query__service__pb2.HealthCheckRequest.SerializeToString,
            zk_dot_rtmd_dot_v1_dot_rtmd__query__service__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
