// @generated
// This file is @generated by prost-build.
// ===== Messages (from rtmd.proto, field numbers preserved) =====

#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct PriceLevel {
    #[prost(double, tag="1")]
    pub price: f64,
    #[prost(double, tag="2")]
    pub qty: f64,
    #[prost(int64, tag="3")]
    pub num_of_orders: i64,
    #[prost(int64, tag="4")]
    pub num_of_pos: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Trade {
    #[prost(double, tag="1")]
    pub price: f64,
    #[prost(double, tag="2")]
    pub qty: f64,
    #[prost(int64, tag="3")]
    pub timestamp: i64,
    #[prost(string, tag="4")]
    pub side: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub instrument_code: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TickData {
    #[prost(enumeration="TickUpdateType", tag="1")]
    pub tick_type: i32,
    #[prost(string, tag="2")]
    pub instrument_code: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub exchange: ::prost::alloc::string::String,
    #[prost(int64, tag="4")]
    pub original_timestamp: i64,
    #[prost(int64, tag="5")]
    pub received_timestamp: i64,
    #[prost(double, tag="7")]
    pub volume: f64,
    #[prost(double, tag="8")]
    pub latest_trade_price: f64,
    #[prost(double, tag="9")]
    pub latest_trade_qty: f64,
    #[prost(string, tag="10")]
    pub latest_trade_side: ::prost::alloc::string::String,
    #[prost(message, repeated, tag="14")]
    pub buy_price_levels: ::prost::alloc::vec::Vec<PriceLevel>,
    #[prost(message, repeated, tag="15")]
    pub sell_price_levels: ::prost::alloc::vec::Vec<PriceLevel>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Kline {
    #[prost(int64, tag="1")]
    pub timestamp: i64,
    #[prost(int64, tag="2")]
    pub kline_end_timestamp: i64,
    #[prost(double, tag="3")]
    pub open: f64,
    #[prost(double, tag="4")]
    pub high: f64,
    #[prost(double, tag="5")]
    pub close: f64,
    #[prost(double, tag="6")]
    pub low: f64,
    #[prost(double, tag="7")]
    pub volume: f64,
    #[prost(double, tag="8")]
    pub amount: f64,
    #[prost(enumeration="kline::KlineType", tag="9")]
    pub kline_type: i32,
    #[prost(string, tag="10")]
    pub symbol: ::prost::alloc::string::String,
    #[prost(string, tag="11")]
    pub source: ::prost::alloc::string::String,
}
/// Nested message and enum types in `Kline`.
pub mod kline {
    #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
    #[repr(i32)]
    pub enum KlineType {
        Kline1min = 0,
        Kline5min = 1,
        Kline15min = 2,
        Kline30min = 3,
        Kline1hour = 4,
        Kline4hour = 5,
        Kline1day = 6,
    }
    impl KlineType {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Kline1min => "KLINE_1MIN",
                Self::Kline5min => "KLINE_5MIN",
                Self::Kline15min => "KLINE_15MIN",
                Self::Kline30min => "KLINE_30MIN",
                Self::Kline1hour => "KLINE_1HOUR",
                Self::Kline4hour => "KLINE_4HOUR",
                Self::Kline1day => "KLINE_1DAY",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "KLINE_1MIN" => Some(Self::Kline1min),
                "KLINE_5MIN" => Some(Self::Kline5min),
                "KLINE_15MIN" => Some(Self::Kline15min),
                "KLINE_30MIN" => Some(Self::Kline30min),
                "KLINE_1HOUR" => Some(Self::Kline1hour),
                "KLINE_4HOUR" => Some(Self::Kline4hour),
                "KLINE_1DAY" => Some(Self::Kline1day),
                _ => None,
            }
        }
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FundingRate {
    #[prost(string, tag="1")]
    pub instrument_code: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub exchange: ::prost::alloc::string::String,
    #[prost(int64, tag="3")]
    pub curr_funding_rate_timestamp: i64,
    #[prost(double, tag="4")]
    pub funding_rate: f64,
    #[prost(double, tag="6")]
    pub mark_price: f64,
    #[prost(double, tag="7")]
    pub index_price: f64,
    #[prost(double, tag="10")]
    pub next_funding_rate: f64,
    #[prost(int64, tag="12")]
    pub observe_timestamp: i64,
    #[prost(int64, tag="13")]
    pub next_funding_rate_timestamp: i64,
    #[prost(string, tag="14")]
    pub original_message: ::prost::alloc::string::String,
    #[prost(int64, tag="15")]
    pub next_payment_timestamp: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RealtimeSignal {
    #[prost(string, tag="1")]
    pub namespace: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub instrument: ::prost::alloc::string::String,
    #[prost(int64, tag="3")]
    pub timestamp: i64,
    #[prost(map="string, double", tag="4")]
    pub data: ::std::collections::HashMap<::prost::alloc::string::String, f64>,
    #[prost(string, tag="5")]
    pub message: ::prost::alloc::string::String,
    #[prost(map="string, int64", tag="6")]
    pub data_int: ::std::collections::HashMap<::prost::alloc::string::String, i64>,
    #[prost(map="string, string", tag="7")]
    pub data_str: ::std::collections::HashMap<::prost::alloc::string::String, ::prost::alloc::string::String>,
}
// ===== New messages (zk.rtmd.v1 additions) =====

#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OrderBook {
    #[prost(string, tag="1")]
    pub instrument_code: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub exchange: ::prost::alloc::string::String,
    #[prost(int64, tag="3")]
    pub timestamp_ms: i64,
    #[prost(message, repeated, tag="4")]
    pub buy_levels: ::prost::alloc::vec::Vec<PriceLevel>,
    #[prost(message, repeated, tag="5")]
    pub sell_levels: ::prost::alloc::vec::Vec<PriceLevel>,
}
// ===== Enums (from rtmd.proto, values preserved) =====

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum TickUpdateType {
    TickTypeUnspecified = 0,
    Ob = 1,
    T = 2,
    M = 3,
}
impl TickUpdateType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::TickTypeUnspecified => "TICK_TYPE_UNSPECIFIED",
            Self::Ob => "OB",
            Self::T => "T",
            Self::M => "M",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "TICK_TYPE_UNSPECIFIED" => Some(Self::TickTypeUnspecified),
            "OB" => Some(Self::Ob),
            "T" => Some(Self::T),
            "M" => Some(Self::M),
            _ => None,
        }
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct QueryTickRequest {
    #[prost(string, tag="1")]
    pub instrument_code: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QueryTickResponse {
    #[prost(message, optional, tag="1")]
    pub tick: ::core::option::Option<TickData>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct QueryOrderBookRequest {
    #[prost(string, tag="1")]
    pub instrument_code: ::prost::alloc::string::String,
    #[prost(uint32, optional, tag="2")]
    pub depth: ::core::option::Option<u32>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QueryOrderBookResponse {
    #[prost(message, optional, tag="1")]
    pub orderbook: ::core::option::Option<OrderBook>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct QueryFundingRequest {
    #[prost(string, tag="1")]
    pub instrument_code: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QueryFundingResponse {
    #[prost(message, optional, tag="1")]
    pub funding: ::core::option::Option<FundingRate>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct QueryKlinesRequest {
    #[prost(string, tag="1")]
    pub instrument_code: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub interval: ::prost::alloc::string::String,
    #[prost(uint32, tag="3")]
    pub limit: u32,
    #[prost(int64, optional, tag="4")]
    pub from_ms: ::core::option::Option<i64>,
    #[prost(int64, optional, tag="5")]
    pub to_ms: ::core::option::Option<i64>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QueryKlinesResponse {
    #[prost(message, repeated, tag="1")]
    pub klines: ::prost::alloc::vec::Vec<Kline>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HealthCheckRequest {
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HealthCheckResponse {
    #[prost(string, tag="1")]
    pub status: ::prost::alloc::string::String,
}
// @@protoc_insertion_point(module)
