# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: zk/monitor/v1/monitor.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'zk/monitor/v1/monitor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bzk/monitor/v1/monitor.proto\x12\rzk.monitor.v1\"\xd4\x01\n\x11NotificationEvent\x12\x10\n\x08severity\x18\x01 \x01(\t\x12\x0e\n\x06source\x18\x02 \x01(\t\x12\x0f\n\x07\x63hannel\x18\x03 \x01(\t\x12\x0f\n\x07message\x18\x04 \x01(\t\x12\x14\n\x0ctimestamp_ms\x18\x05 \x01(\x03\x12\x38\n\x04tags\x18\x06 \x03(\x0b\x32*.zk.monitor.v1.NotificationEvent.TagsEntry\x1a+\n\tTagsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x80\x01\n\x0bReconResult\x12\x12\n\nrecon_type\x18\x01 \x01(\t\x12\x12\n\naccount_id\x18\x02 \x01(\x03\x12\x0e\n\x06oms_id\x18\x03 \x01(\t\x12\x16\n\x0emismatch_count\x18\x04 \x01(\x05\x12\x0e\n\x06\x64\x65tail\x18\x05 \x01(\t\x12\x11\n\trun_at_ms\x18\x06 \x01(\x03\"s\n\tAlertRule\x12\x0f\n\x07rule_id\x18\x01 \x01(\t\x12\x0e\n\x06metric\x18\x02 \x01(\t\x12\x11\n\tcondition\x18\x03 \x01(\t\x12\x10\n\x08severity\x18\x04 \x01(\t\x12\x0f\n\x07\x63hannel\x18\x05 \x01(\t\x12\x0f\n\x07\x65nabled\x18\x06 \x01(\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'zk.monitor.v1.monitor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NOTIFICATIONEVENT_TAGSENTRY']._loaded_options = None
  _globals['_NOTIFICATIONEVENT_TAGSENTRY']._serialized_options = b'8\001'
  _globals['_NOTIFICATIONEVENT']._serialized_start=47
  _globals['_NOTIFICATIONEVENT']._serialized_end=259
  _globals['_NOTIFICATIONEVENT_TAGSENTRY']._serialized_start=216
  _globals['_NOTIFICATIONEVENT_TAGSENTRY']._serialized_end=259
  _globals['_RECONRESULT']._serialized_start=262
  _globals['_RECONRESULT']._serialized_end=390
  _globals['_ALERTRULE']._serialized_start=392
  _globals['_ALERTRULE']._serialized_end=507
# @@protoc_insertion_point(module_scope)
