# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from zk_refdata_svc import refdata_pb2 as refdata__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in refdata_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RefdataServiceStub(object):
    """RefdataService — canonical instrument and market-status query service.
    Consumers discover the endpoint via NATS KV (svc.refdata.*).
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.QueryInstrumentById = channel.unary_unary(
                '/zk.refdata.v1.RefdataService/QueryInstrumentById',
                request_serializer=refdata__pb2.QueryInstrumentByIdRequest.SerializeToString,
                response_deserializer=refdata__pb2.InstrumentRefdataResponse.FromString,
                _registered_method=True)
        self.QueryInstrumentByVenueSymbol = channel.unary_unary(
                '/zk.refdata.v1.RefdataService/QueryInstrumentByVenueSymbol',
                request_serializer=refdata__pb2.QueryByVenueSymbolRequest.SerializeToString,
                response_deserializer=refdata__pb2.InstrumentRefdataResponse.FromString,
                _registered_method=True)
        self.ListInstruments = channel.unary_unary(
                '/zk.refdata.v1.RefdataService/ListInstruments',
                request_serializer=refdata__pb2.ListInstrumentsRequest.SerializeToString,
                response_deserializer=refdata__pb2.ListInstrumentsResponse.FromString,
                _registered_method=True)
        self.QueryRefdataWatermark = channel.unary_unary(
                '/zk.refdata.v1.RefdataService/QueryRefdataWatermark',
                request_serializer=refdata__pb2.QueryWatermarkRequest.SerializeToString,
                response_deserializer=refdata__pb2.WatermarkResponse.FromString,
                _registered_method=True)
        self.QueryMarketStatus = channel.unary_unary(
                '/zk.refdata.v1.RefdataService/QueryMarketStatus',
                request_serializer=refdata__pb2.QueryMarketStatusRequest.SerializeToString,
                response_deserializer=refdata__pb2.MarketStatusResponse.FromString,
                _registered_method=True)


class RefdataServiceServicer(object):
    """RefdataService — canonical instrument and market-status query service.
    Consumers discover the endpoint via NATS KV (svc.refdata.*).
    """

    def QueryInstrumentById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryInstrumentByVenueSymbol(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListInstruments(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryRefdataWatermark(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryMarketStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RefdataServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'QueryInstrumentById': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryInstrumentById,
                    request_deserializer=refdata__pb2.QueryInstrumentByIdRequest.FromString,
                    response_serializer=refdata__pb2.InstrumentRefdataResponse.SerializeToString,
            ),
            'QueryInstrumentByVenueSymbol': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryInstrumentByVenueSymbol,
                    request_deserializer=refdata__pb2.QueryByVenueSymbolRequest.FromString,
                    response_serializer=refdata__pb2.InstrumentRefdataResponse.SerializeToString,
            ),
            'ListInstruments': grpc.unary_unary_rpc_method_handler(
                    servicer.ListInstruments,
                    request_deserializer=refdata__pb2.ListInstrumentsRequest.FromString,
                    response_serializer=refdata__pb2.ListInstrumentsResponse.SerializeToString,
            ),
            'QueryRefdataWatermark': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryRefdataWatermark,
                    request_deserializer=refdata__pb2.QueryWatermarkRequest.FromString,
                    response_serializer=refdata__pb2.WatermarkResponse.SerializeToString,
            ),
            'QueryMarketStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryMarketStatus,
                    request_deserializer=refdata__pb2.QueryMarketStatusRequest.FromString,
                    response_serializer=refdata__pb2.MarketStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'zk.refdata.v1.RefdataService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('zk.refdata.v1.RefdataService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RefdataService(object):
    """RefdataService — canonical instrument and market-status query service.
    Consumers discover the endpoint via NATS KV (svc.refdata.*).
    """

    @staticmethod
    def QueryInstrumentById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/zk.refdata.v1.RefdataService/QueryInstrumentById',
            refdata__pb2.QueryInstrumentByIdRequest.SerializeToString,
            refdata__pb2.InstrumentRefdataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryInstrumentByVenueSymbol(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/zk.refdata.v1.RefdataService/QueryInstrumentByVenueSymbol',
            refdata__pb2.QueryByVenueSymbolRequest.SerializeToString,
            refdata__pb2.InstrumentRefdataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListInstruments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/zk.refdata.v1.RefdataService/ListInstruments',
            refdata__pb2.ListInstrumentsRequest.SerializeToString,
            refdata__pb2.ListInstrumentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryRefdataWatermark(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/zk.refdata.v1.RefdataService/QueryRefdataWatermark',
            refdata__pb2.QueryWatermarkRequest.SerializeToString,
            refdata__pb2.WatermarkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryMarketStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/zk.refdata.v1.RefdataService/QueryMarketStatus',
            refdata__pb2.QueryMarketStatusRequest.SerializeToString,
            refdata__pb2.MarketStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
