# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: rtmd.proto
# plugin: python-betterproto
# This file has been @generated

from dataclasses import dataclass
from typing import (
    Dict,
    List,
)

import betterproto


class TickUpdateType(betterproto.Enum):
    TICK_TYPE_UNSPECIFIED = 0
    OB = 1
    T = 2
    M = 3


class KlineKlineType(betterproto.Enum):
    """enum type for kline frequency"""

    KLINE_1MIN = 0
    KLINE_5MIN = 1
    KLINE_15MIN = 2
    KLINE_30MIN = 3
    KLINE_1HOUR = 4
    KLINE_4HOUR = 5
    KLINE_1DAY = 6


@dataclass(eq=False, repr=False)
class PriceLevel(betterproto.Message):
    price: float = betterproto.double_field(1)
    qty: float = betterproto.double_field(2)
    num_of_orders: int = betterproto.int64_field(3)
    num_of_pos: int = betterproto.int64_field(4)


@dataclass(eq=False, repr=False)
class Trade(betterproto.Message):
    price: float = betterproto.double_field(1)
    qty: float = betterproto.double_field(2)
    timestamp: int = betterproto.int64_field(3)
    side: str = betterproto.string_field(4)
    instrument_code: str = betterproto.string_field(5)


@dataclass(eq=False, repr=False)
class TickData(betterproto.Message):
    tick_type: "TickUpdateType" = betterproto.enum_field(1)
    instrument_code: str = betterproto.string_field(2)
    exchange: str = betterproto.string_field(3)
    original_timestamp: int = betterproto.int64_field(4)
    received_timestamp: int = betterproto.int64_field(5)
    volume: float = betterproto.double_field(7)
    latest_trade_price: float = betterproto.double_field(8)
    """for trade"""

    latest_trade_qty: float = betterproto.double_field(9)
    latest_trade_side: str = betterproto.string_field(10)
    buy_price_levels: List["PriceLevel"] = betterproto.message_field(14)
    """for orderbook"""

    sell_price_levels: List["PriceLevel"] = betterproto.message_field(15)


@dataclass(eq=False, repr=False)
class Kline(betterproto.Message):
    timestamp: int = betterproto.int64_field(1)
    kline_end_timestamp: int = betterproto.int64_field(2)
    open: float = betterproto.double_field(3)
    high: float = betterproto.double_field(4)
    close: float = betterproto.double_field(5)
    low: float = betterproto.double_field(6)
    volume: float = betterproto.double_field(7)
    amount: float = betterproto.double_field(8)
    kline_type: "KlineKlineType" = betterproto.enum_field(9)
    symbol: str = betterproto.string_field(10)
    source: str = betterproto.string_field(11)


@dataclass(eq=False, repr=False)
class FundingRate(betterproto.Message):
    instrument_code: str = betterproto.string_field(1)
    exchange: str = betterproto.string_field(2)
    curr_funding_rate_timestamp: int = betterproto.int64_field(3)
    observe_timestamp: int = betterproto.int64_field(12)
    next_payment_timestamp: int = betterproto.int64_field(15)
    funding_rate: float = betterproto.double_field(4)
    mark_price: float = betterproto.double_field(6)
    index_price: float = betterproto.double_field(7)
    next_funding_rate: float = betterproto.double_field(10)
    next_funding_rate_timestamp: int = betterproto.int64_field(13)
    original_message: str = betterproto.string_field(14)


@dataclass(eq=False, repr=False)
class RealtimeSignal(betterproto.Message):
    namespace: str = betterproto.string_field(1)
    instrument: str = betterproto.string_field(2)
    timestamp: int = betterproto.int64_field(3)
    data: Dict[str, float] = betterproto.map_field(
        4, betterproto.TYPE_STRING, betterproto.TYPE_DOUBLE
    )
    data_int: Dict[str, int] = betterproto.map_field(
        6, betterproto.TYPE_STRING, betterproto.TYPE_INT64
    )
    data_str: Dict[str, str] = betterproto.map_field(
        7, betterproto.TYPE_STRING, betterproto.TYPE_STRING
    )
    message: str = betterproto.string_field(5)
