# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: zk/oms/v1/oms.proto, zk/oms/v1/oms_service.proto
# plugin: python-betterproto
# This file has been @generated

from dataclasses import dataclass
from typing import (
    TYPE_CHECKING,
    Dict,
    List,
    Optional,
)

import betterproto
import grpclib
from betterproto.grpc.grpclib_server import ServiceBase

from ...common import v1 as __common_v1__

if TYPE_CHECKING:
    import grpclib.server
    from betterproto.grpc.grpclib_client import MetadataLike
    from grpclib.metadata import Deadline


class OrderStatus(betterproto.Enum):
    UNSPECIFIED = 0
    PENDING = 1
    BOOKED = 2
    PARTIALLY_FILLED = 3
    FILLED = 4
    CANCELLED = 5
    REJECTED = 6


class ExecType(betterproto.Enum):
    UNSPECIFIED = 0
    CANCEL = 1
    PLACING_ORDER = 2


class OmsErrorType(betterproto.Enum):
    OMS_ERR_TYPE_UNSPECIFIED = 0
    OMS_ERR_TYPE_INVALID_REQ = 2
    OMS_ERR_TYPE_REQUEST_REJECTED = 3
    OMS_ERR_TYPE_LIMIT_EXCEEDED = 4
    OMS_ERR_TYPE_INTERNAL_ERROR = 5


class OmsResponseStatus(betterproto.Enum):
    OMS_RESP_STATUS_UNSPECIFIED = 0
    OMS_RESP_STATUS_SUCCESS = 1
    OMS_RESP_STATUS_FAIL = 2


@dataclass(eq=False, repr=False)
class Account(betterproto.Message):
    account_id: int = betterproto.int64_field(1)
    account_code: str = betterproto.string_field(2)
    exch_account_code: str = betterproto.string_field(3)
    per_account_setting: "__common_v1__.ExtraData" = betterproto.message_field(4)


@dataclass(eq=False, repr=False)
class OrderRequest(betterproto.Message):
    order_id: int = betterproto.int64_field(1)
    account_id: int = betterproto.int64_field(2)
    instrument_code: str = betterproto.string_field(3)
    buy_sell_type: "__common_v1__.BuySellType" = betterproto.enum_field(4)
    open_close_type: "__common_v1__.OpenCloseType" = betterproto.enum_field(5)
    order_type: "__common_v1__.BasicOrderType" = betterproto.enum_field(6)
    price: float = betterproto.double_field(7)
    qty: float = betterproto.double_field(8)
    source_id: str = betterproto.string_field(9)
    timestamp: int = betterproto.int64_field(10)
    leverage: float = betterproto.double_field(11)
    extra_properties: "__common_v1__.ExtraData" = betterproto.message_field(12)
    time_inforce_type: "__common_v1__.TimeInForceType" = betterproto.enum_field(13)
    extra_order_tags: List["__common_v1__.ExtraOrderTagType"] = betterproto.enum_field(
        14
    )
    trigger_context: "__common_v1__.TriggerContext" = betterproto.message_field(15)


@dataclass(eq=False, repr=False)
class OrderCancelRequest(betterproto.Message):
    order_id: int = betterproto.int64_field(1)
    exch_order_ref: str = betterproto.string_field(2)
    extra_info_required: "__common_v1__.ExtraData" = betterproto.message_field(3)
    source_id: str = betterproto.string_field(7)
    timestamp: int = betterproto.int64_field(8)
    trigger_context: "__common_v1__.TriggerContext" = betterproto.message_field(9)


@dataclass(eq=False, repr=False)
class Order(betterproto.Message):
    order_id: int = betterproto.int64_field(1)
    exch_order_ref: str = betterproto.string_field(2)
    snapshot_version: int = betterproto.int32_field(3)
    instrument: str = betterproto.string_field(4)
    buy_sell_type: "__common_v1__.BuySellType" = betterproto.enum_field(5)
    open_close_type: "__common_v1__.OpenCloseType" = betterproto.enum_field(6)
    price: float = betterproto.double_field(7)
    qty: float = betterproto.double_field(8)
    filled_qty: float = betterproto.double_field(9)
    filled_avg_price: float = betterproto.double_field(10)
    error_msg: str = betterproto.string_field(11)
    source_id: str = betterproto.string_field(12)
    created_at: int = betterproto.int64_field(13)
    updated_at: int = betterproto.int64_field(14)
    order_status: "OrderStatus" = betterproto.enum_field(15)
    gw_key: str = betterproto.string_field(16)
    instrument_exch: str = betterproto.string_field(17)
    account_id: int = betterproto.int64_field(18)


@dataclass(eq=False, repr=False)
class Fee(betterproto.Message):
    order_id: int = betterproto.int64_field(1)
    fee_symbol: str = betterproto.string_field(2)
    fee_amount: float = betterproto.double_field(3)
    fee_type: "__common_v1__.FeeType" = betterproto.enum_field(4)
    fee_ts: int = betterproto.int64_field(5)


@dataclass(eq=False, repr=False)
class Trade(betterproto.Message):
    order_id: int = betterproto.int64_field(1)
    ext_order_ref: str = betterproto.string_field(2)
    ext_trade_id: str = betterproto.string_field(3)
    filled_qty: float = betterproto.double_field(4)
    filled_price: float = betterproto.double_field(5)
    filled_ts: int = betterproto.int64_field(6)
    buy_sell_type: "__common_v1__.BuySellType" = betterproto.enum_field(7)
    instrument: str = betterproto.string_field(8)
    account_id: int = betterproto.int64_field(9)
    fill_type: "__common_v1__.FillType" = betterproto.enum_field(10)
    fees: List["Fee"] = betterproto.message_field(11)
    exch_pnl: float = betterproto.double_field(12)


@dataclass(eq=False, repr=False)
class ExecMessage(betterproto.Message):
    order_id: int = betterproto.int64_field(1)
    exch_order_ref: str = betterproto.string_field(2)
    timestamp: int = betterproto.int64_field(3)
    exec_type: "ExecType" = betterproto.enum_field(4)
    exec_success: bool = betterproto.bool_field(5)
    error_msg: str = betterproto.string_field(6)
    rejection_info: "__common_v1__.Rejection" = betterproto.message_field(7)


@dataclass(eq=False, repr=False)
class Position(betterproto.Message):
    account_id: int = betterproto.int64_field(1)
    instrument_code: str = betterproto.string_field(2)
    long_short_type: "__common_v1__.LongShortType" = betterproto.enum_field(3)
    instrument_type: "__common_v1__.InstrumentType" = betterproto.enum_field(4)
    total_qty: float = betterproto.double_field(5)
    frozen_qty: float = betterproto.double_field(6)
    avail_qty: float = betterproto.double_field(7)
    sync_timestamp: int = betterproto.int64_field(8)
    update_timestamp: int = betterproto.int64_field(9)
    is_from_exch: bool = betterproto.bool_field(10)
    exch_data_raw: str = betterproto.string_field(11)
    contract_size: float = betterproto.double_field(12)
    margin_pos_info: "__common_v1__.MarginPositionInfo" = betterproto.message_field(13)
    contract_size_adjusted: bool = betterproto.bool_field(14)


@dataclass(eq=False, repr=False)
class Balance(betterproto.Message):
    account_id: int = betterproto.int64_field(1)
    asset: str = betterproto.string_field(2)
    total_qty: float = betterproto.double_field(3)
    frozen_qty: float = betterproto.double_field(4)
    avail_qty: float = betterproto.double_field(5)
    sync_timestamp: int = betterproto.int64_field(6)
    update_timestamp: int = betterproto.int64_field(7)
    is_from_exch: bool = betterproto.bool_field(8)
    exch_data_raw: str = betterproto.string_field(9)


@dataclass(eq=False, repr=False)
class BalanceUpdateEvent(betterproto.Message):
    account_id: int = betterproto.int64_field(1)
    balance_snapshots: List["Balance"] = betterproto.message_field(2)
    timestamp: int = betterproto.int64_field(3)


@dataclass(eq=False, repr=False)
class OrderUpdateEvent(betterproto.Message):
    order_id: int = betterproto.int64_field(1)
    account_id: int = betterproto.int64_field(2)
    order_snapshot: "Order" = betterproto.message_field(3)
    last_trade: "Trade" = betterproto.message_field(4)
    last_fee: "Fee" = betterproto.message_field(5)
    exec_message: "ExecMessage" = betterproto.message_field(6)
    timestamp: int = betterproto.int64_field(7)
    order_source_id: str = betterproto.string_field(8)
    order_inferred_trade: "Trade" = betterproto.message_field(9)
    gw_report_timestamp_ns: int = betterproto.int64_field(10)
    gw_received_at_ns: int = betterproto.int64_field(11)


@dataclass(eq=False, repr=False)
class PositionUpdateEvent(betterproto.Message):
    account_id: int = betterproto.int64_field(1)
    position_snapshots: List["Position"] = betterproto.message_field(2)
    timestamp: int = betterproto.int64_field(4)


@dataclass(eq=False, repr=False)
class OmsSystemEvent(betterproto.Message):
    timestamp: int = betterproto.int64_field(1)
    oms_id: str = betterproto.string_field(2)
    event_type: str = betterproto.string_field(3)
    event_message: str = betterproto.string_field(4)


@dataclass(eq=False, repr=False)
class OmsResponse(betterproto.Message):
    timestamp: int = betterproto.int64_field(1)
    status: "OmsResponseStatus" = betterproto.enum_field(2)
    error_type: "OmsErrorType" = betterproto.enum_field(3)
    message: str = betterproto.string_field(4)


@dataclass(eq=False, repr=False)
class PlaceOrderRequest(betterproto.Message):
    order_request: "OrderRequest" = betterproto.message_field(1)
    audit_meta: "__common_v1__.AuditMeta" = betterproto.message_field(2)
    idempotency_key: str = betterproto.string_field(3)


@dataclass(eq=False, repr=False)
class CancelOrderRequest(betterproto.Message):
    order_cancel_request: "OrderCancelRequest" = betterproto.message_field(1)
    audit_meta: "__common_v1__.AuditMeta" = betterproto.message_field(2)
    idempotency_key: str = betterproto.string_field(3)


@dataclass(eq=False, repr=False)
class BatchPlaceOrdersRequest(betterproto.Message):
    order_requests: List["OrderRequest"] = betterproto.message_field(1)
    audit_meta: "__common_v1__.AuditMeta" = betterproto.message_field(2)


@dataclass(eq=False, repr=False)
class BatchCancelOrdersRequest(betterproto.Message):
    order_cancel_requests: List["OrderCancelRequest"] = betterproto.message_field(1)
    audit_meta: "__common_v1__.AuditMeta" = betterproto.message_field(2)


@dataclass(eq=False, repr=False)
class AlgoOrderRequest(betterproto.Message):
    algo_order_id: int = betterproto.int64_field(1)
    order_requests: List["OrderRequest"] = betterproto.message_field(2)
    algo_type: str = betterproto.string_field(3)
    algo_config: str = betterproto.string_field(4)


@dataclass(eq=False, repr=False)
class CancelAlgoOrderRequest(betterproto.Message):
    algo_order_id: int = betterproto.int64_field(1)


@dataclass(eq=False, repr=False)
class QueryPositionRequest(betterproto.Message):
    account_id: int = betterproto.int64_field(1)
    query_gw: bool = betterproto.bool_field(2)


@dataclass(eq=False, repr=False)
class PositionResponse(betterproto.Message):
    positions: List["Position"] = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class QueryBalancesRequest(betterproto.Message):
    account_id: int = betterproto.int64_field(1)
    query_gw: bool = betterproto.bool_field(2)


@dataclass(eq=False, repr=False)
class QueryBalancesResponse(betterproto.Message):
    account_id: int = betterproto.int64_field(1)
    balances: List["Balance"] = betterproto.message_field(2)
    timestamp: int = betterproto.int64_field(3)


@dataclass(eq=False, repr=False)
class QueryOpenOrderRequest(betterproto.Message):
    account_id: int = betterproto.int64_field(1)
    query_gw: bool = betterproto.bool_field(2)
    pagination: "__common_v1__.PaginationRequest" = betterproto.message_field(3)


@dataclass(eq=False, repr=False)
class QueryOrderDetailRequest(betterproto.Message):
    order_refs: List[str] = betterproto.string_field(1)
    query_gw: bool = betterproto.bool_field(2)


@dataclass(eq=False, repr=False)
class OrderDetailResponse(betterproto.Message):
    orders: List["Order"] = betterproto.message_field(1)
    pagination: "__common_v1__.PaginationResponse" = betterproto.message_field(2)


@dataclass(eq=False, repr=False)
class QueryTradeDetailRequest(betterproto.Message):
    order_refs: List[str] = betterproto.string_field(1)
    query_gw: bool = betterproto.bool_field(2)
    pagination: "__common_v1__.PaginationRequest" = betterproto.message_field(3)


@dataclass(eq=False, repr=False)
class TradeDetailResponse(betterproto.Message):
    trades: List["Trade"] = betterproto.message_field(1)
    pagination: "__common_v1__.PaginationResponse" = betterproto.message_field(2)


@dataclass(eq=False, repr=False)
class QueryInstrumentRefdataRequest(betterproto.Message):
    account_id: int = betterproto.int64_field(1)
    instruments: List[str] = betterproto.string_field(2)


@dataclass(eq=False, repr=False)
class QueryInstrumentRefdataResponse(betterproto.Message):
    instrument_refdata: List["__common_v1__.InstrumentRefData"] = (
        betterproto.message_field(1)
    )


@dataclass(eq=False, repr=False)
class PanicRequest(betterproto.Message):
    panic_account_id: int = betterproto.int64_field(1)
    panic_message: str = betterproto.string_field(2)
    panic_source: str = betterproto.string_field(3)


@dataclass(eq=False, repr=False)
class DontPanicRequest(betterproto.Message):
    panic_account_id: int = betterproto.int64_field(1)


class OmsServiceStub(betterproto.ServiceStub):
    async def place_order(
        self,
        place_order_request: "PlaceOrderRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "OmsResponse":
        return await self._unary_unary(
            "/zk.oms.v1.OMSService/PlaceOrder",
            place_order_request,
            OmsResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def batch_place_orders(
        self,
        batch_place_orders_request: "BatchPlaceOrdersRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "OmsResponse":
        return await self._unary_unary(
            "/zk.oms.v1.OMSService/BatchPlaceOrders",
            batch_place_orders_request,
            OmsResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def cancel_order(
        self,
        cancel_order_request: "CancelOrderRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "OmsResponse":
        return await self._unary_unary(
            "/zk.oms.v1.OMSService/CancelOrder",
            cancel_order_request,
            OmsResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def batch_cancel_orders(
        self,
        batch_cancel_orders_request: "BatchCancelOrdersRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "OmsResponse":
        return await self._unary_unary(
            "/zk.oms.v1.OMSService/BatchCancelOrders",
            batch_cancel_orders_request,
            OmsResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def execute_algo_order(
        self,
        algo_order_request: "AlgoOrderRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "OmsResponse":
        return await self._unary_unary(
            "/zk.oms.v1.OMSService/ExecuteAlgoOrder",
            algo_order_request,
            OmsResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def cancel_algo_order(
        self,
        cancel_algo_order_request: "CancelAlgoOrderRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "OmsResponse":
        return await self._unary_unary(
            "/zk.oms.v1.OMSService/CancelAlgoOrder",
            cancel_algo_order_request,
            OmsResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def panic(
        self,
        panic_request: "PanicRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "OmsResponse":
        return await self._unary_unary(
            "/zk.oms.v1.OMSService/Panic",
            panic_request,
            OmsResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def dont_panic(
        self,
        dont_panic_request: "DontPanicRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "OmsResponse":
        return await self._unary_unary(
            "/zk.oms.v1.OMSService/DontPanic",
            dont_panic_request,
            OmsResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def query_position(
        self,
        query_position_request: "QueryPositionRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "PositionResponse":
        return await self._unary_unary(
            "/zk.oms.v1.OMSService/QueryPosition",
            query_position_request,
            PositionResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def query_balances(
        self,
        query_balances_request: "QueryBalancesRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "QueryBalancesResponse":
        return await self._unary_unary(
            "/zk.oms.v1.OMSService/QueryBalances",
            query_balances_request,
            QueryBalancesResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def query_open_orders(
        self,
        query_open_order_request: "QueryOpenOrderRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "OrderDetailResponse":
        return await self._unary_unary(
            "/zk.oms.v1.OMSService/QueryOpenOrders",
            query_open_order_request,
            OrderDetailResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def query_order_details(
        self,
        query_order_detail_request: "QueryOrderDetailRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "OrderDetailResponse":
        return await self._unary_unary(
            "/zk.oms.v1.OMSService/QueryOrderDetails",
            query_order_detail_request,
            OrderDetailResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def query_trade_details(
        self,
        query_trade_detail_request: "QueryTradeDetailRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "TradeDetailResponse":
        return await self._unary_unary(
            "/zk.oms.v1.OMSService/QueryTradeDetails",
            query_trade_detail_request,
            TradeDetailResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def query_instrument_refdata(
        self,
        query_instrument_refdata_request: "QueryInstrumentRefdataRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "QueryInstrumentRefdataResponse":
        return await self._unary_unary(
            "/zk.oms.v1.OMSService/QueryInstrumentRefdata",
            query_instrument_refdata_request,
            QueryInstrumentRefdataResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def health_check(
        self,
        common_v1_dummy_request: "__common_v1__.DummyRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "__common_v1__.ServiceHealthResponse":
        return await self._unary_unary(
            "/zk.oms.v1.OMSService/HealthCheck",
            common_v1_dummy_request,
            __common_v1__.ServiceHealthResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )


class OmsServiceBase(ServiceBase):

    async def place_order(
        self, place_order_request: "PlaceOrderRequest"
    ) -> "OmsResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def batch_place_orders(
        self, batch_place_orders_request: "BatchPlaceOrdersRequest"
    ) -> "OmsResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def cancel_order(
        self, cancel_order_request: "CancelOrderRequest"
    ) -> "OmsResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def batch_cancel_orders(
        self, batch_cancel_orders_request: "BatchCancelOrdersRequest"
    ) -> "OmsResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def execute_algo_order(
        self, algo_order_request: "AlgoOrderRequest"
    ) -> "OmsResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def cancel_algo_order(
        self, cancel_algo_order_request: "CancelAlgoOrderRequest"
    ) -> "OmsResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def panic(self, panic_request: "PanicRequest") -> "OmsResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def dont_panic(self, dont_panic_request: "DontPanicRequest") -> "OmsResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def query_position(
        self, query_position_request: "QueryPositionRequest"
    ) -> "PositionResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def query_balances(
        self, query_balances_request: "QueryBalancesRequest"
    ) -> "QueryBalancesResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def query_open_orders(
        self, query_open_order_request: "QueryOpenOrderRequest"
    ) -> "OrderDetailResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def query_order_details(
        self, query_order_detail_request: "QueryOrderDetailRequest"
    ) -> "OrderDetailResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def query_trade_details(
        self, query_trade_detail_request: "QueryTradeDetailRequest"
    ) -> "TradeDetailResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def query_instrument_refdata(
        self, query_instrument_refdata_request: "QueryInstrumentRefdataRequest"
    ) -> "QueryInstrumentRefdataResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def health_check(
        self, common_v1_dummy_request: "__common_v1__.DummyRequest"
    ) -> "__common_v1__.ServiceHealthResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def __rpc_place_order(
        self, stream: "grpclib.server.Stream[PlaceOrderRequest, OmsResponse]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.place_order(request)
        await stream.send_message(response)

    async def __rpc_batch_place_orders(
        self, stream: "grpclib.server.Stream[BatchPlaceOrdersRequest, OmsResponse]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.batch_place_orders(request)
        await stream.send_message(response)

    async def __rpc_cancel_order(
        self, stream: "grpclib.server.Stream[CancelOrderRequest, OmsResponse]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.cancel_order(request)
        await stream.send_message(response)

    async def __rpc_batch_cancel_orders(
        self, stream: "grpclib.server.Stream[BatchCancelOrdersRequest, OmsResponse]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.batch_cancel_orders(request)
        await stream.send_message(response)

    async def __rpc_execute_algo_order(
        self, stream: "grpclib.server.Stream[AlgoOrderRequest, OmsResponse]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.execute_algo_order(request)
        await stream.send_message(response)

    async def __rpc_cancel_algo_order(
        self, stream: "grpclib.server.Stream[CancelAlgoOrderRequest, OmsResponse]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.cancel_algo_order(request)
        await stream.send_message(response)

    async def __rpc_panic(
        self, stream: "grpclib.server.Stream[PanicRequest, OmsResponse]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.panic(request)
        await stream.send_message(response)

    async def __rpc_dont_panic(
        self, stream: "grpclib.server.Stream[DontPanicRequest, OmsResponse]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.dont_panic(request)
        await stream.send_message(response)

    async def __rpc_query_position(
        self, stream: "grpclib.server.Stream[QueryPositionRequest, PositionResponse]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.query_position(request)
        await stream.send_message(response)

    async def __rpc_query_balances(
        self,
        stream: "grpclib.server.Stream[QueryBalancesRequest, QueryBalancesResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.query_balances(request)
        await stream.send_message(response)

    async def __rpc_query_open_orders(
        self,
        stream: "grpclib.server.Stream[QueryOpenOrderRequest, OrderDetailResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.query_open_orders(request)
        await stream.send_message(response)

    async def __rpc_query_order_details(
        self,
        stream: "grpclib.server.Stream[QueryOrderDetailRequest, OrderDetailResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.query_order_details(request)
        await stream.send_message(response)

    async def __rpc_query_trade_details(
        self,
        stream: "grpclib.server.Stream[QueryTradeDetailRequest, TradeDetailResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.query_trade_details(request)
        await stream.send_message(response)

    async def __rpc_query_instrument_refdata(
        self,
        stream: "grpclib.server.Stream[QueryInstrumentRefdataRequest, QueryInstrumentRefdataResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.query_instrument_refdata(request)
        await stream.send_message(response)

    async def __rpc_health_check(
        self,
        stream: "grpclib.server.Stream[__common_v1__.DummyRequest, __common_v1__.ServiceHealthResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.health_check(request)
        await stream.send_message(response)

    def __mapping__(self) -> Dict[str, grpclib.const.Handler]:
        return {
            "/zk.oms.v1.OMSService/PlaceOrder": grpclib.const.Handler(
                self.__rpc_place_order,
                grpclib.const.Cardinality.UNARY_UNARY,
                PlaceOrderRequest,
                OmsResponse,
            ),
            "/zk.oms.v1.OMSService/BatchPlaceOrders": grpclib.const.Handler(
                self.__rpc_batch_place_orders,
                grpclib.const.Cardinality.UNARY_UNARY,
                BatchPlaceOrdersRequest,
                OmsResponse,
            ),
            "/zk.oms.v1.OMSService/CancelOrder": grpclib.const.Handler(
                self.__rpc_cancel_order,
                grpclib.const.Cardinality.UNARY_UNARY,
                CancelOrderRequest,
                OmsResponse,
            ),
            "/zk.oms.v1.OMSService/BatchCancelOrders": grpclib.const.Handler(
                self.__rpc_batch_cancel_orders,
                grpclib.const.Cardinality.UNARY_UNARY,
                BatchCancelOrdersRequest,
                OmsResponse,
            ),
            "/zk.oms.v1.OMSService/ExecuteAlgoOrder": grpclib.const.Handler(
                self.__rpc_execute_algo_order,
                grpclib.const.Cardinality.UNARY_UNARY,
                AlgoOrderRequest,
                OmsResponse,
            ),
            "/zk.oms.v1.OMSService/CancelAlgoOrder": grpclib.const.Handler(
                self.__rpc_cancel_algo_order,
                grpclib.const.Cardinality.UNARY_UNARY,
                CancelAlgoOrderRequest,
                OmsResponse,
            ),
            "/zk.oms.v1.OMSService/Panic": grpclib.const.Handler(
                self.__rpc_panic,
                grpclib.const.Cardinality.UNARY_UNARY,
                PanicRequest,
                OmsResponse,
            ),
            "/zk.oms.v1.OMSService/DontPanic": grpclib.const.Handler(
                self.__rpc_dont_panic,
                grpclib.const.Cardinality.UNARY_UNARY,
                DontPanicRequest,
                OmsResponse,
            ),
            "/zk.oms.v1.OMSService/QueryPosition": grpclib.const.Handler(
                self.__rpc_query_position,
                grpclib.const.Cardinality.UNARY_UNARY,
                QueryPositionRequest,
                PositionResponse,
            ),
            "/zk.oms.v1.OMSService/QueryBalances": grpclib.const.Handler(
                self.__rpc_query_balances,
                grpclib.const.Cardinality.UNARY_UNARY,
                QueryBalancesRequest,
                QueryBalancesResponse,
            ),
            "/zk.oms.v1.OMSService/QueryOpenOrders": grpclib.const.Handler(
                self.__rpc_query_open_orders,
                grpclib.const.Cardinality.UNARY_UNARY,
                QueryOpenOrderRequest,
                OrderDetailResponse,
            ),
            "/zk.oms.v1.OMSService/QueryOrderDetails": grpclib.const.Handler(
                self.__rpc_query_order_details,
                grpclib.const.Cardinality.UNARY_UNARY,
                QueryOrderDetailRequest,
                OrderDetailResponse,
            ),
            "/zk.oms.v1.OMSService/QueryTradeDetails": grpclib.const.Handler(
                self.__rpc_query_trade_details,
                grpclib.const.Cardinality.UNARY_UNARY,
                QueryTradeDetailRequest,
                TradeDetailResponse,
            ),
            "/zk.oms.v1.OMSService/QueryInstrumentRefdata": grpclib.const.Handler(
                self.__rpc_query_instrument_refdata,
                grpclib.const.Cardinality.UNARY_UNARY,
                QueryInstrumentRefdataRequest,
                QueryInstrumentRefdataResponse,
            ),
            "/zk.oms.v1.OMSService/HealthCheck": grpclib.const.Handler(
                self.__rpc_health_check,
                grpclib.const.Cardinality.UNARY_UNARY,
                __common_v1__.DummyRequest,
                __common_v1__.ServiceHealthResponse,
            ),
        }
# legacy-betterproto-compat-start
# Compatibility aliases for older BetterProto output.
OMSErrorType = OmsErrorType
OMSSystemEvent = OmsSystemEvent
OMSResponse = OmsResponse
type.__setattr__(OrderStatus.__class__, "ORDER_STATUS_UNSPECIFIED", OrderStatus.UNSPECIFIED)
OrderStatus._member_map_["ORDER_STATUS_UNSPECIFIED"] = OrderStatus.UNSPECIFIED
type.__setattr__(OrderStatus.__class__, "ORDER_STATUS_PENDING", OrderStatus.PENDING)
OrderStatus._member_map_["ORDER_STATUS_PENDING"] = OrderStatus.PENDING
type.__setattr__(OrderStatus.__class__, "ORDER_STATUS_BOOKED", OrderStatus.BOOKED)
OrderStatus._member_map_["ORDER_STATUS_BOOKED"] = OrderStatus.BOOKED
type.__setattr__(OrderStatus.__class__, "ORDER_STATUS_PARTIALLY_FILLED", OrderStatus.PARTIALLY_FILLED)
OrderStatus._member_map_["ORDER_STATUS_PARTIALLY_FILLED"] = OrderStatus.PARTIALLY_FILLED
type.__setattr__(OrderStatus.__class__, "ORDER_STATUS_FILLED", OrderStatus.FILLED)
OrderStatus._member_map_["ORDER_STATUS_FILLED"] = OrderStatus.FILLED
type.__setattr__(OrderStatus.__class__, "ORDER_STATUS_CANCELLED", OrderStatus.CANCELLED)
OrderStatus._member_map_["ORDER_STATUS_CANCELLED"] = OrderStatus.CANCELLED
type.__setattr__(OrderStatus.__class__, "ORDER_STATUS_REJECTED", OrderStatus.REJECTED)
OrderStatus._member_map_["ORDER_STATUS_REJECTED"] = OrderStatus.REJECTED
type.__setattr__(ExecType.__class__, "EXEC_TYPE_UNSPECIFIED", ExecType.UNSPECIFIED)
ExecType._member_map_["EXEC_TYPE_UNSPECIFIED"] = ExecType.UNSPECIFIED
type.__setattr__(ExecType.__class__, "EXEC_TYPE_CANCEL", ExecType.CANCEL)
ExecType._member_map_["EXEC_TYPE_CANCEL"] = ExecType.CANCEL
type.__setattr__(ExecType.__class__, "EXEC_TYPE_PLACING_ORDER", ExecType.PLACING_ORDER)
ExecType._member_map_["EXEC_TYPE_PLACING_ORDER"] = ExecType.PLACING_ORDER
# legacy-betterproto-compat-end
