# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: zk/pilot/v1/bootstrap.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'zk/pilot/v1/bootstrap.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from zk.config.v1 import config_pb2 as zk_dot_config_dot_v1_dot_config__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bzk/pilot/v1/bootstrap.proto\x12\x0bzk.pilot.v1\x1a\x19zk/config/v1/config.proto\"\xe3\x01\n\x18\x42ootstrapRegisterRequest\x12\r\n\x05token\x18\x01 \x01(\t\x12\x12\n\nlogical_id\x18\x02 \x01(\t\x12\x15\n\rinstance_type\x18\x03 \x01(\t\x12\x0b\n\x03\x65nv\x18\x04 \x01(\t\x12L\n\x0cruntime_info\x18\x05 \x03(\x0b\x32\x36.zk.pilot.v1.BootstrapRegisterRequest.RuntimeInfoEntry\x1a\x32\n\x10RuntimeInfoEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xd9\x02\n\x19\x42ootstrapRegisterResponse\x12\x18\n\x10owner_session_id\x18\x01 \x01(\t\x12\x0e\n\x06kv_key\x18\x02 \x01(\t\x12\x10\n\x08lock_key\x18\x03 \x01(\t\x12\x14\n\x0clease_ttl_ms\x18\x04 \x01(\x03\x12\x13\n\x0binstance_id\x18\x05 \x01(\x05\x12\x19\n\x11scoped_credential\x18\x06 \x01(\t\x12\x0e\n\x06status\x18\x07 \x01(\t\x12\x15\n\rerror_message\x18\x08 \x01(\t\x12\x16\n\x0eruntime_config\x18\t \x01(\t\x12\x16\n\x0eserver_time_ms\x18\n \x01(\x03\x12\x35\n\x0f\x63onfig_metadata\x18\x0b \x01(\x0b\x32\x1c.zk.config.v1.ConfigMetadata\x12,\n\x0bsecret_refs\x18\x0c \x03(\x0b\x32\x17.zk.config.v1.SecretRef\"n\n\x1a\x42ootstrapDeregisterRequest\x12\x18\n\x10owner_session_id\x18\x01 \x01(\t\x12\x12\n\nlogical_id\x18\x02 \x01(\t\x12\x15\n\rinstance_type\x18\x03 \x01(\t\x12\x0b\n\x03\x65nv\x18\x04 \x01(\t\"E\n\x1b\x42ootstrapDeregisterResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x15\n\rerror_message\x18\x02 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'zk.pilot.v1.bootstrap_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BOOTSTRAPREGISTERREQUEST_RUNTIMEINFOENTRY']._loaded_options = None
  _globals['_BOOTSTRAPREGISTERREQUEST_RUNTIMEINFOENTRY']._serialized_options = b'8\001'
  _globals['_BOOTSTRAPREGISTERREQUEST']._serialized_start=72
  _globals['_BOOTSTRAPREGISTERREQUEST']._serialized_end=299
  _globals['_BOOTSTRAPREGISTERREQUEST_RUNTIMEINFOENTRY']._serialized_start=249
  _globals['_BOOTSTRAPREGISTERREQUEST_RUNTIMEINFOENTRY']._serialized_end=299
  _globals['_BOOTSTRAPREGISTERRESPONSE']._serialized_start=302
  _globals['_BOOTSTRAPREGISTERRESPONSE']._serialized_end=647
  _globals['_BOOTSTRAPDEREGISTERREQUEST']._serialized_start=649
  _globals['_BOOTSTRAPDEREGISTERREQUEST']._serialized_end=759
  _globals['_BOOTSTRAPDEREGISTERRESPONSE']._serialized_start=761
  _globals['_BOOTSTRAPDEREGISTERRESPONSE']._serialized_end=830
# @@protoc_insertion_point(module_scope)
