# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: zk/pilot/v1/pilot_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'zk/pilot/v1/pilot_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from zk.common.v1 import common_pb2 as zk_dot_common_dot_v1_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fzk/pilot/v1/pilot_service.proto\x12\x0bzk.pilot.v1\x1a\x19zk/common/v1/common.proto\"+\n\x13ListServicesRequest\x12\x14\n\x0cservice_type\x18\x01 \x01(\t\"\x87\x01\n\x0cServiceEntry\x12\x12\n\nservice_id\x18\x01 \x01(\t\x12\x14\n\x0cservice_type\x18\x02 \x01(\t\x12\x13\n\x0binstance_id\x18\x03 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x04 \x01(\t\x12\r\n\x05state\x18\x05 \x01(\t\x12\x18\n\x10registered_at_ms\x18\x06 \x01(\x03\"y\n\x14ListServicesResponse\x12+\n\x08services\x18\x01 \x03(\x0b\x32\x19.zk.pilot.v1.ServiceEntry\x12\x34\n\npagination\x18\x02 \x01(\x0b\x32 .zk.common.v1.PaginationResponse\"\x8b\x01\n\x12SendCommandRequest\x12\x19\n\x11target_service_id\x18\x01 \x01(\t\x12-\n\x07\x63ommand\x18\x02 \x01(\x0b\x32\x1c.zk.common.v1.ControlCommand\x12+\n\naudit_meta\x18\x03 \x01(\x0b\x32\x17.zk.common.v1.AuditMeta\"+\n\x14ListInstancesRequest\x12\x13\n\x0bstrategy_id\x18\x01 \x01(\t\"_\n\rInstanceEntry\x12\x13\n\x0binstance_id\x18\x01 \x01(\t\x12\x13\n\x0bstrategy_id\x18\x02 \x01(\t\x12\r\n\x05state\x18\x03 \x01(\t\x12\x15\n\rstarted_at_ms\x18\x04 \x01(\x03\"F\n\x15ListInstancesResponse\x12-\n\tinstances\x18\x01 \x03(\x0b\x32\x1a.zk.pilot.v1.InstanceEntry2\xd5\x02\n\x0cPilotService\x12S\n\x0cListServices\x12 .zk.pilot.v1.ListServicesRequest\x1a!.zk.pilot.v1.ListServicesResponse\x12H\n\x0bSendCommand\x12\x1f.zk.pilot.v1.SendCommandRequest\x1a\x18.zk.common.v1.CommandAck\x12V\n\rListInstances\x12!.zk.pilot.v1.ListInstancesRequest\x1a\".zk.pilot.v1.ListInstancesResponse\x12N\n\x0bHealthCheck\x12\x1a.zk.common.v1.DummyRequest\x1a#.zk.common.v1.ServiceHealthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'zk.pilot.v1.pilot_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LISTSERVICESREQUEST']._serialized_start=75
  _globals['_LISTSERVICESREQUEST']._serialized_end=118
  _globals['_SERVICEENTRY']._serialized_start=121
  _globals['_SERVICEENTRY']._serialized_end=256
  _globals['_LISTSERVICESRESPONSE']._serialized_start=258
  _globals['_LISTSERVICESRESPONSE']._serialized_end=379
  _globals['_SENDCOMMANDREQUEST']._serialized_start=382
  _globals['_SENDCOMMANDREQUEST']._serialized_end=521
  _globals['_LISTINSTANCESREQUEST']._serialized_start=523
  _globals['_LISTINSTANCESREQUEST']._serialized_end=566
  _globals['_INSTANCEENTRY']._serialized_start=568
  _globals['_INSTANCEENTRY']._serialized_end=663
  _globals['_LISTINSTANCESRESPONSE']._serialized_start=665
  _globals['_LISTINSTANCESRESPONSE']._serialized_end=735
  _globals['_PILOTSERVICE']._serialized_start=738
  _globals['_PILOTSERVICE']._serialized_end=1079
# @@protoc_insertion_point(module_scope)
