// @generated
// This file is @generated by prost-build.
// @dataclass
// class OrderInfo(betterproto.Message):
//     """this message is for OMS to recover data from trade message"""
//
//     exch_order_ref: str = betterproto.string_field(1)
//     client_order_id: str = betterproto.string_field(2)
//     instrument: str = betterproto.string_field(3)
//     exch_account_id: str = betterproto.string_field(4)
//     buy_sell_type: common.BuySellType = betterproto.enum_field(5)
//     place_qty: float = betterproto.double_field(6)
//     place_price: float = betterproto.double_field(7)

#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OrderInfo {
    #[prost(string, tag="1")]
    pub exch_order_ref: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub client_order_id: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub instrument: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub exch_account_id: ::prost::alloc::string::String,
    #[prost(enumeration="super::common::BuySellType", tag="5")]
    pub buy_sell_type: i32,
    #[prost(double, tag="6")]
    pub place_qty: f64,
    #[prost(double, tag="7")]
    pub place_price: f64,
}
/// deprecated; use common.Rejection instead
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExchErrorInfo {
    /// exchange error code
    #[prost(int32, tag="1")]
    pub error_code: i32,
    #[prost(string, tag="2")]
    pub error_message: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OrderReport {
    #[prost(string, tag="3")]
    pub exchange: ::prost::alloc::string::String,
    #[prost(int64, tag="5")]
    pub account_id: i64,
    /// required
    #[prost(string, tag="1")]
    pub exch_order_ref: ::prost::alloc::string::String,
    /// optional
    #[prost(int64, tag="2")]
    pub order_id: i64,
    /// optional
    #[prost(string, tag="7")]
    pub extra_order_id: ::prost::alloc::string::String,
    #[prost(enumeration="OrderSourceType", tag="8")]
    pub order_source_type: i32,
    #[prost(message, repeated, tag="4")]
    pub order_report_entries: ::prost::alloc::vec::Vec<OrderReportEntry>,
    #[prost(int64, tag="6")]
    pub update_timestamp: i64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OrderReportEntry {
    #[prost(enumeration="OrderReportType", tag="1")]
    pub report_type: i32,
    #[prost(oneof="order_report_entry::Report", tags="7, 8, 9, 10, 11")]
    pub report: ::core::option::Option<order_report_entry::Report>,
}
/// Nested message and enum types in `OrderReportEntry`.
pub mod order_report_entry {
    #[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Report {
        #[prost(message, tag="7")]
        TradeReport(super::TradeReport),
        #[prost(message, tag="8")]
        OrderStateReport(super::OrderStateReport),
        #[prost(message, tag="9")]
        OrderIdLinkageReport(super::OrderIdLinkageReport),
        #[prost(message, tag="10")]
        FeeReport(super::FeeReport),
        #[prost(message, tag="11")]
        ExecReport(super::ExecReport),
    }
}
/// gateway should generate at least 1 order id linkage report
/// back to OMS
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OrderIdLinkageReport {
    #[prost(string, tag="1")]
    pub exch_order_ref: ::prost::alloc::string::String,
    #[prost(int64, tag="2")]
    pub order_id: i64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OrderStateReport {
    #[prost(enumeration="ExchangeOrderStatus", tag="1")]
    pub exch_order_status: i32,
    #[prost(double, tag="2")]
    pub filled_qty: f64,
    #[prost(double, tag="3")]
    pub unfilled_qty: f64,
    /// avg price for all filled trades; 0 means no info provided;
    #[prost(double, tag="4")]
    pub avg_price: f64,
    /// ExchErrorInfo error_info = 5;
    #[prost(message, optional, tag="6")]
    pub order_info: ::core::option::Option<OrderInfo>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TradeReport {
    #[prost(string, tag="1")]
    pub exch_trade_id: ::prost::alloc::string::String,
    #[prost(double, tag="2")]
    pub filled_qty: f64,
    #[prost(double, tag="3")]
    pub filled_price: f64,
    #[prost(enumeration="super::common::FillType", tag="4")]
    pub fill_type: i32,
    #[prost(int64, tag="5")]
    pub filled_ts: i64,
    #[prost(double, tag="6")]
    pub exch_pnl: f64,
    #[prost(message, optional, tag="7")]
    pub order_info: ::core::option::Option<OrderInfo>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FeeReport {
    #[prost(enumeration="FeeUnitType", tag="1")]
    pub fee_unit_type: i32,
    #[prost(double, tag="2")]
    pub fee_qty: f64,
    #[prost(string, tag="3")]
    pub fee_symbol: ::prost::alloc::string::String,
    #[prost(enumeration="super::common::FeeType", tag="4")]
    pub fee_type: i32,
    #[prost(int64, tag="5")]
    pub fee_ts: i64,
    #[prost(string, tag="6")]
    pub inst_symbol: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExecReport {
    #[prost(string, tag="1")]
    pub exec_id: ::prost::alloc::string::String,
    #[prost(enumeration="ExchExecType", tag="2")]
    pub exec_type: i32,
    /// wrap execType etc.
    #[prost(string, tag="3")]
    pub exec_message: ::prost::alloc::string::String,
    /// deprecated;
    #[prost(message, optional, tag="4")]
    pub error_info: ::core::option::Option<ExchErrorInfo>,
    #[prost(message, optional, tag="5")]
    pub rejection_info: ::core::option::Option<super::common::Rejection>,
}
/// shared structure
/// for both spot positions (balances) and futures positions (with leverage/margins)
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PositionReport {
    #[prost(string, tag="1")]
    pub instrument_code: ::prost::alloc::string::String,
    #[prost(enumeration="super::common::InstrumentType", tag="2")]
    pub instrument_type: i32,
    #[prost(enumeration="super::common::LongShortType", tag="3")]
    pub long_short_type: i32,
    #[prost(string, tag="4")]
    pub exch_account_code: ::prost::alloc::string::String,
    /// account id in OMS
    #[prost(int64, tag="15")]
    pub account_id: i64,
    #[prost(double, tag="5")]
    pub qty: f64,
    #[prost(double, tag="6")]
    pub avail_qty: f64,
    #[prost(double, tag="7")]
    pub value: f64,
    // for margin trading positions
    //     double leverage = 8;
    //     double entry_price = 9;
    //     double mark_price = 10;
    //     double liquidation_price = 11;
    //     double margin = 12;

    #[prost(int64, tag="13")]
    pub update_timestamp: i64,
    /// raw message from exchange
    #[prost(string, tag="14")]
    pub message_raw: ::prost::alloc::string::String,
    #[prost(message, optional, tag="22")]
    pub margin_pos_info: ::core::option::Option<super::common::MarginPositionInfo>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BalanceUpdate {
    #[prost(message, repeated, tag="1")]
    pub balances: ::prost::alloc::vec::Vec<PositionReport>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GatewaySystemEvent {
    #[prost(string, tag="1")]
    pub gw_name: ::prost::alloc::string::String,
    #[prost(enumeration="GatewayEventType", tag="2")]
    pub event_type: i32,
    #[prost(string, tag="3")]
    pub service_endpoint: ::prost::alloc::string::String,
    #[prost(int64, tag="4")]
    pub event_timestamp: i64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AccountSummaryEntry {
    #[prost(string, tag="1")]
    pub account_code: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub cash_asset: ::prost::alloc::string::String,
    #[prost(double, tag="3")]
    pub total_avail_value: f64,
    #[prost(double, tag="4")]
    pub total_value: f64,
    #[prost(double, tag="5")]
    pub total_frozen_value: f64,
    #[prost(double, tag="6")]
    pub unrealized_pnl: f64,
    #[prost(double, tag="7")]
    pub leverage: f64,
    #[prost(enumeration="MarginModeType", tag="8")]
    pub margin_mode_type: i32,
    #[prost(double, tag="9")]
    pub total_margin: f64,
    #[prost(int64, tag="14")]
    pub update_timestamp: i64,
    #[prost(string, tag="15")]
    pub original_info: ::prost::alloc::string::String,
    #[prost(double, tag="16")]
    pub buying_power: f64,
    #[prost(double, tag="17")]
    pub maintenance_margin: f64,
    #[prost(double, tag="18")]
    pub net_liquidation_value: f64,
    #[prost(enumeration="super::common::AccountType", tag="19")]
    pub account_type: i32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AccountSettingEntry {
    #[prost(string, tag="1")]
    pub exch_account_id: ::prost::alloc::string::String,
    #[prost(double, tag="2")]
    pub long_leverage: f64,
    #[prost(double, tag="3")]
    pub short_leverage: f64,
    #[prost(enumeration="MarginModeType", tag="4")]
    pub margin_mode_type: i32,
    #[prost(string, tag="5")]
    pub instrument: ::prost::alloc::string::String,
    #[prost(enumeration="super::common::BrokerType", tag="6")]
    pub broker_type: i32,
    #[prost(enumeration="super::common::AccountType", tag="7")]
    pub account_type: i32,
    /// account denomination currency (e.g., "USD")
    #[prost(string, tag="8")]
    pub base_currency: ::prost::alloc::string::String,
    /// e.g., "SEC Reg-T", "FCA"
    #[prost(string, tag="9")]
    pub regulatory_info: ::prost::alloc::string::String,
    /// broker-specific config
    #[prost(map="string, string", tag="10")]
    pub extra_settings: ::std::collections::HashMap<::prost::alloc::string::String, ::prost::alloc::string::String>,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum FeeUnitType {
    FeeTypeUnspecified = 0,
    FeeFiat = 1,
    FeeValueCoin = 2,
    FeeGasCoin = 3,
}
impl FeeUnitType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            FeeUnitType::FeeTypeUnspecified => "FEE_TYPE_UNSPECIFIED",
            FeeUnitType::FeeFiat => "FEE_FIAT",
            FeeUnitType::FeeValueCoin => "FEE_VALUE_COIN",
            FeeUnitType::FeeGasCoin => "FEE_GAS_COIN",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "FEE_TYPE_UNSPECIFIED" => Some(Self::FeeTypeUnspecified),
            "FEE_FIAT" => Some(Self::FeeFiat),
            "FEE_VALUE_COIN" => Some(Self::FeeValueCoin),
            "FEE_GAS_COIN" => Some(Self::FeeGasCoin),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum OrderReportType {
    OrderRepTypeUnspecified = 0,
    OrderRepTypeTrade = 1,
    OrderRepTypeState = 2,
    OrderRepTypeFee = 3,
    OrderRepTypeLinkage = 4,
    /// wraps all other acks/rejects
    OrderRepTypeExec = 5,
}
impl OrderReportType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            OrderReportType::OrderRepTypeUnspecified => "ORDER_REP_TYPE_UNSPECIFIED",
            OrderReportType::OrderRepTypeTrade => "ORDER_REP_TYPE_TRADE",
            OrderReportType::OrderRepTypeState => "ORDER_REP_TYPE_STATE",
            OrderReportType::OrderRepTypeFee => "ORDER_REP_TYPE_FEE",
            OrderReportType::OrderRepTypeLinkage => "ORDER_REP_TYPE_LINKAGE",
            OrderReportType::OrderRepTypeExec => "ORDER_REP_TYPE_EXEC",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "ORDER_REP_TYPE_UNSPECIFIED" => Some(Self::OrderRepTypeUnspecified),
            "ORDER_REP_TYPE_TRADE" => Some(Self::OrderRepTypeTrade),
            "ORDER_REP_TYPE_STATE" => Some(Self::OrderRepTypeState),
            "ORDER_REP_TYPE_FEE" => Some(Self::OrderRepTypeFee),
            "ORDER_REP_TYPE_LINKAGE" => Some(Self::OrderRepTypeLinkage),
            "ORDER_REP_TYPE_EXEC" => Some(Self::OrderRepTypeExec),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ExchangeOrderStatus {
    ExchOrderStatusUnspecified = 0,
    ExchOrderStatusBooked = 1,
    ExchOrderStatusPartialFilled = 2,
    ExchOrderStatusFilled = 3,
    ExchOrderStatusCancelled = 4,
    ExchOrderStatusExchRejected = 5,
    ExchOrderStatusExpired = 6,
}
impl ExchangeOrderStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            ExchangeOrderStatus::ExchOrderStatusUnspecified => "EXCH_ORDER_STATUS_UNSPECIFIED",
            ExchangeOrderStatus::ExchOrderStatusBooked => "EXCH_ORDER_STATUS_BOOKED",
            ExchangeOrderStatus::ExchOrderStatusPartialFilled => "EXCH_ORDER_STATUS_PARTIAL_FILLED",
            ExchangeOrderStatus::ExchOrderStatusFilled => "EXCH_ORDER_STATUS_FILLED",
            ExchangeOrderStatus::ExchOrderStatusCancelled => "EXCH_ORDER_STATUS_CANCELLED",
            ExchangeOrderStatus::ExchOrderStatusExchRejected => "EXCH_ORDER_STATUS_EXCH_REJECTED",
            ExchangeOrderStatus::ExchOrderStatusExpired => "EXCH_ORDER_STATUS_EXPIRED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "EXCH_ORDER_STATUS_UNSPECIFIED" => Some(Self::ExchOrderStatusUnspecified),
            "EXCH_ORDER_STATUS_BOOKED" => Some(Self::ExchOrderStatusBooked),
            "EXCH_ORDER_STATUS_PARTIAL_FILLED" => Some(Self::ExchOrderStatusPartialFilled),
            "EXCH_ORDER_STATUS_FILLED" => Some(Self::ExchOrderStatusFilled),
            "EXCH_ORDER_STATUS_CANCELLED" => Some(Self::ExchOrderStatusCancelled),
            "EXCH_ORDER_STATUS_EXCH_REJECTED" => Some(Self::ExchOrderStatusExchRejected),
            "EXCH_ORDER_STATUS_EXPIRED" => Some(Self::ExchOrderStatusExpired),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ExchExecType {
    Unspecified = 0,
    Rejected = 1,
    CancelReject = 2,
    Replaced = 3,
    Restated = 4,
}
impl ExchExecType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            ExchExecType::Unspecified => "EXCH_EXEC_TYPE_UNSPECIFIED",
            ExchExecType::Rejected => "EXCH_EXEC_TYPE_REJECTED",
            ExchExecType::CancelReject => "EXCH_EXEC_TYPE_CANCEL_REJECT",
            ExchExecType::Replaced => "EXCH_EXEC_TYPE_REPLACED",
            ExchExecType::Restated => "EXCH_EXEC_TYPE_RESTATED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "EXCH_EXEC_TYPE_UNSPECIFIED" => Some(Self::Unspecified),
            "EXCH_EXEC_TYPE_REJECTED" => Some(Self::Rejected),
            "EXCH_EXEC_TYPE_CANCEL_REJECT" => Some(Self::CancelReject),
            "EXCH_EXEC_TYPE_REPLACED" => Some(Self::Replaced),
            "EXCH_EXEC_TYPE_RESTATED" => Some(Self::Restated),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum OrderSourceType {
    OrderSourceUnspecified = 0,
    OrderSourceTq = 1,
    OrderSourceNonTq = 2,
    OrderSourceUnknown = 3,
}
impl OrderSourceType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            OrderSourceType::OrderSourceUnspecified => "ORDER_SOURCE_UNSPECIFIED",
            OrderSourceType::OrderSourceTq => "ORDER_SOURCE_TQ",
            OrderSourceType::OrderSourceNonTq => "ORDER_SOURCE_NON_TQ",
            OrderSourceType::OrderSourceUnknown => "ORDER_SOURCE_UNKNOWN",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "ORDER_SOURCE_UNSPECIFIED" => Some(Self::OrderSourceUnspecified),
            "ORDER_SOURCE_TQ" => Some(Self::OrderSourceTq),
            "ORDER_SOURCE_NON_TQ" => Some(Self::OrderSourceNonTq),
            "ORDER_SOURCE_UNKNOWN" => Some(Self::OrderSourceUnknown),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum MarginModeType {
    MarginUnspecified = 0,
    MarginCross = 1,
    MarginIsolated = 2,
    MarginUnknown = 3,
}
impl MarginModeType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            MarginModeType::MarginUnspecified => "MARGIN_UNSPECIFIED",
            MarginModeType::MarginCross => "MARGIN_CROSS",
            MarginModeType::MarginIsolated => "MARGIN_ISOLATED",
            MarginModeType::MarginUnknown => "MARGIN_UNKNOWN",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "MARGIN_UNSPECIFIED" => Some(Self::MarginUnspecified),
            "MARGIN_CROSS" => Some(Self::MarginCross),
            "MARGIN_ISOLATED" => Some(Self::MarginIsolated),
            "MARGIN_UNKNOWN" => Some(Self::MarginUnknown),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum GatewayEventType {
    GwEventStarted = 0,
    /// todo: add other events if needed
    GwEventExchDisconnected = 1,
}
impl GatewayEventType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            GatewayEventType::GwEventStarted => "GW_EVENT_STARTED",
            GatewayEventType::GwEventExchDisconnected => "GW_EVENT_EXCH_DISCONNECTED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "GW_EVENT_STARTED" => Some(Self::GwEventStarted),
            "GW_EVENT_EXCH_DISCONNECTED" => Some(Self::GwEventExchDisconnected),
            _ => None,
        }
    }
}
// @@protoc_insertion_point(module)
