// @generated
// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OmsRouteEntry {
    #[prost(int64, tag = "1")]
    pub account_id: i64,
    #[prost(string, tag = "2")]
    pub exch_account_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub gw_key: ::prost::alloc::string::String,
    #[prost(bool, tag = "4")]
    pub startup_sync: bool,
    #[prost(string, tag = "5")]
    pub desc: ::prost::alloc::string::String,
    #[prost(enumeration = "super::common::BrokerType", tag = "6")]
    pub broker_type: i32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GwConfigEntry {
    #[prost(string, tag = "1")]
    pub exch_name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub gw_key: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub rpc_endpoint: ::prost::alloc::string::String,
    #[prost(string, tag = "15")]
    pub extra_rpc_endpoint: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub report_endpoint: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub balance_endpoint: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub gw_system_endpoint: ::prost::alloc::string::String,
    #[prost(bool, tag = "7")]
    pub support_order_replace: bool,
    #[prost(bool, tag = "8")]
    pub support_order_query: bool,
    #[prost(bool, tag = "9")]
    pub support_position_query: bool,
    #[prost(bool, tag = "10")]
    pub support_batch_order: bool,
    #[prost(bool, tag = "11")]
    pub support_batch_cancel: bool,
    #[prost(bool, tag = "14")]
    pub support_trade_history_query: bool,
    #[prost(bool, tag = "16")]
    pub support_fee_query: bool,
    #[prost(bool, tag = "12")]
    pub calc_balance_needed: bool,
    #[prost(string, repeated, tag = "13")]
    pub cancel_required_fields: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(enumeration = "super::common::BrokerType", tag = "17")]
    pub broker_type: i32,
    #[prost(enumeration = "super::common::AccountType", tag = "18")]
    pub account_type: i32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OmsConfigEntry {
    #[prost(string, tag = "1")]
    pub oms_id: ::prost::alloc::string::String,
    #[prost(int64, repeated, tag = "2")]
    pub managed_account_ids: ::prost::alloc::vec::Vec<i64>,
    #[prost(string, tag = "4")]
    pub namespace: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub desc: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AccountTradingConfig {
    #[prost(int64, tag = "1")]
    pub account_id: i64,
    #[prost(string, tag = "2")]
    pub oms_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "3")]
    pub account_route: ::core::option::Option<OmsRouteEntry>,
    #[prost(message, optional, tag = "4")]
    pub gw_config: ::core::option::Option<GwConfigEntry>,
    #[prost(message, repeated, tag = "5")]
    pub supported_instruments: ::prost::alloc::vec::Vec<super::common::InstrumentRefData>,
}
// @@protoc_insertion_point(module)
