// @generated
// This file is @generated by prost-build.
// @dataclass
// class OMSQueryAccountRequest(betterproto.Message):
//     account_id: int = betterproto.int64_field(1)
//     query_gw: bool = betterproto.bool_field(2)
//     instruments: List\[str\] = betterproto.string_field(3)

#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OmsQueryAccountRequest {
    #[prost(int64, tag = "1")]
    pub account_id: i64,
    #[prost(bool, tag = "2")]
    pub query_gw: bool,
    #[prost(string, repeated, tag = "3")]
    pub instruments: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
// @dataclass
// class ODSQueryAccountSummaryRequest(betterproto.Message):
//     account_id: int = betterproto.int64_field(1)

#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct OdsQueryAccountSummaryRequest {
    #[prost(int64, tag = "1")]
    pub account_id: i64,
}
/// @dataclass
/// class ODSAccountSummaryResponse(betterproto.Message):
///     account_id: int = betterproto.int64_field(1)
///     account_summary: exch_gw.AccountSummaryEntry = betterproto.message_field(2)
///     timestamp: int = betterproto.int64_field(3)
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OdsAccountSummaryResponse {
    #[prost(int64, tag = "1")]
    pub account_id: i64,
    #[prost(message, optional, tag = "2")]
    pub account_summary: ::core::option::Option<super::exch_gw::AccountSummaryEntry>,
    #[prost(int64, tag = "3")]
    pub timestamp: i64,
}
/// @dataclass
/// class ODSQueryAccountSettingRequest(betterproto.Message):
///     account_id: int = betterproto.int64_field(1)
///     instrument_id: str = betterproto.string_field(2)
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OdsQueryAccountSettingRequest {
    #[prost(int64, tag = "1")]
    pub account_id: i64,
    #[prost(string, tag = "2")]
    pub instrument_id: ::prost::alloc::string::String,
}
/// @dataclass
/// class ODSAccountSettingResponse(betterproto.Message):
///     account_id: int = betterproto.int64_field(1)
///     account_setting_entry: exch_gw.AccountSettingEntry = betterproto.message_field(2)
///     timestamp: int = betterproto.int64_field(3)
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OdsAccountSettingResponse {
    #[prost(int64, tag = "1")]
    pub account_id: i64,
    #[prost(message, optional, tag = "2")]
    pub account_setting_entry: ::core::option::Option<super::exch_gw::AccountSettingEntry>,
    #[prost(int64, tag = "3")]
    pub timestamp: i64,
}
/// @dataclass
/// class ODSUpdateAccountSettingRequest(betterproto.Message):
///     account_id: int = betterproto.int64_field(1)
///     account_setting_entry: exch_gw.AccountSettingEntry = betterproto.message_field(2)
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OdsUpdateAccountSettingRequest {
    #[prost(int64, tag = "1")]
    pub account_id: i64,
    #[prost(message, optional, tag = "2")]
    pub account_setting_entry: ::core::option::Option<super::exch_gw::AccountSettingEntry>,
}
/// @dataclass
/// class ODSUpdateAccountSettingResponse(betterproto.Message):
///     account_id: int = betterproto.int64_field(1)
///     margin_mode_changed: bool = betterproto.bool_field(2)
///     leverage_changed: bool = betterproto.bool_field(3)
///     err_msg: str = betterproto.string_field(4)
///     timestamp: int = betterproto.int64_field(5)
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OdsUpdateAccountSettingResponse {
    #[prost(int64, tag = "1")]
    pub account_id: i64,
    #[prost(bool, tag = "2")]
    pub margin_mode_changed: bool,
    #[prost(bool, tag = "3")]
    pub leverage_changed: bool,
    #[prost(string, tag = "4")]
    pub err_msg: ::prost::alloc::string::String,
    #[prost(int64, tag = "5")]
    pub timestamp: i64,
}
/// @dataclass
/// class OMSQueryPositionRequest(betterproto.Message):
///     account_id: int = betterproto.int64_field(1)
///     query_gw: bool = betterproto.bool_field(2)
///     instruments: List\[str\] = betterproto.string_field(3)
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OmsQueryPositionRequest {
    #[prost(int64, tag = "1")]
    pub account_id: i64,
    #[prost(bool, tag = "2")]
    pub query_gw: bool,
    #[prost(string, repeated, tag = "3")]
    pub instruments: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// @dataclass
/// class OMSPositionResponse(betterproto.Message):
///     positions: List\[oms.Position\] = betterproto.message_field(1)
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OmsPositionResponse {
    #[prost(message, repeated, tag = "1")]
    pub positions: ::prost::alloc::vec::Vec<super::oms::Position>,
}
/// @dataclass
/// class OMSQueryOpenOrderRequest(betterproto.Message):
///     account_id: int = betterproto.int64_field(1)
///     query_gw: bool = betterproto.bool_field(2)
///     instruments: List\[str\] = betterproto.string_field(3)
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OmsQueryOpenOrderRequest {
    #[prost(int64, tag = "1")]
    pub account_id: i64,
    #[prost(bool, tag = "2")]
    pub query_gw: bool,
    #[prost(string, repeated, tag = "3")]
    pub instruments: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// @dataclass
/// class OMSQueryOrderDetailRequest(betterproto.Message):
///     order_refs: List\[str\] = betterproto.string_field(1)
///     query_gw: bool = betterproto.bool_field(2)
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OmsQueryOrderDetailRequest {
    #[prost(string, repeated, tag = "1")]
    pub order_refs: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(bool, tag = "2")]
    pub query_gw: bool,
}
/// @dataclass
/// class OMSOrderDetailResponse(betterproto.Message):
///     orders: List\[oms.Order\] = betterproto.message_field(1)
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OmsOrderDetailResponse {
    #[prost(message, repeated, tag = "1")]
    pub orders: ::prost::alloc::vec::Vec<super::oms::Order>,
}
/// @dataclass
/// class OMSQeuryTradeDetailRequest(betterproto.Message):
///     order_refs: List\[str\] = betterproto.string_field(1)
///     # todo: other criteria?
///     query_gw: bool = betterproto.bool_field(2)
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OmsQeuryTradeDetailRequest {
    #[prost(string, repeated, tag = "1")]
    pub order_refs: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(bool, tag = "2")]
    pub query_gw: bool,
}
/// @dataclass
/// class OMSTradeDetailResponse(betterproto.Message):
///     trades: List\[oms.Trade\] = betterproto.message_field(1)
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OmsTradeDetailResponse {
    #[prost(message, repeated, tag = "1")]
    pub trades: ::prost::alloc::vec::Vec<super::oms::Trade>,
}
/// @dataclass
/// class OMSQueryInstrumentRefdataRequest(betterproto.Message):
///     account_id: int = betterproto.int64_field(1)
///     instruments: List\[str\] = betterproto.string_field(2)
///     start: int = betterproto.int32_field(3)
///     limit: int = betterproto.int32_field(4)
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OmsQueryInstrumentRefdataRequest {
    #[prost(int64, tag = "1")]
    pub account_id: i64,
    #[prost(string, repeated, tag = "2")]
    pub instruments: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(int32, tag = "3")]
    pub start: i32,
    #[prost(int32, tag = "4")]
    pub limit: i32,
}
/// @dataclass
/// class OMSQueryInstrumentRefdataResponse(betterproto.Message):
///     instrument_refdata: List\[common.InstrumentRefData\] = betterproto.message_field(1)
///     prev: int = betterproto.int32_field(2)
///     next: int = betterproto.int32_field(3)
///     prev_instrument_id: str = betterproto.string_field(4)
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OmsQueryInstrumentRefdataResponse {
    #[prost(message, repeated, tag = "1")]
    pub instrument_refdata: ::prost::alloc::vec::Vec<super::common::InstrumentRefData>,
    #[prost(int32, tag = "2")]
    pub prev: i32,
    #[prost(int32, tag = "3")]
    pub next: i32,
    #[prost(string, tag = "4")]
    pub prev_instrument_id: ::prost::alloc::string::String,
}
/// @dataclass
/// class OMSQueryInstrumentRequest(betterproto.Message):
///     account_id: int = betterproto.int64_field(1)
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct OmsQueryInstrumentRequest {
    #[prost(int64, tag = "1")]
    pub account_id: i64,
}
/// @dataclass
/// class OMSQueryInstrumentResponse(betterproto.Message):
///     instrument_ids: List\[str\] = betterproto.string_field(1)
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OmsQueryInstrumentResponse {
    #[prost(string, repeated, tag = "1")]
    pub instrument_ids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// @dataclass
/// class OMSQueryAccountTradingConfigRequest(betterproto.Message):
///     account_ids: List\[int\] = betterproto.int64_field(1)
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OmsQueryAccountTradingConfigRequest {
    #[prost(int64, repeated, tag = "1")]
    pub account_ids: ::prost::alloc::vec::Vec<i64>,
}
/// @dataclass
/// class OMSQueryAccountTradingConfigResponse(betterproto.Message):
///     account_trading_configs: List\[ods.AccountTradingConfig\] = betterproto.message_field(
///         1
///     )
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OmsQueryAccountTradingConfigResponse {
    #[prost(message, repeated, tag = "1")]
    pub account_trading_configs: ::prost::alloc::vec::Vec<super::ods::AccountTradingConfig>,
}
/// @dataclass
/// class OMSQueryOmsConfigRequest(betterproto.Message):
///     oms_id: str = betterproto.string_field(1)
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OmsQueryOmsConfigRequest {
    #[prost(string, tag = "1")]
    pub oms_id: ::prost::alloc::string::String,
}
/// @dataclass
/// class OMSQueryOmsConfigResponse(betterproto.Message):
///     oms_config: ods.OMSConfigEntry = betterproto.message_field(1)
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OmsQueryOmsConfigResponse {
    #[prost(message, optional, tag = "1")]
    pub oms_config: ::core::option::Option<super::ods::OmsConfigEntry>,
}
/// @dataclass
/// class OMSQueryClientConfigRequest(betterproto.Message):
///     trading_account_ids: List\[int\] = betterproto.int64_field(1)
///     order_subscribed_account_ids: List\[int\] = betterproto.int64_field(2)
///     position_subscribed_account_ids: List\[int\] = betterproto.int64_field(3)
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OmsQueryClientConfigRequest {
    #[prost(int64, repeated, tag = "1")]
    pub trading_account_ids: ::prost::alloc::vec::Vec<i64>,
    #[prost(int64, repeated, tag = "2")]
    pub order_subscribed_account_ids: ::prost::alloc::vec::Vec<i64>,
    #[prost(int64, repeated, tag = "3")]
    pub position_subscribed_account_ids: ::prost::alloc::vec::Vec<i64>,
}
/// @dataclass
/// class OMSQueryClientConfigResponse(betterproto.Message):
///     oms_service_endpoints: Dict\[int, str\] = betterproto.map_field(
///         1, betterproto.TYPE_INT64, betterproto.TYPE_STRING
///     )
///     oms_orderupdates_endpoints: List\[str\] = betterproto.string_field(2)
///     oms_balanceupdates_endpoints: List\[str\] = betterproto.string_field(3)
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OmsQueryClientConfigResponse {
    #[prost(map = "int64, string", tag = "1")]
    pub oms_service_endpoints: ::std::collections::HashMap<i64, ::prost::alloc::string::String>,
    #[prost(string, repeated, tag = "2")]
    pub oms_orderupdates_endpoints: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, repeated, tag = "3")]
    pub oms_balanceupdates_endpoints: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// @dataclass
/// class ODSRtmdQueryRequest(betterproto.Message):
///     instrument_id: str = betterproto.string_field(1)
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OdsRtmdQueryRequest {
    #[prost(string, tag = "1")]
    pub instrument_id: ::prost::alloc::string::String,
}
/// @dataclass
/// class ODSRtmdChannelQueryResponse(betterproto.Message):
///     channel_present: bool = betterproto.bool_field(1)
///     rtmd_channel: str = betterproto.string_field(2)
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OdsRtmdChannelQueryResponse {
    #[prost(bool, tag = "1")]
    pub channel_present: bool,
    #[prost(string, tag = "2")]
    pub rtmd_channel: ::prost::alloc::string::String,
}
/// @dataclass
/// class ODSRtmdDataQueryResponse(betterproto.Message):
///     data_present: bool = betterproto.bool_field(1)
///     rtmd_orderbook_bytes: bytes = betterproto.bytes_field(3)
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OdsRtmdDataQueryResponse {
    #[prost(bool, tag = "1")]
    pub data_present: bool,
    #[prost(bytes = "vec", tag = "3")]
    pub rtmd_orderbook_bytes: ::prost::alloc::vec::Vec<u8>,
}
/// @dataclass
/// class ODSRtmdSubQueryRequest(betterproto.Message):
///     exch_name: str = betterproto.string_field(1)
///     rtmd_instance_id: str = betterproto.string_field(2)
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OdsRtmdSubQueryRequest {
    #[prost(string, tag = "1")]
    pub exch_name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub rtmd_instance_id: ::prost::alloc::string::String,
}
// @@protoc_insertion_point(module)
