# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from zk.gateway.v1 import gateway_simulator_admin_pb2 as zk_dot_gateway_dot_v1_dot_gateway__simulator__admin__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in zk/gateway/v1/gateway_simulator_admin_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GatewaySimulatorAdminServiceStub(object):
    """GatewaySimulatorAdminService — test-harness controls for the simulator venue adapter.
    This service is NOT part of the production GatewayService contract.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ForceMatch = channel.unary_unary(
                '/zk.gateway.v1.GatewaySimulatorAdminService/ForceMatch',
                request_serializer=zk_dot_gateway_dot_v1_dot_gateway__simulator__admin__pb2.ForceMatchRequest.SerializeToString,
                response_deserializer=zk_dot_gateway_dot_v1_dot_gateway__simulator__admin__pb2.ForceMatchResponse.FromString,
                _registered_method=True)
        self.InjectError = channel.unary_unary(
                '/zk.gateway.v1.GatewaySimulatorAdminService/InjectError',
                request_serializer=zk_dot_gateway_dot_v1_dot_gateway__simulator__admin__pb2.InjectErrorRequest.SerializeToString,
                response_deserializer=zk_dot_gateway_dot_v1_dot_gateway__simulator__admin__pb2.InjectErrorResponse.FromString,
                _registered_method=True)
        self.ListInjectedErrors = channel.unary_unary(
                '/zk.gateway.v1.GatewaySimulatorAdminService/ListInjectedErrors',
                request_serializer=zk_dot_gateway_dot_v1_dot_gateway__simulator__admin__pb2.ListInjectedErrorsRequest.SerializeToString,
                response_deserializer=zk_dot_gateway_dot_v1_dot_gateway__simulator__admin__pb2.ListInjectedErrorsResponse.FromString,
                _registered_method=True)
        self.ClearInjectedError = channel.unary_unary(
                '/zk.gateway.v1.GatewaySimulatorAdminService/ClearInjectedError',
                request_serializer=zk_dot_gateway_dot_v1_dot_gateway__simulator__admin__pb2.ClearInjectedErrorRequest.SerializeToString,
                response_deserializer=zk_dot_gateway_dot_v1_dot_gateway__simulator__admin__pb2.ClearInjectedErrorResponse.FromString,
                _registered_method=True)
        self.ResetSimulator = channel.unary_unary(
                '/zk.gateway.v1.GatewaySimulatorAdminService/ResetSimulator',
                request_serializer=zk_dot_gateway_dot_v1_dot_gateway__simulator__admin__pb2.ResetSimulatorRequest.SerializeToString,
                response_deserializer=zk_dot_gateway_dot_v1_dot_gateway__simulator__admin__pb2.ResetSimulatorResponse.FromString,
                _registered_method=True)
        self.SetAccountState = channel.unary_unary(
                '/zk.gateway.v1.GatewaySimulatorAdminService/SetAccountState',
                request_serializer=zk_dot_gateway_dot_v1_dot_gateway__simulator__admin__pb2.SetAccountStateRequest.SerializeToString,
                response_deserializer=zk_dot_gateway_dot_v1_dot_gateway__simulator__admin__pb2.SetAccountStateResponse.FromString,
                _registered_method=True)
        self.SubmitSyntheticTick = channel.unary_unary(
                '/zk.gateway.v1.GatewaySimulatorAdminService/SubmitSyntheticTick',
                request_serializer=zk_dot_gateway_dot_v1_dot_gateway__simulator__admin__pb2.SubmitSyntheticTickRequest.SerializeToString,
                response_deserializer=zk_dot_gateway_dot_v1_dot_gateway__simulator__admin__pb2.SubmitSyntheticTickResponse.FromString,
                _registered_method=True)
        self.ListOpenOrders = channel.unary_unary(
                '/zk.gateway.v1.GatewaySimulatorAdminService/ListOpenOrders',
                request_serializer=zk_dot_gateway_dot_v1_dot_gateway__simulator__admin__pb2.ListOpenOrdersRequest.SerializeToString,
                response_deserializer=zk_dot_gateway_dot_v1_dot_gateway__simulator__admin__pb2.ListOpenOrdersResponse.FromString,
                _registered_method=True)
        self.PauseMatching = channel.unary_unary(
                '/zk.gateway.v1.GatewaySimulatorAdminService/PauseMatching',
                request_serializer=zk_dot_gateway_dot_v1_dot_gateway__simulator__admin__pb2.PauseMatchingRequest.SerializeToString,
                response_deserializer=zk_dot_gateway_dot_v1_dot_gateway__simulator__admin__pb2.MatchingStateResponse.FromString,
                _registered_method=True)
        self.ResumeMatching = channel.unary_unary(
                '/zk.gateway.v1.GatewaySimulatorAdminService/ResumeMatching',
                request_serializer=zk_dot_gateway_dot_v1_dot_gateway__simulator__admin__pb2.ResumeMatchingRequest.SerializeToString,
                response_deserializer=zk_dot_gateway_dot_v1_dot_gateway__simulator__admin__pb2.MatchingStateResponse.FromString,
                _registered_method=True)
        self.SetMatchPolicy = channel.unary_unary(
                '/zk.gateway.v1.GatewaySimulatorAdminService/SetMatchPolicy',
                request_serializer=zk_dot_gateway_dot_v1_dot_gateway__simulator__admin__pb2.SetMatchPolicyRequest.SerializeToString,
                response_deserializer=zk_dot_gateway_dot_v1_dot_gateway__simulator__admin__pb2.SetMatchPolicyResponse.FromString,
                _registered_method=True)
        self.AdvanceTime = channel.unary_unary(
                '/zk.gateway.v1.GatewaySimulatorAdminService/AdvanceTime',
                request_serializer=zk_dot_gateway_dot_v1_dot_gateway__simulator__admin__pb2.AdvanceTimeRequest.SerializeToString,
                response_deserializer=zk_dot_gateway_dot_v1_dot_gateway__simulator__admin__pb2.AdvanceTimeResponse.FromString,
                _registered_method=True)
        self.GetSimulatorState = channel.unary_unary(
                '/zk.gateway.v1.GatewaySimulatorAdminService/GetSimulatorState',
                request_serializer=zk_dot_gateway_dot_v1_dot_gateway__simulator__admin__pb2.GetSimulatorStateRequest.SerializeToString,
                response_deserializer=zk_dot_gateway_dot_v1_dot_gateway__simulator__admin__pb2.GetSimulatorStateResponse.FromString,
                _registered_method=True)


class GatewaySimulatorAdminServiceServicer(object):
    """GatewaySimulatorAdminService — test-harness controls for the simulator venue adapter.
    This service is NOT part of the production GatewayService contract.
    """

    def ForceMatch(self, request, context):
        """Phase 1: minimal operator surface
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InjectError(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListInjectedErrors(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClearInjectedError(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResetSimulator(self, request, context):
        """Phase 2: reset and diagnostics
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetAccountState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitSyntheticTick(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListOpenOrders(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PauseMatching(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResumeMatching(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetMatchPolicy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AdvanceTime(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSimulatorState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GatewaySimulatorAdminServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ForceMatch': grpc.unary_unary_rpc_method_handler(
                    servicer.ForceMatch,
                    request_deserializer=zk_dot_gateway_dot_v1_dot_gateway__simulator__admin__pb2.ForceMatchRequest.FromString,
                    response_serializer=zk_dot_gateway_dot_v1_dot_gateway__simulator__admin__pb2.ForceMatchResponse.SerializeToString,
            ),
            'InjectError': grpc.unary_unary_rpc_method_handler(
                    servicer.InjectError,
                    request_deserializer=zk_dot_gateway_dot_v1_dot_gateway__simulator__admin__pb2.InjectErrorRequest.FromString,
                    response_serializer=zk_dot_gateway_dot_v1_dot_gateway__simulator__admin__pb2.InjectErrorResponse.SerializeToString,
            ),
            'ListInjectedErrors': grpc.unary_unary_rpc_method_handler(
                    servicer.ListInjectedErrors,
                    request_deserializer=zk_dot_gateway_dot_v1_dot_gateway__simulator__admin__pb2.ListInjectedErrorsRequest.FromString,
                    response_serializer=zk_dot_gateway_dot_v1_dot_gateway__simulator__admin__pb2.ListInjectedErrorsResponse.SerializeToString,
            ),
            'ClearInjectedError': grpc.unary_unary_rpc_method_handler(
                    servicer.ClearInjectedError,
                    request_deserializer=zk_dot_gateway_dot_v1_dot_gateway__simulator__admin__pb2.ClearInjectedErrorRequest.FromString,
                    response_serializer=zk_dot_gateway_dot_v1_dot_gateway__simulator__admin__pb2.ClearInjectedErrorResponse.SerializeToString,
            ),
            'ResetSimulator': grpc.unary_unary_rpc_method_handler(
                    servicer.ResetSimulator,
                    request_deserializer=zk_dot_gateway_dot_v1_dot_gateway__simulator__admin__pb2.ResetSimulatorRequest.FromString,
                    response_serializer=zk_dot_gateway_dot_v1_dot_gateway__simulator__admin__pb2.ResetSimulatorResponse.SerializeToString,
            ),
            'SetAccountState': grpc.unary_unary_rpc_method_handler(
                    servicer.SetAccountState,
                    request_deserializer=zk_dot_gateway_dot_v1_dot_gateway__simulator__admin__pb2.SetAccountStateRequest.FromString,
                    response_serializer=zk_dot_gateway_dot_v1_dot_gateway__simulator__admin__pb2.SetAccountStateResponse.SerializeToString,
            ),
            'SubmitSyntheticTick': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitSyntheticTick,
                    request_deserializer=zk_dot_gateway_dot_v1_dot_gateway__simulator__admin__pb2.SubmitSyntheticTickRequest.FromString,
                    response_serializer=zk_dot_gateway_dot_v1_dot_gateway__simulator__admin__pb2.SubmitSyntheticTickResponse.SerializeToString,
            ),
            'ListOpenOrders': grpc.unary_unary_rpc_method_handler(
                    servicer.ListOpenOrders,
                    request_deserializer=zk_dot_gateway_dot_v1_dot_gateway__simulator__admin__pb2.ListOpenOrdersRequest.FromString,
                    response_serializer=zk_dot_gateway_dot_v1_dot_gateway__simulator__admin__pb2.ListOpenOrdersResponse.SerializeToString,
            ),
            'PauseMatching': grpc.unary_unary_rpc_method_handler(
                    servicer.PauseMatching,
                    request_deserializer=zk_dot_gateway_dot_v1_dot_gateway__simulator__admin__pb2.PauseMatchingRequest.FromString,
                    response_serializer=zk_dot_gateway_dot_v1_dot_gateway__simulator__admin__pb2.MatchingStateResponse.SerializeToString,
            ),
            'ResumeMatching': grpc.unary_unary_rpc_method_handler(
                    servicer.ResumeMatching,
                    request_deserializer=zk_dot_gateway_dot_v1_dot_gateway__simulator__admin__pb2.ResumeMatchingRequest.FromString,
                    response_serializer=zk_dot_gateway_dot_v1_dot_gateway__simulator__admin__pb2.MatchingStateResponse.SerializeToString,
            ),
            'SetMatchPolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.SetMatchPolicy,
                    request_deserializer=zk_dot_gateway_dot_v1_dot_gateway__simulator__admin__pb2.SetMatchPolicyRequest.FromString,
                    response_serializer=zk_dot_gateway_dot_v1_dot_gateway__simulator__admin__pb2.SetMatchPolicyResponse.SerializeToString,
            ),
            'AdvanceTime': grpc.unary_unary_rpc_method_handler(
                    servicer.AdvanceTime,
                    request_deserializer=zk_dot_gateway_dot_v1_dot_gateway__simulator__admin__pb2.AdvanceTimeRequest.FromString,
                    response_serializer=zk_dot_gateway_dot_v1_dot_gateway__simulator__admin__pb2.AdvanceTimeResponse.SerializeToString,
            ),
            'GetSimulatorState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSimulatorState,
                    request_deserializer=zk_dot_gateway_dot_v1_dot_gateway__simulator__admin__pb2.GetSimulatorStateRequest.FromString,
                    response_serializer=zk_dot_gateway_dot_v1_dot_gateway__simulator__admin__pb2.GetSimulatorStateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'zk.gateway.v1.GatewaySimulatorAdminService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('zk.gateway.v1.GatewaySimulatorAdminService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GatewaySimulatorAdminService(object):
    """GatewaySimulatorAdminService — test-harness controls for the simulator venue adapter.
    This service is NOT part of the production GatewayService contract.
    """

    @staticmethod
    def ForceMatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/zk.gateway.v1.GatewaySimulatorAdminService/ForceMatch',
            zk_dot_gateway_dot_v1_dot_gateway__simulator__admin__pb2.ForceMatchRequest.SerializeToString,
            zk_dot_gateway_dot_v1_dot_gateway__simulator__admin__pb2.ForceMatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InjectError(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/zk.gateway.v1.GatewaySimulatorAdminService/InjectError',
            zk_dot_gateway_dot_v1_dot_gateway__simulator__admin__pb2.InjectErrorRequest.SerializeToString,
            zk_dot_gateway_dot_v1_dot_gateway__simulator__admin__pb2.InjectErrorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListInjectedErrors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/zk.gateway.v1.GatewaySimulatorAdminService/ListInjectedErrors',
            zk_dot_gateway_dot_v1_dot_gateway__simulator__admin__pb2.ListInjectedErrorsRequest.SerializeToString,
            zk_dot_gateway_dot_v1_dot_gateway__simulator__admin__pb2.ListInjectedErrorsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClearInjectedError(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/zk.gateway.v1.GatewaySimulatorAdminService/ClearInjectedError',
            zk_dot_gateway_dot_v1_dot_gateway__simulator__admin__pb2.ClearInjectedErrorRequest.SerializeToString,
            zk_dot_gateway_dot_v1_dot_gateway__simulator__admin__pb2.ClearInjectedErrorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResetSimulator(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/zk.gateway.v1.GatewaySimulatorAdminService/ResetSimulator',
            zk_dot_gateway_dot_v1_dot_gateway__simulator__admin__pb2.ResetSimulatorRequest.SerializeToString,
            zk_dot_gateway_dot_v1_dot_gateway__simulator__admin__pb2.ResetSimulatorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetAccountState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/zk.gateway.v1.GatewaySimulatorAdminService/SetAccountState',
            zk_dot_gateway_dot_v1_dot_gateway__simulator__admin__pb2.SetAccountStateRequest.SerializeToString,
            zk_dot_gateway_dot_v1_dot_gateway__simulator__admin__pb2.SetAccountStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitSyntheticTick(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/zk.gateway.v1.GatewaySimulatorAdminService/SubmitSyntheticTick',
            zk_dot_gateway_dot_v1_dot_gateway__simulator__admin__pb2.SubmitSyntheticTickRequest.SerializeToString,
            zk_dot_gateway_dot_v1_dot_gateway__simulator__admin__pb2.SubmitSyntheticTickResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListOpenOrders(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/zk.gateway.v1.GatewaySimulatorAdminService/ListOpenOrders',
            zk_dot_gateway_dot_v1_dot_gateway__simulator__admin__pb2.ListOpenOrdersRequest.SerializeToString,
            zk_dot_gateway_dot_v1_dot_gateway__simulator__admin__pb2.ListOpenOrdersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PauseMatching(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/zk.gateway.v1.GatewaySimulatorAdminService/PauseMatching',
            zk_dot_gateway_dot_v1_dot_gateway__simulator__admin__pb2.PauseMatchingRequest.SerializeToString,
            zk_dot_gateway_dot_v1_dot_gateway__simulator__admin__pb2.MatchingStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResumeMatching(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/zk.gateway.v1.GatewaySimulatorAdminService/ResumeMatching',
            zk_dot_gateway_dot_v1_dot_gateway__simulator__admin__pb2.ResumeMatchingRequest.SerializeToString,
            zk_dot_gateway_dot_v1_dot_gateway__simulator__admin__pb2.MatchingStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetMatchPolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/zk.gateway.v1.GatewaySimulatorAdminService/SetMatchPolicy',
            zk_dot_gateway_dot_v1_dot_gateway__simulator__admin__pb2.SetMatchPolicyRequest.SerializeToString,
            zk_dot_gateway_dot_v1_dot_gateway__simulator__admin__pb2.SetMatchPolicyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AdvanceTime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/zk.gateway.v1.GatewaySimulatorAdminService/AdvanceTime',
            zk_dot_gateway_dot_v1_dot_gateway__simulator__admin__pb2.AdvanceTimeRequest.SerializeToString,
            zk_dot_gateway_dot_v1_dot_gateway__simulator__admin__pb2.AdvanceTimeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSimulatorState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/zk.gateway.v1.GatewaySimulatorAdminService/GetSimulatorState',
            zk_dot_gateway_dot_v1_dot_gateway__simulator__admin__pb2.GetSimulatorStateRequest.SerializeToString,
            zk_dot_gateway_dot_v1_dot_gateway__simulator__admin__pb2.GetSimulatorStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
