// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: zk/oms/v1/oms_service.proto
// Protobuf C++ Version: 7.34.0

#include "zk/oms/v1/oms_service.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/internal_visibility.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace zk {
namespace oms {
namespace v1 {
}  // namespace v1
}  // namespace oms
}  // namespace zk
static constexpr const ::_pb::EnumDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_enum_descriptors_zk_2foms_2fv1_2foms_5fservice_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_zk_2foms_2fv1_2foms_5fservice_2eproto = nullptr;
const ::uint32_t TableStruct_zk_2foms_2fv1_2foms_5fservice_2eproto::offsets[1] = {};
static constexpr ::_pbi::MigrationSchema* PROTOBUF_NULLABLE schemas = nullptr;
static constexpr ::_pb::Message* PROTOBUF_NONNULL const* PROTOBUF_NULLABLE
    file_default_instances = nullptr;
const char descriptor_table_protodef_zk_2foms_2fv1_2foms_5fservice_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\033zk/oms/v1/oms_service.proto\022\tzk.oms.v1"
    "\032\023zk/oms/v1/oms.proto\032\031zk/common/v1/comm"
    "on.proto2\263\t\n\nOMSService\022B\n\nPlaceOrder\022\034."
    "zk.oms.v1.PlaceOrderRequest\032\026.zk.oms.v1."
    "OMSResponse\022N\n\020BatchPlaceOrders\022\".zk.oms"
    ".v1.BatchPlaceOrdersRequest\032\026.zk.oms.v1."
    "OMSResponse\022D\n\013CancelOrder\022\035.zk.oms.v1.C"
    "ancelOrderRequest\032\026.zk.oms.v1.OMSRespons"
    "e\022P\n\021BatchCancelOrders\022#.zk.oms.v1.Batch"
    "CancelOrdersRequest\032\026.zk.oms.v1.OMSRespo"
    "nse\022G\n\020ExecuteAlgoOrder\022\033.zk.oms.v1.Algo"
    "OrderRequest\032\026.zk.oms.v1.OMSResponse\022L\n\017"
    "CancelAlgoOrder\022!.zk.oms.v1.CancelAlgoOr"
    "derRequest\032\026.zk.oms.v1.OMSResponse\0228\n\005Pa"
    "nic\022\027.zk.oms.v1.PanicRequest\032\026.zk.oms.v1"
    ".OMSResponse\022@\n\tDontPanic\022\033.zk.oms.v1.Do"
    "ntPanicRequest\032\026.zk.oms.v1.OMSResponse\022Q"
    "\n\023QueryAccountBalance\022\036.zk.oms.v1.QueryA"
    "ccountRequest\032\032.zk.oms.v1.AccountRespons"
    "e\022M\n\rQueryPosition\022\037.zk.oms.v1.QueryPosi"
    "tionRequest\032\033.zk.oms.v1.PositionResponse"
    "\022S\n\017QueryOpenOrders\022 .zk.oms.v1.QueryOpe"
    "nOrderRequest\032\036.zk.oms.v1.OrderDetailRes"
    "ponse\022W\n\021QueryOrderDetails\022\".zk.oms.v1.Q"
    "ueryOrderDetailRequest\032\036.zk.oms.v1.Order"
    "DetailResponse\022W\n\021QueryTradeDetails\022\".zk"
    ".oms.v1.QueryTradeDetailRequest\032\036.zk.oms"
    ".v1.TradeDetailResponse\022m\n\026QueryInstrume"
    "ntRefdata\022(.zk.oms.v1.QueryInstrumentRef"
    "dataRequest\032).zk.oms.v1.QueryInstrumentR"
    "efdataResponse\022N\n\013HealthCheck\022\032.zk.commo"
    "n.v1.DummyRequest\032#.zk.common.v1.Service"
    "HealthResponseBf\n\rcom.zk.oms.v1B\017OmsServ"
    "iceProtoP\001\242\002\003ZOX\252\002\tZk.Oms.V1\312\002\tZk\\Oms\\V1"
    "\342\002\025Zk\\Oms\\V1\\GPBMetadata\352\002\013Zk::Oms::V1b\006"
    "proto3"
};
static const ::_pbi::DescriptorTable* PROTOBUF_NONNULL const
    descriptor_table_zk_2foms_2fv1_2foms_5fservice_2eproto_deps[2] = {
        &::descriptor_table_zk_2fcommon_2fv1_2fcommon_2eproto,
        &::descriptor_table_zk_2foms_2fv1_2foms_2eproto,
};
static ::absl::once_flag descriptor_table_zk_2foms_2fv1_2foms_5fservice_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_zk_2foms_2fv1_2foms_5fservice_2eproto = {
    false,
    false,
    1406,
    descriptor_table_protodef_zk_2foms_2fv1_2foms_5fservice_2eproto,
    "zk/oms/v1/oms_service.proto",
    &descriptor_table_zk_2foms_2fv1_2foms_5fservice_2eproto_once,
    descriptor_table_zk_2foms_2fv1_2foms_5fservice_2eproto_deps,
    2,
    0,
    schemas,
    file_default_instances,
    TableStruct_zk_2foms_2fv1_2foms_5fservice_2eproto::offsets,
    file_level_enum_descriptors_zk_2foms_2fv1_2foms_5fservice_2eproto,
    file_level_service_descriptors_zk_2foms_2fv1_2foms_5fservice_2eproto,
};
namespace zk {
namespace oms {
namespace v1 {
// @@protoc_insertion_point(namespace_scope)
}  // namespace v1
}  // namespace oms
}  // namespace zk
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_zk_2foms_2fv1_2foms_5fservice_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
