# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: zk/ods/v1/ods.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'zk/ods/v1/ods.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from zk.common.v1 import common_pb2 as zk_dot_common_dot_v1_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13zk/ods/v1/ods.proto\x12\tzk.ods.v1\x1a\x19zk/common/v1/common.proto\"\x9f\x01\n\rOMSRouteEntry\x12\x12\n\naccount_id\x18\x01 \x01(\x03\x12\x17\n\x0f\x65xch_account_id\x18\x02 \x01(\t\x12\x0e\n\x06gw_key\x18\x03 \x01(\t\x12\x14\n\x0cstartup_sync\x18\x04 \x01(\x08\x12\x0c\n\x04\x64\x65sc\x18\x05 \x01(\t\x12-\n\x0b\x62roker_type\x18\x06 \x01(\x0e\x32\x18.zk.common.v1.BrokerType\"\xa7\x04\n\rGWConfigEntry\x12\x11\n\texch_name\x18\x01 \x01(\t\x12\x0e\n\x06gw_key\x18\x02 \x01(\t\x12\x14\n\x0crpc_endpoint\x18\x03 \x01(\t\x12\x1a\n\x12\x65xtra_rpc_endpoint\x18\x0f \x01(\t\x12\x17\n\x0freport_endpoint\x18\x04 \x01(\t\x12\x18\n\x10\x62\x61lance_endpoint\x18\x05 \x01(\t\x12\x1a\n\x12gw_system_endpoint\x18\x06 \x01(\t\x12\x1d\n\x15support_order_replace\x18\x07 \x01(\x08\x12\x1b\n\x13support_order_query\x18\x08 \x01(\x08\x12\x1e\n\x16support_position_query\x18\t \x01(\x08\x12\x1b\n\x13support_batch_order\x18\n \x01(\x08\x12\x1c\n\x14support_batch_cancel\x18\x0b \x01(\x08\x12#\n\x1bsupport_trade_history_query\x18\x0e \x01(\x08\x12\x19\n\x11support_fee_query\x18\x10 \x01(\x08\x12\x1b\n\x13\x63\x61lc_balance_needed\x18\x0c \x01(\x08\x12\x1e\n\x16\x63\x61ncel_required_fields\x18\r \x03(\t\x12-\n\x0b\x62roker_type\x18\x11 \x01(\x0e\x32\x18.zk.common.v1.BrokerType\x12/\n\x0c\x61\x63\x63ount_type\x18\x12 \x01(\x0e\x32\x19.zk.common.v1.AccountType\"^\n\x0eOMSConfigEntry\x12\x0e\n\x06oms_id\x18\x01 \x01(\t\x12\x1b\n\x13managed_account_ids\x18\x02 \x03(\x03\x12\x11\n\tnamespace\x18\x04 \x01(\t\x12\x0c\n\x04\x64\x65sc\x18\x05 \x01(\t\"\xd8\x01\n\x14\x41\x63\x63ountTradingConfig\x12\x12\n\naccount_id\x18\x01 \x01(\x03\x12\x0e\n\x06oms_id\x18\x02 \x01(\t\x12/\n\raccount_route\x18\x03 \x01(\x0b\x32\x18.zk.ods.v1.OMSRouteEntry\x12+\n\tgw_config\x18\x04 \x01(\x0b\x32\x18.zk.ods.v1.GWConfigEntry\x12>\n\x15supported_instruments\x18\x05 \x03(\x0b\x32\x1f.zk.common.v1.InstrumentRefDatab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'zk.ods.v1.ods_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_OMSROUTEENTRY']._serialized_start=62
  _globals['_OMSROUTEENTRY']._serialized_end=221
  _globals['_GWCONFIGENTRY']._serialized_start=224
  _globals['_GWCONFIGENTRY']._serialized_end=775
  _globals['_OMSCONFIGENTRY']._serialized_start=777
  _globals['_OMSCONFIGENTRY']._serialized_end=871
  _globals['_ACCOUNTTRADINGCONFIG']._serialized_start=874
  _globals['_ACCOUNTTRADINGCONFIG']._serialized_end=1090
# @@protoc_insertion_point(module_scope)
