// @generated
// This file is @generated by prost-build.
/// RecorderTerminalOrder carries the full terminal snapshot of an OMS order.
/// Maps to trd.order_oms. OMS fills linkage fields; recorder does enrichment
/// (strategy_id, execution_id, account name).
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RecorderTerminalOrder {
    #[prost(int64, tag="1")]
    pub order_id: i64,
    #[prost(int64, tag="2")]
    pub account_id: i64,
    #[prost(string, tag="3")]
    pub oms_id: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub gw_key: ::prost::alloc::string::String,
    /// order source binding (e.g. strategy source_id)
    #[prost(string, tag="5")]
    pub source_id: ::prost::alloc::string::String,
    #[prost(string, tag="6")]
    pub instrument_code: ::prost::alloc::string::String,
    /// exchange-specific instrument identifier
    #[prost(string, tag="7")]
    pub instrument_exch: ::prost::alloc::string::String,
    #[prost(enumeration="super::super::common::v1::BuySellType", tag="8")]
    pub side: i32,
    #[prost(enumeration="super::super::common::v1::OpenCloseType", tag="9")]
    pub open_close: i32,
    #[prost(enumeration="super::super::common::v1::BasicOrderType", tag="10")]
    pub order_type: i32,
    #[prost(enumeration="super::super::oms::v1::OrderStatus", tag="11")]
    pub order_status: i32,
    #[prost(double, tag="12")]
    pub price: f64,
    #[prost(double, tag="13")]
    pub qty: f64,
    #[prost(double, tag="14")]
    pub filled_qty: f64,
    #[prost(double, tag="15")]
    pub filled_avg_price: f64,
    #[prost(string, tag="16")]
    pub ext_order_ref: ::prost::alloc::string::String,
    #[prost(string, tag="17")]
    pub error_msg: ::prost::alloc::string::String,
    /// timestamp when order reached terminal state
    #[prost(int64, tag="18")]
    pub terminal_at_ms: i64,
    /// order creation timestamp
    #[prost(int64, tag="19")]
    pub created_at_ms: i64,
    /// all explicit fills
    #[prost(message, repeated, tag="20")]
    pub trades: ::prost::alloc::vec::Vec<super::super::oms::v1::Trade>,
    /// all OMS-inferred fills
    #[prost(message, repeated, tag="21")]
    pub inferred_trades: ::prost::alloc::vec::Vec<super::super::oms::v1::Trade>,
    /// all fees
    #[prost(message, repeated, tag="22")]
    pub fees: ::prost::alloc::vec::Vec<super::super::oms::v1::Fee>,
}
/// RecorderTradeEvent carries a single fill event for the recorder.
/// Maps to trd.trade_oms. Emitted once per explicit or inferred trade.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RecorderTradeEvent {
    #[prost(int64, tag="1")]
    pub order_id: i64,
    #[prost(int64, tag="2")]
    pub account_id: i64,
    #[prost(string, tag="3")]
    pub oms_id: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub gw_key: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub source_id: ::prost::alloc::string::String,
    #[prost(string, tag="6")]
    pub instrument_code: ::prost::alloc::string::String,
    #[prost(string, tag="7")]
    pub instrument_exch: ::prost::alloc::string::String,
    #[prost(enumeration="super::super::common::v1::BuySellType", tag="8")]
    pub side: i32,
    #[prost(enumeration="super::super::common::v1::OpenCloseType", tag="9")]
    pub open_close: i32,
    #[prost(string, tag="10")]
    pub ext_order_ref: ::prost::alloc::string::String,
    /// fill data
    #[prost(string, tag="11")]
    pub ext_trade_id: ::prost::alloc::string::String,
    #[prost(double, tag="12")]
    pub filled_qty: f64,
    #[prost(double, tag="13")]
    pub filled_price: f64,
    #[prost(int64, tag="14")]
    pub filled_ts_ms: i64,
    #[prost(enumeration="super::super::common::v1::FillType", tag="15")]
    pub fill_type: i32,
    #[prost(message, repeated, tag="16")]
    pub fees: ::prost::alloc::vec::Vec<super::super::oms::v1::Fee>,
    /// true if this was an OMS-inferred fill
    #[prost(bool, tag="17")]
    pub is_inferred: bool,
}
// @@protoc_insertion_point(module)
