// @generated
// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct QueryInstrumentByIdRequest {
    #[prost(string, tag="1")]
    pub instrument_id: ::prost::alloc::string::String,
    #[prost(enumeration="DisclosureLevel", tag="2")]
    pub level: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct QueryByVenueSymbolRequest {
    #[prost(string, tag="1")]
    pub venue: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub instrument_exch: ::prost::alloc::string::String,
    #[prost(enumeration="DisclosureLevel", tag="3")]
    pub level: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListInstrumentsRequest {
    #[prost(string, tag="1")]
    pub venue: ::prost::alloc::string::String,
    #[prost(bool, tag="2")]
    pub enabled_only: bool,
    #[prost(enumeration="DisclosureLevel", tag="3")]
    pub level: i32,
}
/// Instrument reference data with progressive disclosure.
/// BASIC (fields 1-10): canonical identity, venue mapping, primary trading params.
/// EXTENDED (fields 11-23): lifecycle, extra properties, market session context.
/// FULL (fields 24-25): provenance / operator fields.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InstrumentRefdataResponse {
    /// BASIC fields
    #[prost(string, tag="1")]
    pub instrument_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub venue: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub instrument_exch: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub instrument_type: ::prost::alloc::string::String,
    #[prost(bool, tag="5")]
    pub disabled: bool,
    #[prost(double, tag="6")]
    pub price_tick_size: f64,
    #[prost(double, tag="7")]
    pub qty_lot_size: f64,
    #[prost(string, tag="8")]
    pub base_asset: ::prost::alloc::string::String,
    #[prost(string, tag="9")]
    pub quote_asset: ::prost::alloc::string::String,
    #[prost(int64, tag="10")]
    pub updated_at_ms: i64,
    /// EXTENDED fields
    ///
    /// active | disabled | deprecated
    #[prost(string, tag="11")]
    pub lifecycle_status: ::prost::alloc::string::String,
    #[prost(string, tag="12")]
    pub settlement_asset: ::prost::alloc::string::String,
    #[prost(double, tag="13")]
    pub contract_size: f64,
    #[prost(double, tag="14")]
    pub min_notional: f64,
    #[prost(double, tag="15")]
    pub max_notional: f64,
    #[prost(double, tag="16")]
    pub min_order_qty: f64,
    #[prost(double, tag="17")]
    pub max_order_qty: f64,
    #[prost(double, tag="18")]
    pub max_mkt_order_qty: f64,
    #[prost(int32, tag="19")]
    pub price_precision: i32,
    #[prost(int32, tag="20")]
    pub qty_precision: i32,
    #[prost(map="string, string", tag="21")]
    pub extra_properties: ::std::collections::HashMap<::prost::alloc::string::String, ::prost::alloc::string::String>,
    #[prost(int64, tag="22")]
    pub first_seen_at_ms: i64,
    #[prost(int64, tag="23")]
    pub last_seen_at_ms: i64,
    /// FULL fields
    #[prost(string, tag="24")]
    pub source_name: ::prost::alloc::string::String,
    #[prost(int64, tag="25")]
    pub source_run_id: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListInstrumentsResponse {
    #[prost(message, repeated, tag="1")]
    pub instruments: ::prost::alloc::vec::Vec<InstrumentRefdataResponse>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct QueryWatermarkRequest {
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct WatermarkResponse {
    #[prost(int64, tag="1")]
    pub watermark_ms: i64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct QueryMarketStatusRequest {
    #[prost(string, tag="1")]
    pub venue: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub market: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MarketStatusResponse {
    #[prost(string, tag="1")]
    pub venue: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub market: ::prost::alloc::string::String,
    /// open | closed | halted | pre_open | special
    #[prost(string, tag="3")]
    pub session_state: ::prost::alloc::string::String,
    #[prost(int64, tag="4")]
    pub effective_at_ms: i64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct QueryMarketCalendarRequest {
    #[prost(string, tag="1")]
    pub venue: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub market: ::prost::alloc::string::String,
    /// YYYY-MM-DD
    #[prost(string, tag="3")]
    pub start_date: ::prost::alloc::string::String,
    /// YYYY-MM-DD
    #[prost(string, tag="4")]
    pub end_date: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QueryMarketCalendarResponse {
    #[prost(message, repeated, tag="1")]
    pub entries: ::prost::alloc::vec::Vec<MarketCalendarEntry>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MarketCalendarEntry {
    #[prost(string, tag="1")]
    pub venue: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub market: ::prost::alloc::string::String,
    /// YYYY-MM-DD
    #[prost(string, tag="3")]
    pub date: ::prost::alloc::string::String,
    /// open | closed | halted | pre_open | special
    #[prost(string, tag="4")]
    pub session_state: ::prost::alloc::string::String,
    #[prost(int64, tag="5")]
    pub open_time_ms: i64,
    #[prost(int64, tag="6")]
    pub close_time_ms: i64,
    #[prost(string, tag="7")]
    pub source: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TriggerVenueRefreshRequest {
    #[prost(string, tag="1")]
    pub venue: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetRefreshRunRequest {
    #[prost(int64, tag="1")]
    pub run_id: i64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RefreshRunResponse {
    #[prost(int64, tag="1")]
    pub run_id: i64,
    #[prost(string, tag="2")]
    pub venue: ::prost::alloc::string::String,
    /// running | completed | failed
    #[prost(string, tag="3")]
    pub status: ::prost::alloc::string::String,
    #[prost(int32, tag="4")]
    pub added: i32,
    #[prost(int32, tag="5")]
    pub updated: i32,
    #[prost(int32, tag="6")]
    pub disabled: i32,
    #[prost(string, tag="7")]
    pub error_detail: ::prost::alloc::string::String,
    #[prost(int64, tag="8")]
    pub started_at_ms: i64,
    #[prost(int64, tag="9")]
    pub completed_at_ms: i64,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum DisclosureLevel {
    Unspecified = 0,
    Basic = 1,
    Extended = 2,
    Full = 3,
}
impl DisclosureLevel {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "DISCLOSURE_LEVEL_UNSPECIFIED",
            Self::Basic => "BASIC",
            Self::Extended => "EXTENDED",
            Self::Full => "FULL",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "DISCLOSURE_LEVEL_UNSPECIFIED" => Some(Self::Unspecified),
            "BASIC" => Some(Self::Basic),
            "EXTENDED" => Some(Self::Extended),
            "FULL" => Some(Self::Full),
            _ => None,
        }
    }
}
// @@protoc_insertion_point(module)
