# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: zk/engine/v1/engine_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'zk/engine/v1/engine_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from zk.common.v1 import common_pb2 as zk_dot_common_dot_v1_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!zk/engine/v1/engine_service.proto\x12\x0czk.engine.v1\x1a\x19zk/common/v1/common.proto\"\x96\x01\n\x12StartEngineRequest\x12\x13\n\x0binstance_id\x18\x01 \x01(\t\x12\x13\n\x0bstrategy_id\x18\x02 \x01(\t\x12\x14\n\x0c\x65xecution_id\x18\x03 \x01(\t\x12\x13\n\x0b\x63onfig_json\x18\x04 \x01(\t\x12+\n\naudit_meta\x18\x05 \x01(\x0b\x32\x17.zk.common.v1.AuditMeta\"{\n\x11StopEngineRequest\x12\x13\n\x0binstance_id\x18\x01 \x01(\t\x12\x14\n\x0c\x65xecution_id\x18\x02 \x01(\t\x12\x0e\n\x06reason\x18\x03 \x01(\t\x12+\n\naudit_meta\x18\x04 \x01(\x0b\x32\x17.zk.common.v1.AuditMeta\"l\n\x12PauseEngineRequest\x12\x13\n\x0binstance_id\x18\x01 \x01(\t\x12\x14\n\x0c\x65xecution_id\x18\x02 \x01(\t\x12+\n\naudit_meta\x18\x03 \x01(\x0b\x32\x17.zk.common.v1.AuditMeta\"m\n\x13ResumeEngineRequest\x12\x13\n\x0binstance_id\x18\x01 \x01(\t\x12\x14\n\x0c\x65xecution_id\x18\x02 \x01(\t\x12+\n\naudit_meta\x18\x03 \x01(\x0b\x32\x17.zk.common.v1.AuditMeta\"*\n\x13\x45ngineStatusRequest\x12\x13\n\x0binstance_id\x18\x01 \x01(\t\"s\n\x14\x45ngineStatusResponse\x12\x13\n\x0binstance_id\x18\x01 \x01(\t\x12\x14\n\x0c\x65xecution_id\x18\x02 \x01(\t\x12\r\n\x05state\x18\x03 \x01(\t\x12\x0e\n\x06\x64\x65tail\x18\x04 \x01(\t\x12\x11\n\tuptime_ms\x18\x05 \x01(\x03\x32\xc7\x03\n\rEngineService\x12\x43\n\x05Start\x12 .zk.engine.v1.StartEngineRequest\x1a\x18.zk.common.v1.CommandAck\x12\x41\n\x04Stop\x12\x1f.zk.engine.v1.StopEngineRequest\x1a\x18.zk.common.v1.CommandAck\x12\x43\n\x05Pause\x12 .zk.engine.v1.PauseEngineRequest\x1a\x18.zk.common.v1.CommandAck\x12\x45\n\x06Resume\x12!.zk.engine.v1.ResumeEngineRequest\x1a\x18.zk.common.v1.CommandAck\x12R\n\tGetStatus\x12!.zk.engine.v1.EngineStatusRequest\x1a\".zk.engine.v1.EngineStatusResponse\x12N\n\x0bHealthCheck\x12\x1a.zk.common.v1.DummyRequest\x1a#.zk.common.v1.ServiceHealthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'zk.engine.v1.engine_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STARTENGINEREQUEST']._serialized_start=79
  _globals['_STARTENGINEREQUEST']._serialized_end=229
  _globals['_STOPENGINEREQUEST']._serialized_start=231
  _globals['_STOPENGINEREQUEST']._serialized_end=354
  _globals['_PAUSEENGINEREQUEST']._serialized_start=356
  _globals['_PAUSEENGINEREQUEST']._serialized_end=464
  _globals['_RESUMEENGINEREQUEST']._serialized_start=466
  _globals['_RESUMEENGINEREQUEST']._serialized_end=575
  _globals['_ENGINESTATUSREQUEST']._serialized_start=577
  _globals['_ENGINESTATUSREQUEST']._serialized_end=619
  _globals['_ENGINESTATUSRESPONSE']._serialized_start=621
  _globals['_ENGINESTATUSRESPONSE']._serialized_end=736
  _globals['_ENGINESERVICE']._serialized_start=739
  _globals['_ENGINESERVICE']._serialized_end=1194
# @@protoc_insertion_point(module_scope)
