# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: zk/monitor/v1/monitor.proto
# plugin: python-betterproto
# This file has been @generated

from dataclasses import dataclass
from typing import Dict

import betterproto


@dataclass(eq=False, repr=False)
class NotificationEvent(betterproto.Message):
    severity: str = betterproto.string_field(1)
    source: str = betterproto.string_field(2)
    channel: str = betterproto.string_field(3)
    message: str = betterproto.string_field(4)
    timestamp_ms: int = betterproto.int64_field(5)
    tags: Dict[str, str] = betterproto.map_field(
        6, betterproto.TYPE_STRING, betterproto.TYPE_STRING
    )


@dataclass(eq=False, repr=False)
class ReconResult(betterproto.Message):
    recon_type: str = betterproto.string_field(1)
    account_id: int = betterproto.int64_field(2)
    oms_id: str = betterproto.string_field(3)
    mismatch_count: int = betterproto.int32_field(4)
    detail: str = betterproto.string_field(5)
    run_at_ms: int = betterproto.int64_field(6)


@dataclass(eq=False, repr=False)
class AlertRule(betterproto.Message):
    rule_id: str = betterproto.string_field(1)
    metric: str = betterproto.string_field(2)
    condition: str = betterproto.string_field(3)
    severity: str = betterproto.string_field(4)
    channel: str = betterproto.string_field(5)
    enabled: bool = betterproto.bool_field(6)
