# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: zk/recorder/v1/recorder.proto
# plugin: python-betterproto
# This file has been @generated

from dataclasses import dataclass
from typing import List

import betterproto

from ...common import v1 as __common_v1__
from ...oms import v1 as __oms_v1__


@dataclass(eq=False, repr=False)
class RecorderTerminalOrder(betterproto.Message):
    """
    RecorderTerminalOrder carries the full terminal snapshot of an OMS order.
     Maps to trd.order_oms. OMS fills linkage fields; recorder does enrichment
     (strategy_id, execution_id, account name).
    """

    order_id: int = betterproto.int64_field(1)
    account_id: int = betterproto.int64_field(2)
    oms_id: str = betterproto.string_field(3)
    gw_key: str = betterproto.string_field(4)
    source_id: str = betterproto.string_field(5)
    instrument_code: str = betterproto.string_field(6)
    instrument_exch: str = betterproto.string_field(7)
    side: "__common_v1__.BuySellType" = betterproto.enum_field(8)
    open_close: "__common_v1__.OpenCloseType" = betterproto.enum_field(9)
    order_type: "__common_v1__.BasicOrderType" = betterproto.enum_field(10)
    order_status: "__oms_v1__.OrderStatus" = betterproto.enum_field(11)
    price: float = betterproto.double_field(12)
    qty: float = betterproto.double_field(13)
    filled_qty: float = betterproto.double_field(14)
    filled_avg_price: float = betterproto.double_field(15)
    ext_order_ref: str = betterproto.string_field(16)
    error_msg: str = betterproto.string_field(17)
    terminal_at_ms: int = betterproto.int64_field(18)
    created_at_ms: int = betterproto.int64_field(19)
    trades: List["__oms_v1__.Trade"] = betterproto.message_field(20)
    inferred_trades: List["__oms_v1__.Trade"] = betterproto.message_field(21)
    fees: List["__oms_v1__.Fee"] = betterproto.message_field(22)


@dataclass(eq=False, repr=False)
class RecorderTradeEvent(betterproto.Message):
    """
    RecorderTradeEvent carries a single fill event for the recorder.
     Maps to trd.trade_oms. Emitted once per explicit or inferred trade.
    """

    order_id: int = betterproto.int64_field(1)
    account_id: int = betterproto.int64_field(2)
    oms_id: str = betterproto.string_field(3)
    gw_key: str = betterproto.string_field(4)
    source_id: str = betterproto.string_field(5)
    instrument_code: str = betterproto.string_field(6)
    instrument_exch: str = betterproto.string_field(7)
    side: "__common_v1__.BuySellType" = betterproto.enum_field(8)
    open_close: "__common_v1__.OpenCloseType" = betterproto.enum_field(9)
    ext_order_ref: str = betterproto.string_field(10)
    ext_trade_id: str = betterproto.string_field(11)
    """fill data"""

    filled_qty: float = betterproto.double_field(12)
    filled_price: float = betterproto.double_field(13)
    filled_ts_ms: int = betterproto.int64_field(14)
    fill_type: "__common_v1__.FillType" = betterproto.enum_field(15)
    fees: List["__oms_v1__.Fee"] = betterproto.message_field(16)
    is_inferred: bool = betterproto.bool_field(17)
