use zk_proto_rs::zk::{
    exch_gw::v1::OrderReport, gateway::v1::SendOrderRequest as ExchSendOrderRequest,
};

/// In-flight order tracked by the simulator.
#[derive(Debug, Clone)]
pub struct SimOrder {
    pub req: ExchSendOrderRequest,
    /// Exchange-assigned order reference (simulator generated).
    pub exch_order_id: String,
    pub filled_qty: f64,
    pub remaining_qty: f64,
    /// Last update timestamp in milliseconds.
    pub update_ts: i64,
}

/// A single fill or status update generated by a match policy.
#[derive(Debug, Clone)]
pub struct MatchResult {
    /// Millisecond timestamp when the fill should be delivered.
    pub trigger_ts: i64,
    pub qty: f64,
    pub price: f64,
    /// Additional delay in ms applied on top of trigger_ts.
    pub delay_ms: i64,
    /// True if the remaining qty should be cancelled after this fill (IOC).
    pub ioc_cancel: bool,
}

/// Output from the simulator: an order report plus its effective timestamp.
#[derive(Debug, Clone)]
pub struct SimResult {
    pub ts_ms: i64,
    pub order_report: OrderReport,
}
