# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: rpc-oms.proto
# plugin: python-betterproto
# This file has been @generated

from dataclasses import dataclass
from typing import (
    TYPE_CHECKING,
    Dict,
    List,
    Optional,
)

import betterproto
import grpclib
from betterproto.grpc.grpclib_server import ServiceBase

from .. import (
    common as _common__,
    oms as _oms__,
)

if TYPE_CHECKING:
    import grpclib.server
    from betterproto.grpc.grpclib_client import MetadataLike
    from grpclib.metadata import Deadline


class OmsErrorType(betterproto.Enum):
    OMS_ERR_TYPE_UNSPECIFIED = 0
    OMS_ERR_TYPE_INVALID_REQ = 2
    OMS_ERR_TYPE_REQUEST_REJECTED = 3
    OMS_ERR_TYPE_LIMIT_EXCEEDED = 4
    OMS_ERR_TYPE_INTERNAL_ERROR = 5


class OmsResponseStatus(betterproto.Enum):
    OMS_RESP_STATUS_UNSPECIFIED = 0
    OMS_RESP_STATUS_SUCCESS = 1
    OMS_RESP_STATUS_FAIL = 2


@dataclass(eq=False, repr=False)
class OmsResponse(betterproto.Message):
    timestamp: int = betterproto.int64_field(1)
    status: "OmsResponseStatus" = betterproto.enum_field(2)
    error_type: "OmsErrorType" = betterproto.enum_field(3)
    message: str = betterproto.string_field(4)


@dataclass(eq=False, repr=False)
class OmsPlaceOrderRequest(betterproto.Message):
    order_request: "_oms__.OrderRequest" = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class OmsCancelOrderRequest(betterproto.Message):
    order_cancel_request: "_oms__.OrderCancelRequest" = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class OmsBatchPlaceOrdersRequest(betterproto.Message):
    order_requests: List["_oms__.OrderRequest"] = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class OmsBatchCancelOrdersRequest(betterproto.Message):
    order_cancel_requests: List["_oms__.OrderCancelRequest"] = (
        betterproto.message_field(1)
    )


@dataclass(eq=False, repr=False)
class OmsAlgoOrderRequest(betterproto.Message):
    algo_order_id: int = betterproto.int64_field(1)
    order_requests: List["_oms__.OrderRequest"] = betterproto.message_field(2)
    algo_type: str = betterproto.string_field(3)
    algo_config: str = betterproto.string_field(4)


@dataclass(eq=False, repr=False)
class OmsCancelAlgoOrderRequest(betterproto.Message):
    algo_order_id: int = betterproto.int64_field(1)


@dataclass(eq=False, repr=False)
class OmsReloadConfRequest(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class OmsQueryAccountRequest(betterproto.Message):
    account_id: int = betterproto.int64_field(1)
    query_gw: bool = betterproto.bool_field(2)


@dataclass(eq=False, repr=False)
class OmsAccountBalanceEntry(betterproto.Message):
    symbol: str = betterproto.string_field(1)
    avail: float = betterproto.double_field(2)
    frozen: float = betterproto.double_field(3)


@dataclass(eq=False, repr=False)
class OmsAccountResponse(betterproto.Message):
    account_id: int = betterproto.int64_field(1)
    account_balance_entries: List["_oms__.Position"] = betterproto.message_field(2)
    timestamp: int = betterproto.int64_field(3)


@dataclass(eq=False, repr=False)
class OmsQueryPositionRequest(betterproto.Message):
    account_id: int = betterproto.int64_field(1)
    query_gw: bool = betterproto.bool_field(2)


@dataclass(eq=False, repr=False)
class OmsPositionResponse(betterproto.Message):
    positions: List["_oms__.Position"] = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class OmsQueryOpenOrderRequest(betterproto.Message):
    account_id: int = betterproto.int64_field(1)
    query_gw: bool = betterproto.bool_field(2)


@dataclass(eq=False, repr=False)
class OmsQueryOrderDetailRequest(betterproto.Message):
    order_refs: List[str] = betterproto.string_field(1)
    query_gw: bool = betterproto.bool_field(2)


@dataclass(eq=False, repr=False)
class OmsOrderDetailResponse(betterproto.Message):
    orders: List["_oms__.Order"] = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class OmsQeuryTradeDetailRequest(betterproto.Message):
    order_refs: List[str] = betterproto.string_field(1)
    query_gw: bool = betterproto.bool_field(2)
    """todo: other criteria?"""


@dataclass(eq=False, repr=False)
class OmsTradeDetailResponse(betterproto.Message):
    trades: List["_oms__.Trade"] = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class PanicRequest(betterproto.Message):
    panic_account_id: int = betterproto.int64_field(1)
    panic_message: str = betterproto.string_field(2)
    panic_source: str = betterproto.string_field(3)


@dataclass(eq=False, repr=False)
class DontPanicRequest(betterproto.Message):
    panic_account_id: int = betterproto.int64_field(1)


@dataclass(eq=False, repr=False)
class OmsQueryInstrumentRefdataRequest(betterproto.Message):
    account_id: int = betterproto.int64_field(1)
    instruments: List[str] = betterproto.string_field(2)


@dataclass(eq=False, repr=False)
class OmsQueryInstrumentRefdataResponse(betterproto.Message):
    instrument_refdata: List["_common__.InstrumentRefData"] = betterproto.message_field(
        1
    )


class OrderManagerServiceStub(betterproto.ServiceStub):
    async def place_order(
        self,
        oms_place_order_request: "OmsPlaceOrderRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "OmsResponse":
        return await self._unary_unary(
            "/tqrpc_oms.OrderManagerService/PlaceOrder",
            oms_place_order_request,
            OmsResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def batch_place_orders(
        self,
        oms_batch_place_orders_request: "OmsBatchPlaceOrdersRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "OmsResponse":
        return await self._unary_unary(
            "/tqrpc_oms.OrderManagerService/BatchPlaceOrders",
            oms_batch_place_orders_request,
            OmsResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def cancel_order(
        self,
        oms_cancel_order_request: "OmsCancelOrderRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "OmsResponse":
        return await self._unary_unary(
            "/tqrpc_oms.OrderManagerService/CancelOrder",
            oms_cancel_order_request,
            OmsResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def batch_cancel_orders(
        self,
        oms_batch_cancel_orders_request: "OmsBatchCancelOrdersRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "OmsResponse":
        return await self._unary_unary(
            "/tqrpc_oms.OrderManagerService/BatchCancelOrders",
            oms_batch_cancel_orders_request,
            OmsResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def execute_algo_order(
        self,
        oms_algo_order_request: "OmsAlgoOrderRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "OmsResponse":
        return await self._unary_unary(
            "/tqrpc_oms.OrderManagerService/ExecuteAlgoOrder",
            oms_algo_order_request,
            OmsResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def cancel_algo_order(
        self,
        oms_cancel_algo_order_request: "OmsCancelAlgoOrderRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "OmsResponse":
        return await self._unary_unary(
            "/tqrpc_oms.OrderManagerService/CancelAlgoOrder",
            oms_cancel_algo_order_request,
            OmsResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def reload_config(
        self,
        oms_reload_conf_request: "OmsReloadConfRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "OmsResponse":
        return await self._unary_unary(
            "/tqrpc_oms.OrderManagerService/ReloadConfig",
            oms_reload_conf_request,
            OmsResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def panic(
        self,
        panic_request: "PanicRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "OmsResponse":
        return await self._unary_unary(
            "/tqrpc_oms.OrderManagerService/Panic",
            panic_request,
            OmsResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def dont_panic(
        self,
        dont_panic_request: "DontPanicRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "OmsResponse":
        return await self._unary_unary(
            "/tqrpc_oms.OrderManagerService/DontPanic",
            dont_panic_request,
            OmsResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def query_account_balance(
        self,
        oms_query_account_request: "OmsQueryAccountRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "OmsAccountResponse":
        return await self._unary_unary(
            "/tqrpc_oms.OrderManagerService/QueryAccountBalance",
            oms_query_account_request,
            OmsAccountResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def query_position(
        self,
        oms_query_position_request: "OmsQueryPositionRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "OmsPositionResponse":
        return await self._unary_unary(
            "/tqrpc_oms.OrderManagerService/QueryPosition",
            oms_query_position_request,
            OmsPositionResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def query_open_orders(
        self,
        oms_query_open_order_request: "OmsQueryOpenOrderRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "OmsOrderDetailResponse":
        return await self._unary_unary(
            "/tqrpc_oms.OrderManagerService/QueryOpenOrders",
            oms_query_open_order_request,
            OmsOrderDetailResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def query_order_details(
        self,
        oms_query_order_detail_request: "OmsQueryOrderDetailRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "OmsOrderDetailResponse":
        return await self._unary_unary(
            "/tqrpc_oms.OrderManagerService/QueryOrderDetails",
            oms_query_order_detail_request,
            OmsOrderDetailResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def query_trade_details(
        self,
        oms_qeury_trade_detail_request: "OmsQeuryTradeDetailRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "OmsTradeDetailResponse":
        return await self._unary_unary(
            "/tqrpc_oms.OrderManagerService/QueryTradeDetails",
            oms_qeury_trade_detail_request,
            OmsTradeDetailResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )


class OrderManagerServiceBase(ServiceBase):

    async def place_order(
        self, oms_place_order_request: "OmsPlaceOrderRequest"
    ) -> "OmsResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def batch_place_orders(
        self, oms_batch_place_orders_request: "OmsBatchPlaceOrdersRequest"
    ) -> "OmsResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def cancel_order(
        self, oms_cancel_order_request: "OmsCancelOrderRequest"
    ) -> "OmsResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def batch_cancel_orders(
        self, oms_batch_cancel_orders_request: "OmsBatchCancelOrdersRequest"
    ) -> "OmsResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def execute_algo_order(
        self, oms_algo_order_request: "OmsAlgoOrderRequest"
    ) -> "OmsResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def cancel_algo_order(
        self, oms_cancel_algo_order_request: "OmsCancelAlgoOrderRequest"
    ) -> "OmsResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def reload_config(
        self, oms_reload_conf_request: "OmsReloadConfRequest"
    ) -> "OmsResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def panic(self, panic_request: "PanicRequest") -> "OmsResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def dont_panic(self, dont_panic_request: "DontPanicRequest") -> "OmsResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def query_account_balance(
        self, oms_query_account_request: "OmsQueryAccountRequest"
    ) -> "OmsAccountResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def query_position(
        self, oms_query_position_request: "OmsQueryPositionRequest"
    ) -> "OmsPositionResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def query_open_orders(
        self, oms_query_open_order_request: "OmsQueryOpenOrderRequest"
    ) -> "OmsOrderDetailResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def query_order_details(
        self, oms_query_order_detail_request: "OmsQueryOrderDetailRequest"
    ) -> "OmsOrderDetailResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def query_trade_details(
        self, oms_qeury_trade_detail_request: "OmsQeuryTradeDetailRequest"
    ) -> "OmsTradeDetailResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def __rpc_place_order(
        self, stream: "grpclib.server.Stream[OmsPlaceOrderRequest, OmsResponse]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.place_order(request)
        await stream.send_message(response)

    async def __rpc_batch_place_orders(
        self, stream: "grpclib.server.Stream[OmsBatchPlaceOrdersRequest, OmsResponse]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.batch_place_orders(request)
        await stream.send_message(response)

    async def __rpc_cancel_order(
        self, stream: "grpclib.server.Stream[OmsCancelOrderRequest, OmsResponse]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.cancel_order(request)
        await stream.send_message(response)

    async def __rpc_batch_cancel_orders(
        self, stream: "grpclib.server.Stream[OmsBatchCancelOrdersRequest, OmsResponse]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.batch_cancel_orders(request)
        await stream.send_message(response)

    async def __rpc_execute_algo_order(
        self, stream: "grpclib.server.Stream[OmsAlgoOrderRequest, OmsResponse]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.execute_algo_order(request)
        await stream.send_message(response)

    async def __rpc_cancel_algo_order(
        self, stream: "grpclib.server.Stream[OmsCancelAlgoOrderRequest, OmsResponse]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.cancel_algo_order(request)
        await stream.send_message(response)

    async def __rpc_reload_config(
        self, stream: "grpclib.server.Stream[OmsReloadConfRequest, OmsResponse]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.reload_config(request)
        await stream.send_message(response)

    async def __rpc_panic(
        self, stream: "grpclib.server.Stream[PanicRequest, OmsResponse]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.panic(request)
        await stream.send_message(response)

    async def __rpc_dont_panic(
        self, stream: "grpclib.server.Stream[DontPanicRequest, OmsResponse]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.dont_panic(request)
        await stream.send_message(response)

    async def __rpc_query_account_balance(
        self,
        stream: "grpclib.server.Stream[OmsQueryAccountRequest, OmsAccountResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.query_account_balance(request)
        await stream.send_message(response)

    async def __rpc_query_position(
        self,
        stream: "grpclib.server.Stream[OmsQueryPositionRequest, OmsPositionResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.query_position(request)
        await stream.send_message(response)

    async def __rpc_query_open_orders(
        self,
        stream: "grpclib.server.Stream[OmsQueryOpenOrderRequest, OmsOrderDetailResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.query_open_orders(request)
        await stream.send_message(response)

    async def __rpc_query_order_details(
        self,
        stream: "grpclib.server.Stream[OmsQueryOrderDetailRequest, OmsOrderDetailResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.query_order_details(request)
        await stream.send_message(response)

    async def __rpc_query_trade_details(
        self,
        stream: "grpclib.server.Stream[OmsQeuryTradeDetailRequest, OmsTradeDetailResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.query_trade_details(request)
        await stream.send_message(response)

    def __mapping__(self) -> Dict[str, grpclib.const.Handler]:
        return {
            "/tqrpc_oms.OrderManagerService/PlaceOrder": grpclib.const.Handler(
                self.__rpc_place_order,
                grpclib.const.Cardinality.UNARY_UNARY,
                OmsPlaceOrderRequest,
                OmsResponse,
            ),
            "/tqrpc_oms.OrderManagerService/BatchPlaceOrders": grpclib.const.Handler(
                self.__rpc_batch_place_orders,
                grpclib.const.Cardinality.UNARY_UNARY,
                OmsBatchPlaceOrdersRequest,
                OmsResponse,
            ),
            "/tqrpc_oms.OrderManagerService/CancelOrder": grpclib.const.Handler(
                self.__rpc_cancel_order,
                grpclib.const.Cardinality.UNARY_UNARY,
                OmsCancelOrderRequest,
                OmsResponse,
            ),
            "/tqrpc_oms.OrderManagerService/BatchCancelOrders": grpclib.const.Handler(
                self.__rpc_batch_cancel_orders,
                grpclib.const.Cardinality.UNARY_UNARY,
                OmsBatchCancelOrdersRequest,
                OmsResponse,
            ),
            "/tqrpc_oms.OrderManagerService/ExecuteAlgoOrder": grpclib.const.Handler(
                self.__rpc_execute_algo_order,
                grpclib.const.Cardinality.UNARY_UNARY,
                OmsAlgoOrderRequest,
                OmsResponse,
            ),
            "/tqrpc_oms.OrderManagerService/CancelAlgoOrder": grpclib.const.Handler(
                self.__rpc_cancel_algo_order,
                grpclib.const.Cardinality.UNARY_UNARY,
                OmsCancelAlgoOrderRequest,
                OmsResponse,
            ),
            "/tqrpc_oms.OrderManagerService/ReloadConfig": grpclib.const.Handler(
                self.__rpc_reload_config,
                grpclib.const.Cardinality.UNARY_UNARY,
                OmsReloadConfRequest,
                OmsResponse,
            ),
            "/tqrpc_oms.OrderManagerService/Panic": grpclib.const.Handler(
                self.__rpc_panic,
                grpclib.const.Cardinality.UNARY_UNARY,
                PanicRequest,
                OmsResponse,
            ),
            "/tqrpc_oms.OrderManagerService/DontPanic": grpclib.const.Handler(
                self.__rpc_dont_panic,
                grpclib.const.Cardinality.UNARY_UNARY,
                DontPanicRequest,
                OmsResponse,
            ),
            "/tqrpc_oms.OrderManagerService/QueryAccountBalance": grpclib.const.Handler(
                self.__rpc_query_account_balance,
                grpclib.const.Cardinality.UNARY_UNARY,
                OmsQueryAccountRequest,
                OmsAccountResponse,
            ),
            "/tqrpc_oms.OrderManagerService/QueryPosition": grpclib.const.Handler(
                self.__rpc_query_position,
                grpclib.const.Cardinality.UNARY_UNARY,
                OmsQueryPositionRequest,
                OmsPositionResponse,
            ),
            "/tqrpc_oms.OrderManagerService/QueryOpenOrders": grpclib.const.Handler(
                self.__rpc_query_open_orders,
                grpclib.const.Cardinality.UNARY_UNARY,
                OmsQueryOpenOrderRequest,
                OmsOrderDetailResponse,
            ),
            "/tqrpc_oms.OrderManagerService/QueryOrderDetails": grpclib.const.Handler(
                self.__rpc_query_order_details,
                grpclib.const.Cardinality.UNARY_UNARY,
                OmsQueryOrderDetailRequest,
                OmsOrderDetailResponse,
            ),
            "/tqrpc_oms.OrderManagerService/QueryTradeDetails": grpclib.const.Handler(
                self.__rpc_query_trade_details,
                grpclib.const.Cardinality.UNARY_UNARY,
                OmsQeuryTradeDetailRequest,
                OmsTradeDetailResponse,
            ),
        }
# legacy-betterproto-compat-start
# Compatibility aliases for older BetterProto output.
OMSErrorType = OmsErrorType
OMSResponse = OmsResponse
OMSPlaceOrderRequest = OmsPlaceOrderRequest
OMSCancelOrderRequest = OmsCancelOrderRequest
OMSBatchPlaceOrdersRequest = OmsBatchPlaceOrdersRequest
OMSBatchCancelOrdersRequest = OmsBatchCancelOrdersRequest
OMSAlgoOrderRequest = OmsAlgoOrderRequest
OMSCancelAlgoOrderRequest = OmsCancelAlgoOrderRequest
OMSReloadConfRequest = OmsReloadConfRequest
OMSQueryAccountRequest = OmsQueryAccountRequest
OMSAccountBalanceEntry = OmsAccountBalanceEntry
OMSAccountResponse = OmsAccountResponse
OMSQueryPositionRequest = OmsQueryPositionRequest
OMSPositionResponse = OmsPositionResponse
OMSQueryOpenOrderRequest = OmsQueryOpenOrderRequest
OMSQueryOrderDetailRequest = OmsQueryOrderDetailRequest
OMSOrderDetailResponse = OmsOrderDetailResponse
OMSQeuryTradeDetailRequest = OmsQeuryTradeDetailRequest
OMSTradeDetailResponse = OmsTradeDetailResponse
OMSQueryInstrumentRefdataRequest = OmsQueryInstrumentRefdataRequest
OMSQueryInstrumentRefdataResponse = OmsQueryInstrumentRefdataResponse
# legacy-betterproto-compat-end
