# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: zk/rtmd/v1/rtmd.proto, zk/rtmd/v1/rtmd_query_service.proto
# plugin: python-betterproto
# This file has been @generated

from dataclasses import dataclass
from typing import (
    TYPE_CHECKING,
    Dict,
    List,
    Optional,
)

import betterproto
import grpclib
from betterproto.grpc.grpclib_server import ServiceBase

if TYPE_CHECKING:
    import grpclib.server
    from betterproto.grpc.grpclib_client import MetadataLike
    from grpclib.metadata import Deadline


class TickUpdateType(betterproto.Enum):
    TICK_TYPE_UNSPECIFIED = 0
    OB = 1
    T = 2
    M = 3


class KlineKlineType(betterproto.Enum):
    KLINE_1MIN = 0
    KLINE_5MIN = 1
    KLINE_15MIN = 2
    KLINE_30MIN = 3
    KLINE_1HOUR = 4
    KLINE_4HOUR = 5
    KLINE_1DAY = 6


@dataclass(eq=False, repr=False)
class PriceLevel(betterproto.Message):
    price: float = betterproto.double_field(1)
    qty: float = betterproto.double_field(2)
    num_of_orders: int = betterproto.int64_field(3)
    num_of_pos: int = betterproto.int64_field(4)


@dataclass(eq=False, repr=False)
class Trade(betterproto.Message):
    price: float = betterproto.double_field(1)
    qty: float = betterproto.double_field(2)
    timestamp: int = betterproto.int64_field(3)
    side: str = betterproto.string_field(4)
    instrument_code: str = betterproto.string_field(5)


@dataclass(eq=False, repr=False)
class TickData(betterproto.Message):
    tick_type: "TickUpdateType" = betterproto.enum_field(1)
    instrument_code: str = betterproto.string_field(2)
    exchange: str = betterproto.string_field(3)
    original_timestamp: int = betterproto.int64_field(4)
    received_timestamp: int = betterproto.int64_field(5)
    volume: float = betterproto.double_field(7)
    latest_trade_price: float = betterproto.double_field(8)
    latest_trade_qty: float = betterproto.double_field(9)
    latest_trade_side: str = betterproto.string_field(10)
    buy_price_levels: List["PriceLevel"] = betterproto.message_field(14)
    sell_price_levels: List["PriceLevel"] = betterproto.message_field(15)


@dataclass(eq=False, repr=False)
class Kline(betterproto.Message):
    timestamp: int = betterproto.int64_field(1)
    kline_end_timestamp: int = betterproto.int64_field(2)
    open: float = betterproto.double_field(3)
    high: float = betterproto.double_field(4)
    close: float = betterproto.double_field(5)
    low: float = betterproto.double_field(6)
    volume: float = betterproto.double_field(7)
    amount: float = betterproto.double_field(8)
    kline_type: "KlineKlineType" = betterproto.enum_field(9)
    symbol: str = betterproto.string_field(10)
    source: str = betterproto.string_field(11)


@dataclass(eq=False, repr=False)
class FundingRate(betterproto.Message):
    instrument_code: str = betterproto.string_field(1)
    exchange: str = betterproto.string_field(2)
    curr_funding_rate_timestamp: int = betterproto.int64_field(3)
    funding_rate: float = betterproto.double_field(4)
    mark_price: float = betterproto.double_field(6)
    index_price: float = betterproto.double_field(7)
    next_funding_rate: float = betterproto.double_field(10)
    observe_timestamp: int = betterproto.int64_field(12)
    next_funding_rate_timestamp: int = betterproto.int64_field(13)
    original_message: str = betterproto.string_field(14)
    next_payment_timestamp: int = betterproto.int64_field(15)


@dataclass(eq=False, repr=False)
class RealtimeSignal(betterproto.Message):
    namespace: str = betterproto.string_field(1)
    instrument: str = betterproto.string_field(2)
    timestamp: int = betterproto.int64_field(3)
    data: Dict[str, float] = betterproto.map_field(
        4, betterproto.TYPE_STRING, betterproto.TYPE_DOUBLE
    )
    message: str = betterproto.string_field(5)
    data_int: Dict[str, int] = betterproto.map_field(
        6, betterproto.TYPE_STRING, betterproto.TYPE_INT64
    )
    data_str: Dict[str, str] = betterproto.map_field(
        7, betterproto.TYPE_STRING, betterproto.TYPE_STRING
    )


@dataclass(eq=False, repr=False)
class OrderBook(betterproto.Message):
    instrument_code: str = betterproto.string_field(1)
    exchange: str = betterproto.string_field(2)
    timestamp_ms: int = betterproto.int64_field(3)
    buy_levels: List["PriceLevel"] = betterproto.message_field(4)
    sell_levels: List["PriceLevel"] = betterproto.message_field(5)


@dataclass(eq=False, repr=False)
class QueryTickRequest(betterproto.Message):
    instrument_code: str = betterproto.string_field(1)


@dataclass(eq=False, repr=False)
class QueryTickResponse(betterproto.Message):
    tick: "TickData" = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class QueryOrderBookRequest(betterproto.Message):
    instrument_code: str = betterproto.string_field(1)
    depth: Optional[int] = betterproto.uint32_field(2, optional=True)


@dataclass(eq=False, repr=False)
class QueryOrderBookResponse(betterproto.Message):
    orderbook: "OrderBook" = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class QueryFundingRequest(betterproto.Message):
    instrument_code: str = betterproto.string_field(1)


@dataclass(eq=False, repr=False)
class QueryFundingResponse(betterproto.Message):
    funding: "FundingRate" = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class QueryKlinesRequest(betterproto.Message):
    instrument_code: str = betterproto.string_field(1)
    interval: str = betterproto.string_field(2)
    limit: int = betterproto.uint32_field(3)
    from_ms: Optional[int] = betterproto.int64_field(4, optional=True)
    to_ms: Optional[int] = betterproto.int64_field(5, optional=True)


@dataclass(eq=False, repr=False)
class QueryKlinesResponse(betterproto.Message):
    klines: List["Kline"] = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class HealthCheckRequest(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class HealthCheckResponse(betterproto.Message):
    status: str = betterproto.string_field(1)


class RtmdQueryServiceStub(betterproto.ServiceStub):
    async def query_current_tick(
        self,
        query_tick_request: "QueryTickRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "QueryTickResponse":
        return await self._unary_unary(
            "/zk.rtmd.v1.RtmdQueryService/QueryCurrentTick",
            query_tick_request,
            QueryTickResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def query_current_order_book(
        self,
        query_order_book_request: "QueryOrderBookRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "QueryOrderBookResponse":
        return await self._unary_unary(
            "/zk.rtmd.v1.RtmdQueryService/QueryCurrentOrderBook",
            query_order_book_request,
            QueryOrderBookResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def query_current_funding(
        self,
        query_funding_request: "QueryFundingRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "QueryFundingResponse":
        return await self._unary_unary(
            "/zk.rtmd.v1.RtmdQueryService/QueryCurrentFunding",
            query_funding_request,
            QueryFundingResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def query_klines(
        self,
        query_klines_request: "QueryKlinesRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "QueryKlinesResponse":
        return await self._unary_unary(
            "/zk.rtmd.v1.RtmdQueryService/QueryKlines",
            query_klines_request,
            QueryKlinesResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def health_check(
        self,
        health_check_request: "HealthCheckRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "HealthCheckResponse":
        return await self._unary_unary(
            "/zk.rtmd.v1.RtmdQueryService/HealthCheck",
            health_check_request,
            HealthCheckResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )


class RtmdQueryServiceBase(ServiceBase):

    async def query_current_tick(
        self, query_tick_request: "QueryTickRequest"
    ) -> "QueryTickResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def query_current_order_book(
        self, query_order_book_request: "QueryOrderBookRequest"
    ) -> "QueryOrderBookResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def query_current_funding(
        self, query_funding_request: "QueryFundingRequest"
    ) -> "QueryFundingResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def query_klines(
        self, query_klines_request: "QueryKlinesRequest"
    ) -> "QueryKlinesResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def health_check(
        self, health_check_request: "HealthCheckRequest"
    ) -> "HealthCheckResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def __rpc_query_current_tick(
        self, stream: "grpclib.server.Stream[QueryTickRequest, QueryTickResponse]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.query_current_tick(request)
        await stream.send_message(response)

    async def __rpc_query_current_order_book(
        self,
        stream: "grpclib.server.Stream[QueryOrderBookRequest, QueryOrderBookResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.query_current_order_book(request)
        await stream.send_message(response)

    async def __rpc_query_current_funding(
        self, stream: "grpclib.server.Stream[QueryFundingRequest, QueryFundingResponse]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.query_current_funding(request)
        await stream.send_message(response)

    async def __rpc_query_klines(
        self, stream: "grpclib.server.Stream[QueryKlinesRequest, QueryKlinesResponse]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.query_klines(request)
        await stream.send_message(response)

    async def __rpc_health_check(
        self, stream: "grpclib.server.Stream[HealthCheckRequest, HealthCheckResponse]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.health_check(request)
        await stream.send_message(response)

    def __mapping__(self) -> Dict[str, grpclib.const.Handler]:
        return {
            "/zk.rtmd.v1.RtmdQueryService/QueryCurrentTick": grpclib.const.Handler(
                self.__rpc_query_current_tick,
                grpclib.const.Cardinality.UNARY_UNARY,
                QueryTickRequest,
                QueryTickResponse,
            ),
            "/zk.rtmd.v1.RtmdQueryService/QueryCurrentOrderBook": grpclib.const.Handler(
                self.__rpc_query_current_order_book,
                grpclib.const.Cardinality.UNARY_UNARY,
                QueryOrderBookRequest,
                QueryOrderBookResponse,
            ),
            "/zk.rtmd.v1.RtmdQueryService/QueryCurrentFunding": grpclib.const.Handler(
                self.__rpc_query_current_funding,
                grpclib.const.Cardinality.UNARY_UNARY,
                QueryFundingRequest,
                QueryFundingResponse,
            ),
            "/zk.rtmd.v1.RtmdQueryService/QueryKlines": grpclib.const.Handler(
                self.__rpc_query_klines,
                grpclib.const.Cardinality.UNARY_UNARY,
                QueryKlinesRequest,
                QueryKlinesResponse,
            ),
            "/zk.rtmd.v1.RtmdQueryService/HealthCheck": grpclib.const.Handler(
                self.__rpc_health_check,
                grpclib.const.Cardinality.UNARY_UNARY,
                HealthCheckRequest,
                HealthCheckResponse,
            ),
        }
