// @generated
// This file is @generated by prost-build.
// ===== Messages (from strategy.proto, field numbers preserved) =====

#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Strategy {
    #[prost(string, tag="1")]
    pub strategy_key: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub strategy_desc: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub strategy_script_file_name: ::prost::alloc::string::String,
    #[prost(int64, repeated, tag="4")]
    pub account_ids: ::prost::alloc::vec::Vec<i64>,
    #[prost(string, repeated, tag="5")]
    pub symbols: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, tag="6")]
    pub config: ::prost::alloc::string::String,
    #[prost(string, tag="7")]
    pub oms_config: ::prost::alloc::string::String,
    #[prost(string, tag="8")]
    pub current_execution_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StrategyExecution {
    #[prost(int64, tag="1")]
    pub start_ts: i64,
    #[prost(int64, tag="2")]
    pub end_ts: i64,
    #[prost(string, tag="3")]
    pub strategy_key: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub execution_id: ::prost::alloc::string::String,
    #[prost(string, tag="6")]
    pub config: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StrategyCommand {
    #[prost(enumeration="StrategyCommandType", tag="1")]
    pub cmd_type: i32,
    #[prost(string, tag="2")]
    pub source_id: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub strategy_key: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub execution_id: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub cmd_data: ::prost::alloc::string::String,
}
/// TBA
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StrategyConfig {
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StrategyLifecycleNotifyEvent {
    #[prost(int64, tag="1")]
    pub timestamp: i64,
    #[prost(string, tag="2")]
    pub strategy_id: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub execution_id: ::prost::alloc::string::String,
    #[prost(enumeration="StrategyStatusType", tag="4")]
    pub status: i32,
    #[prost(string, tag="5")]
    pub payload_json: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StrategyOrderEvent {
    #[prost(int64, tag="1")]
    pub timestamp: i64,
    #[prost(string, tag="2")]
    pub strategy_id: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub execution_id: ::prost::alloc::string::String,
    #[prost(int64, tag="5")]
    pub order_id: i64,
    #[prost(double, tag="6")]
    pub price: f64,
    #[prost(double, tag="7")]
    pub qty: f64,
    #[prost(string, tag="8")]
    pub symbol: ::prost::alloc::string::String,
    #[prost(int64, tag="9")]
    pub account_id: i64,
    #[prost(enumeration="super::super::common::v1::BuySellType", tag="10")]
    pub buy_sell: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StrategyCancelEvent {
    #[prost(int64, tag="1")]
    pub timestamp: i64,
    #[prost(string, tag="2")]
    pub strategy_id: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub execution_id: ::prost::alloc::string::String,
    #[prost(int64, tag="4")]
    pub order_id: i64,
    #[prost(string, tag="5")]
    pub exch_order_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StrategyLogEvent {
    #[prost(int64, tag="1")]
    pub timestamp: i64,
    #[prost(string, tag="2")]
    pub strategy_id: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub execution_id: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub log: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub log_type: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StrategyNotification {
    #[prost(int64, tag="1")]
    pub timestamp: i64,
    #[prost(string, tag="2")]
    pub strategy_key: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub execution_id: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub message: ::prost::alloc::string::String,
    #[prost(map="string, string", tag="5")]
    pub message_meta_info: ::std::collections::HashMap<::prost::alloc::string::String, ::prost::alloc::string::String>,
}
// ===== New messages (zk.strategy.v1 additions) =====

#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StrategyStructuredLogEvent {
    #[prost(string, tag="1")]
    pub strategy_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub execution_id: ::prost::alloc::string::String,
    #[prost(enumeration="LogLevel", tag="3")]
    pub level: i32,
    #[prost(string, tag="4")]
    pub message: ::prost::alloc::string::String,
    #[prost(int64, tag="5")]
    pub timestamp_ms: i64,
    #[prost(map="string, string", tag="6")]
    pub meta: ::std::collections::HashMap<::prost::alloc::string::String, ::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StrategyAlert {
    /// INFO | WARN | CRITICAL
    #[prost(string, tag="1")]
    pub severity: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub channel: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub message: ::prost::alloc::string::String,
    #[prost(map="string, string", tag="4")]
    pub payload: ::std::collections::HashMap<::prost::alloc::string::String, ::prost::alloc::string::String>,
}
// ===== Enums (from strategy.proto, values preserved) =====

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum StrategyCommandType {
    StratCmdUnspecified = 0,
    StratCmdReinit = 1,
    StratCmdPause = 2,
    StratSpecificCmd = 3,
}
impl StrategyCommandType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::StratCmdUnspecified => "STRAT_CMD_UNSPECIFIED",
            Self::StratCmdReinit => "STRAT_CMD_REINIT",
            Self::StratCmdPause => "STRAT_CMD_PAUSE",
            Self::StratSpecificCmd => "STRAT_SPECIFIC_CMD",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "STRAT_CMD_UNSPECIFIED" => Some(Self::StratCmdUnspecified),
            "STRAT_CMD_REINIT" => Some(Self::StratCmdReinit),
            "STRAT_CMD_PAUSE" => Some(Self::StratCmdPause),
            "STRAT_SPECIFIC_CMD" => Some(Self::StratSpecificCmd),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum StrategyStatusType {
    StratStatusUnspecified = 0,
    StratStatusInitializing = 1,
    StratStatusRunning = 2,
    StratStatusStopped = 3,
    StratStatusError = 4,
    StratStatusExceptioned = 5,
}
impl StrategyStatusType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::StratStatusUnspecified => "STRAT_STATUS_UNSPECIFIED",
            Self::StratStatusInitializing => "STRAT_STATUS_INITIALIZING",
            Self::StratStatusRunning => "STRAT_STATUS_RUNNING",
            Self::StratStatusStopped => "STRAT_STATUS_STOPPED",
            Self::StratStatusError => "STRAT_STATUS_ERROR",
            Self::StratStatusExceptioned => "STRAT_STATUS_EXCEPTIONED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "STRAT_STATUS_UNSPECIFIED" => Some(Self::StratStatusUnspecified),
            "STRAT_STATUS_INITIALIZING" => Some(Self::StratStatusInitializing),
            "STRAT_STATUS_RUNNING" => Some(Self::StratStatusRunning),
            "STRAT_STATUS_STOPPED" => Some(Self::StratStatusStopped),
            "STRAT_STATUS_ERROR" => Some(Self::StratStatusError),
            "STRAT_STATUS_EXCEPTIONED" => Some(Self::StratStatusExceptioned),
            _ => None,
        }
    }
}
// ===== New enums (zk.strategy.v1 additions) =====

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum StrategyLifecycleState {
    LifecycleUnspecified = 0,
    Initializing = 1,
    Running = 2,
    Paused = 3,
    Stopped = 4,
    Error = 5,
}
impl StrategyLifecycleState {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::LifecycleUnspecified => "LIFECYCLE_UNSPECIFIED",
            Self::Initializing => "INITIALIZING",
            Self::Running => "RUNNING",
            Self::Paused => "PAUSED",
            Self::Stopped => "STOPPED",
            Self::Error => "ERROR",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "LIFECYCLE_UNSPECIFIED" => Some(Self::LifecycleUnspecified),
            "INITIALIZING" => Some(Self::Initializing),
            "RUNNING" => Some(Self::Running),
            "PAUSED" => Some(Self::Paused),
            "STOPPED" => Some(Self::Stopped),
            "ERROR" => Some(Self::Error),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum StrategyRuntimeType {
    RuntimeUnspecified = 0,
    RuntimeRust = 1,
    RuntimePyEmbedded = 2,
    RuntimePyWorker = 3,
}
impl StrategyRuntimeType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::RuntimeUnspecified => "RUNTIME_UNSPECIFIED",
            Self::RuntimeRust => "RUNTIME_RUST",
            Self::RuntimePyEmbedded => "RUNTIME_PY_EMBEDDED",
            Self::RuntimePyWorker => "RUNTIME_PY_WORKER",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "RUNTIME_UNSPECIFIED" => Some(Self::RuntimeUnspecified),
            "RUNTIME_RUST" => Some(Self::RuntimeRust),
            "RUNTIME_PY_EMBEDDED" => Some(Self::RuntimePyEmbedded),
            "RUNTIME_PY_WORKER" => Some(Self::RuntimePyWorker),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum LogLevel {
    LogUnspecified = 0,
    LogTrace = 1,
    LogDebug = 2,
    LogInfo = 3,
    LogWarn = 4,
    LogError = 5,
}
impl LogLevel {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::LogUnspecified => "LOG_UNSPECIFIED",
            Self::LogTrace => "LOG_TRACE",
            Self::LogDebug => "LOG_DEBUG",
            Self::LogInfo => "LOG_INFO",
            Self::LogWarn => "LOG_WARN",
            Self::LogError => "LOG_ERROR",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "LOG_UNSPECIFIED" => Some(Self::LogUnspecified),
            "LOG_TRACE" => Some(Self::LogTrace),
            "LOG_DEBUG" => Some(Self::LogDebug),
            "LOG_INFO" => Some(Self::LogInfo),
            "LOG_WARN" => Some(Self::LogWarn),
            "LOG_ERROR" => Some(Self::LogError),
            _ => None,
        }
    }
}
// @@protoc_insertion_point(module)
