# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: zk/gateway/v1/gateway_service.proto, zk/gateway/v1/gateway_simulator_admin.proto
# plugin: python-betterproto
# This file has been @generated

from dataclasses import dataclass
from typing import (
    TYPE_CHECKING,
    Dict,
    List,
    Optional,
)

import betterproto
import grpclib
from betterproto.grpc.grpclib_server import ServiceBase

from ...common import v1 as __common_v1__
from ...exch_gw import v1 as __exch_gw_v1__
from ...oms import v1 as __oms_v1__
from ...rtmd import v1 as __rtmd_v1__

if TYPE_CHECKING:
    import grpclib.server
    from betterproto.grpc.grpclib_client import MetadataLike
    from grpclib.metadata import Deadline


class GatewayCommandRequestCommandType(betterproto.Enum):
    CMD_TYPE_UNSPECIFIED = 0
    CMD_TYPE_RECONNECT_EXCH = 1
    CMD_TYPE_PUBLISH_ACCOUNT = 2
    CMD_TYPE_USER_DEFINED = 3


class GatewayResponseStatus(betterproto.Enum):
    GW_RESP_STATUS_UNSPECIFIED = 0
    GW_RESP_STATUS_SUCCESS = 1
    GW_RESP_STATUS_FAIL = 2


class FillMode(betterproto.Enum):
    UNSPECIFIED = 0
    FULL = 1
    PARTIAL = 2


class ErrorScope(betterproto.Enum):
    UNSPECIFIED = 0
    PLACE_ORDER = 1
    CANCEL_ORDER = 2
    QUERY_ACCOUNT_BALANCE = 3
    QUERY_ORDER_DETAIL = 4


class ErrorEffectType(betterproto.Enum):
    ERROR_EFFECT_UNSPECIFIED = 0
    ERROR_EFFECT_RPC_ERROR = 1
    ERROR_EFFECT_REJECT_ORDER = 2
    ERROR_EFFECT_DELAY_RESPONSE = 3
    ERROR_EFFECT_DROP_REPORT = 4
    ERROR_EFFECT_DUPLICATE_REPORT = 5
    ERROR_EFFECT_DISCONNECT = 6


class TriggerPolicy(betterproto.Enum):
    UNSPECIFIED = 0
    ONCE = 1
    TIMES = 2
    UNTIL_CLEARED = 3


class MutationMode(betterproto.Enum):
    UNSPECIFIED = 0
    UPSERT = 1
    REMOVE = 2


@dataclass(eq=False, repr=False)
class SendOrderRequest(betterproto.Message):
    correlation_id: int = betterproto.int64_field(1)
    exch_account_id: str = betterproto.string_field(2)
    instrument: str = betterproto.string_field(3)
    buysell_type: "__common_v1__.BuySellType" = betterproto.enum_field(4)
    openclose_type: "__common_v1__.OpenCloseType" = betterproto.enum_field(5)
    order_type: "__common_v1__.BasicOrderType" = betterproto.enum_field(6)
    scaled_price: float = betterproto.double_field(7)
    scaled_qty: float = betterproto.double_field(8)
    leverage: float = betterproto.double_field(9)
    timestamp: int = betterproto.int64_field(10)
    exch_specific_params: "__common_v1__.ExtraData" = betterproto.message_field(11)
    time_inforce_type: "__common_v1__.TimeInForceType" = betterproto.enum_field(12)
    extra_order_tags: List["__common_v1__.ExtraOrderTagType"] = betterproto.enum_field(
        13
    )


@dataclass(eq=False, repr=False)
class BatchSendOrdersRequest(betterproto.Message):
    order_requests: List["SendOrderRequest"] = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class ExchOrder(betterproto.Message):
    order_ref: str = betterproto.string_field(1)
    instrument: str = betterproto.string_field(2)
    buysell_type: "__common_v1__.BuySellType" = betterproto.enum_field(3)
    openclose_type: "__common_v1__.OpenCloseType" = betterproto.enum_field(4)
    order_type: "__common_v1__.BasicOrderType" = betterproto.enum_field(5)
    order_report: "__exch_gw_v1__.OrderReport" = betterproto.message_field(6)
    leverage: float = betterproto.double_field(11)
    timestamp: int = betterproto.int64_field(12)
    exch_order_original: str = betterproto.string_field(13)


@dataclass(eq=False, repr=False)
class CancelOrderRequest(betterproto.Message):
    exch_order_ref: str = betterproto.string_field(1)
    order_id: int = betterproto.int64_field(2)
    exch_specific_params: "__common_v1__.ExtraData" = betterproto.message_field(3)
    timestamp: int = betterproto.int64_field(4)


@dataclass(eq=False, repr=False)
class BatchCancelOrdersRequest(betterproto.Message):
    cancel_requests: List["CancelOrderRequest"] = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class AmendOrderRequest(betterproto.Message):
    exch_order_ref: str = betterproto.string_field(1)


@dataclass(eq=False, repr=False)
class GatewayCommandRequest(betterproto.Message):
    command_type: "GatewayCommandRequestCommandType" = betterproto.enum_field(1)
    command_source_id: str = betterproto.string_field(2)
    command_payload: str = betterproto.string_field(3)


@dataclass(eq=False, repr=False)
class GatewayResponse(betterproto.Message):
    timestamp: int = betterproto.int64_field(1)
    status: "GatewayResponseStatus" = betterproto.enum_field(2)
    error_code: int = betterproto.int64_field(4)
    message: str = betterproto.string_field(5)
    rejection_info: "__common_v1__.Rejection" = betterproto.message_field(6)


@dataclass(eq=False, repr=False)
class SingleOrderQuery(betterproto.Message):
    exch_order_ref: str = betterproto.string_field(1)
    order_id: int = betterproto.int64_field(2)
    symbol: str = betterproto.string_field(3)
    exch_account: str = betterproto.string_field(4)


@dataclass(eq=False, repr=False)
class QueryAccountRequest(betterproto.Message):
    explicit_symbols: List[str] = betterproto.string_field(1)


@dataclass(eq=False, repr=False)
class AccountResponse(betterproto.Message):
    exch_account_code: str = betterproto.string_field(1)
    balance_update: "__exch_gw_v1__.BalanceUpdate" = betterproto.message_field(4)
    timestamp: int = betterproto.int64_field(3)


@dataclass(eq=False, repr=False)
class QueryPositionRequest(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class PositionResponse(betterproto.Message):
    positions: List["__oms_v1__.Position"] = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class QueryOpenOrderRequest(betterproto.Message):
    exch_account_code: str = betterproto.string_field(1)


@dataclass(eq=False, repr=False)
class QueryOrderDetailRequest(betterproto.Message):
    order_queries: List["SingleOrderQuery"] = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class OrderDetailResponse(betterproto.Message):
    orders: List["ExchOrder"] = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class QueryTradeDetailRequest(betterproto.Message):
    exch_account_id: str = betterproto.string_field(1)
    instrument_code: str = betterproto.string_field(2)
    start_ts: int = betterproto.int64_field(3)
    end_ts: int = betterproto.int64_field(4)
    limit: int = betterproto.int64_field(5)


@dataclass(eq=False, repr=False)
class HistoryTradeRecord(betterproto.Message):
    exch_order_ref: str = betterproto.string_field(1)
    order_info: "__exch_gw_v1__.OrderInfo" = betterproto.message_field(2)
    trade: "__exch_gw_v1__.TradeReport" = betterproto.message_field(3)
    fee: "__exch_gw_v1__.FeeReport" = betterproto.message_field(4)
    extra_fees: List["__exch_gw_v1__.FeeReport"] = betterproto.message_field(5)
    timestamp: int = betterproto.int64_field(6)
    idx: str = betterproto.string_field(7)


@dataclass(eq=False, repr=False)
class TradeDetailResponse(betterproto.Message):
    history_trades: List["HistoryTradeRecord"] = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class QueryFeeRequest(betterproto.Message):
    instrument_code: str = betterproto.string_field(1)
    start_ts: int = betterproto.int64_field(2)
    end_ts: int = betterproto.int64_field(3)
    exch_account_id: str = betterproto.string_field(4)
    fee_types: "__common_v1__.FeeType" = betterproto.enum_field(5)
    limit: int = betterproto.int64_field(6)


@dataclass(eq=False, repr=False)
class FeeResponse(betterproto.Message):
    fees: List["__exch_gw_v1__.FeeReport"] = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class QueryOrderTradesRequest(betterproto.Message):
    exch_order_ref: str = betterproto.string_field(1)
    instrument_exch: str = betterproto.string_field(2)


@dataclass(eq=False, repr=False)
class OrderTradesResponse(betterproto.Message):
    order_id: str = betterproto.string_field(1)
    exch_order_ref: str = betterproto.string_field(2)
    instrument_exch: str = betterproto.string_field(3)
    buysell_type: "__common_v1__.BuySellType" = betterproto.enum_field(4)
    exch_trades: List["ExchTrade"] = betterproto.message_field(5)


@dataclass(eq=False, repr=False)
class ExchTrade(betterproto.Message):
    trade_report: "__exch_gw_v1__.TradeReport" = betterproto.message_field(1)
    fee_report: "__exch_gw_v1__.FeeReport" = betterproto.message_field(2)


@dataclass(eq=False, repr=False)
class GenericRequest(betterproto.Message):
    request_json: str = betterproto.string_field(1)


@dataclass(eq=False, repr=False)
class GenericResponse(betterproto.Message):
    response_json: str = betterproto.string_field(1)


@dataclass(eq=False, repr=False)
class AccountSettingRequest(betterproto.Message):
    account_setting_entry: "__exch_gw_v1__.AccountSettingEntry" = (
        betterproto.message_field(1)
    )


@dataclass(eq=False, repr=False)
class AccountSettingUpdateResponse(betterproto.Message):
    margin_mode_changed: bool = betterproto.bool_field(1)
    leverage_changed: bool = betterproto.bool_field(2)
    err_msg: str = betterproto.string_field(3)


@dataclass(eq=False, repr=False)
class QueryAccountSettingRequest(betterproto.Message):
    exch_account_id: str = betterproto.string_field(1)
    instrument: str = betterproto.string_field(2)


@dataclass(eq=False, repr=False)
class AccountSettingResponse(betterproto.Message):
    account_setting_entry: "__exch_gw_v1__.AccountSettingEntry" = (
        betterproto.message_field(1)
    )
    original_info: str = betterproto.string_field(2)


@dataclass(eq=False, repr=False)
class ForceMatchRequest(betterproto.Message):
    order_id: int = betterproto.int64_field(1)
    fill_mode: "FillMode" = betterproto.enum_field(2)
    fill_qty: float = betterproto.double_field(3)
    fill_price: float = betterproto.double_field(4)
    publish_balance_update: bool = betterproto.bool_field(5)
    publish_position_update: bool = betterproto.bool_field(6)
    reason: str = betterproto.string_field(7)


@dataclass(eq=False, repr=False)
class ForceMatchResponse(betterproto.Message):
    accepted: bool = betterproto.bool_field(1)
    matched_order_id: int = betterproto.int64_field(2)
    generated_trade_count: int = betterproto.int32_field(3)
    remaining_open_qty: float = betterproto.double_field(4)
    message: str = betterproto.string_field(5)


@dataclass(eq=False, repr=False)
class ErrorMatchCriteria(betterproto.Message):
    account_id: int = betterproto.int64_field(1)
    side: int = betterproto.int32_field(2)
    instrument: str = betterproto.string_field(3)
    order_id: int = betterproto.int64_field(4)
    client_order_id: int = betterproto.int64_field(5)
    exch_account_id: str = betterproto.string_field(6)


@dataclass(eq=False, repr=False)
class InjectErrorRequest(betterproto.Message):
    error_id: str = betterproto.string_field(1)
    scope: "ErrorScope" = betterproto.enum_field(2)
    match_criteria: "ErrorMatchCriteria" = betterproto.message_field(3)
    effect: "ErrorEffectType" = betterproto.enum_field(4)
    grpc_status_code: int = betterproto.int32_field(5)
    """effect parameters"""

    error_message: str = betterproto.string_field(6)
    delay_ms: int = betterproto.int64_field(7)
    duplicate_count: int = betterproto.int32_field(8)
    trigger_policy: "TriggerPolicy" = betterproto.enum_field(9)
    """trigger"""

    trigger_times: int = betterproto.int32_field(10)
    priority: int = betterproto.int32_field(11)
    enabled: bool = betterproto.bool_field(12)


@dataclass(eq=False, repr=False)
class InjectErrorResponse(betterproto.Message):
    error_id: str = betterproto.string_field(1)
    accepted: bool = betterproto.bool_field(2)
    message: str = betterproto.string_field(3)


@dataclass(eq=False, repr=False)
class ListInjectedErrorsRequest(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class InjectedErrorInfo(betterproto.Message):
    error_id: str = betterproto.string_field(1)
    scope: "ErrorScope" = betterproto.enum_field(2)
    match_criteria: "ErrorMatchCriteria" = betterproto.message_field(3)
    effect: "ErrorEffectType" = betterproto.enum_field(4)
    trigger_policy: "TriggerPolicy" = betterproto.enum_field(5)
    remaining_triggers: int = betterproto.int32_field(6)
    priority: int = betterproto.int32_field(7)
    enabled: bool = betterproto.bool_field(8)
    created_at: int = betterproto.int64_field(9)
    last_fired_at: int = betterproto.int64_field(10)


@dataclass(eq=False, repr=False)
class ListInjectedErrorsResponse(betterproto.Message):
    errors: List["InjectedErrorInfo"] = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class ClearInjectedErrorRequest(betterproto.Message):
    error_id: str = betterproto.string_field(1)


@dataclass(eq=False, repr=False)
class ClearInjectedErrorResponse(betterproto.Message):
    accepted: bool = betterproto.bool_field(1)
    cleared_count: int = betterproto.int32_field(2)
    message: str = betterproto.string_field(3)


@dataclass(eq=False, repr=False)
class ResetSimulatorRequest(betterproto.Message):
    reason: str = betterproto.string_field(1)


@dataclass(eq=False, repr=False)
class ResetSimulatorResponse(betterproto.Message):
    accepted: bool = betterproto.bool_field(1)
    cleared_orders: int = betterproto.int32_field(2)
    cleared_error_rules: int = betterproto.int32_field(3)
    message: str = betterproto.string_field(4)


@dataclass(eq=False, repr=False)
class BalanceMutation(betterproto.Message):
    asset: str = betterproto.string_field(1)
    total_qty: float = betterproto.double_field(2)
    avail_qty: float = betterproto.double_field(3)
    frozen_qty: float = betterproto.double_field(4)
    mode: "MutationMode" = betterproto.enum_field(5)


@dataclass(eq=False, repr=False)
class PositionMutation(betterproto.Message):
    instrument_code: str = betterproto.string_field(1)
    long_short_type: int = betterproto.int32_field(2)
    total_qty: float = betterproto.double_field(3)
    avail_qty: float = betterproto.double_field(4)
    frozen_qty: float = betterproto.double_field(5)
    mode: "MutationMode" = betterproto.enum_field(6)


@dataclass(eq=False, repr=False)
class SetAccountStateRequest(betterproto.Message):
    account_id: int = betterproto.int64_field(1)
    balance_mutations: List["BalanceMutation"] = betterproto.message_field(2)
    position_mutations: List["PositionMutation"] = betterproto.message_field(3)
    clear_existing_balances: bool = betterproto.bool_field(4)
    clear_existing_positions: bool = betterproto.bool_field(5)
    publish_updates: bool = betterproto.bool_field(6)
    reason: str = betterproto.string_field(7)


@dataclass(eq=False, repr=False)
class SetAccountStateResponse(betterproto.Message):
    accepted: bool = betterproto.bool_field(1)
    applied_balance_count: int = betterproto.int32_field(2)
    applied_position_count: int = betterproto.int32_field(3)
    message: str = betterproto.string_field(4)


@dataclass(eq=False, repr=False)
class SubmitSyntheticTickRequest(betterproto.Message):
    tick: "__rtmd_v1__.TickData" = betterproto.message_field(1)
    source_tag: str = betterproto.string_field(2)
    reason: str = betterproto.string_field(3)


@dataclass(eq=False, repr=False)
class SubmitSyntheticTickResponse(betterproto.Message):
    accepted: bool = betterproto.bool_field(1)
    affected_order_count: int = betterproto.int32_field(2)
    generated_report_count: int = betterproto.int32_field(3)
    message: str = betterproto.string_field(4)


@dataclass(eq=False, repr=False)
class ListOpenOrdersRequest(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class SimOpenOrder(betterproto.Message):
    order_id: int = betterproto.int64_field(1)
    exch_order_ref: str = betterproto.string_field(2)
    account_id: int = betterproto.int64_field(3)
    instrument: str = betterproto.string_field(4)
    side: int = betterproto.int32_field(5)
    remaining_qty: float = betterproto.double_field(6)
    filled_qty: float = betterproto.double_field(7)
    limit_price: float = betterproto.double_field(8)
    created_ts: int = betterproto.int64_field(9)
    updated_ts: int = betterproto.int64_field(10)


@dataclass(eq=False, repr=False)
class ListOpenOrdersResponse(betterproto.Message):
    orders: List["SimOpenOrder"] = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class PauseMatchingRequest(betterproto.Message):
    reason: str = betterproto.string_field(1)


@dataclass(eq=False, repr=False)
class ResumeMatchingRequest(betterproto.Message):
    reason: str = betterproto.string_field(1)


@dataclass(eq=False, repr=False)
class MatchingStateResponse(betterproto.Message):
    matching_paused: bool = betterproto.bool_field(1)
    message: str = betterproto.string_field(2)


@dataclass(eq=False, repr=False)
class SetMatchPolicyRequest(betterproto.Message):
    policy_name: str = betterproto.string_field(1)
    policy_config: str = betterproto.string_field(2)
    reason: str = betterproto.string_field(3)


@dataclass(eq=False, repr=False)
class SetMatchPolicyResponse(betterproto.Message):
    previous_policy: str = betterproto.string_field(1)
    current_policy: str = betterproto.string_field(2)
    accepted: bool = betterproto.bool_field(3)
    message: str = betterproto.string_field(4)


@dataclass(eq=False, repr=False)
class AdvanceTimeRequest(betterproto.Message):
    advance_ms: int = betterproto.int64_field(1)
    reason: str = betterproto.string_field(2)


@dataclass(eq=False, repr=False)
class AdvanceTimeResponse(betterproto.Message):
    accepted: bool = betterproto.bool_field(1)
    acknowledged_delta_ms: int = betterproto.int64_field(2)
    message: str = betterproto.string_field(3)


@dataclass(eq=False, repr=False)
class GetSimulatorStateRequest(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class SimBalanceEntry(betterproto.Message):
    asset: str = betterproto.string_field(1)
    total_qty: float = betterproto.double_field(2)
    avail_qty: float = betterproto.double_field(3)
    frozen_qty: float = betterproto.double_field(4)


@dataclass(eq=False, repr=False)
class SimPositionEntry(betterproto.Message):
    instrument_code: str = betterproto.string_field(1)
    long_short_type: int = betterproto.int32_field(2)
    total_qty: float = betterproto.double_field(3)
    avail_qty: float = betterproto.double_field(4)
    frozen_qty: float = betterproto.double_field(5)


@dataclass(eq=False, repr=False)
class GetSimulatorStateResponse(betterproto.Message):
    open_orders: List["SimOpenOrder"] = betterproto.message_field(1)
    balances: List["SimBalanceEntry"] = betterproto.message_field(2)
    positions: List["SimPositionEntry"] = betterproto.message_field(3)
    active_error_rules: List["InjectedErrorInfo"] = betterproto.message_field(4)
    current_match_policy: str = betterproto.string_field(5)
    matching_paused: bool = betterproto.bool_field(6)
    last_tick_ts: int = betterproto.int64_field(7)
    last_event_ts: int = betterproto.int64_field(8)


class GatewayServiceStub(betterproto.ServiceStub):
    async def place_order(
        self,
        send_order_request: "SendOrderRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "GatewayResponse":
        return await self._unary_unary(
            "/zk.gateway.v1.GatewayService/PlaceOrder",
            send_order_request,
            GatewayResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def batch_place_orders(
        self,
        batch_send_orders_request: "BatchSendOrdersRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "GatewayResponse":
        return await self._unary_unary(
            "/zk.gateway.v1.GatewayService/BatchPlaceOrders",
            batch_send_orders_request,
            GatewayResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def cancel_order(
        self,
        cancel_order_request: "CancelOrderRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "GatewayResponse":
        return await self._unary_unary(
            "/zk.gateway.v1.GatewayService/CancelOrder",
            cancel_order_request,
            GatewayResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def batch_cancel_orders(
        self,
        batch_cancel_orders_request: "BatchCancelOrdersRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "GatewayResponse":
        return await self._unary_unary(
            "/zk.gateway.v1.GatewayService/BatchCancelOrders",
            batch_cancel_orders_request,
            GatewayResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def query_account_balance(
        self,
        query_account_request: "QueryAccountRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "AccountResponse":
        return await self._unary_unary(
            "/zk.gateway.v1.GatewayService/QueryAccountBalance",
            query_account_request,
            AccountResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def query_position(
        self,
        query_position_request: "QueryPositionRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "PositionResponse":
        return await self._unary_unary(
            "/zk.gateway.v1.GatewayService/QueryPosition",
            query_position_request,
            PositionResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def query_order_details(
        self,
        query_order_detail_request: "QueryOrderDetailRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "OrderDetailResponse":
        return await self._unary_unary(
            "/zk.gateway.v1.GatewayService/QueryOrderDetails",
            query_order_detail_request,
            OrderDetailResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def query_open_orders(
        self,
        query_open_order_request: "QueryOpenOrderRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "OrderDetailResponse":
        return await self._unary_unary(
            "/zk.gateway.v1.GatewayService/QueryOpenOrders",
            query_open_order_request,
            OrderDetailResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def query_account_fees(
        self,
        query_fee_request: "QueryFeeRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "FeeResponse":
        return await self._unary_unary(
            "/zk.gateway.v1.GatewayService/QueryAccountFees",
            query_fee_request,
            FeeResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def query_order_trades(
        self,
        query_order_trades_request: "QueryOrderTradesRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "OrderTradesResponse":
        return await self._unary_unary(
            "/zk.gateway.v1.GatewayService/QueryOrderTrades",
            query_order_trades_request,
            OrderTradesResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def generic_rpc_call(
        self,
        generic_request: "GenericRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "GenericResponse":
        return await self._unary_unary(
            "/zk.gateway.v1.GatewayService/GenericRpcCall",
            generic_request,
            GenericResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def health_check(
        self,
        common_v1_dummy_request: "__common_v1__.DummyRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "__common_v1__.ServiceHealthResponse":
        return await self._unary_unary(
            "/zk.gateway.v1.GatewayService/HealthCheck",
            common_v1_dummy_request,
            __common_v1__.ServiceHealthResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )


class GatewaySimulatorAdminServiceStub(betterproto.ServiceStub):
    async def force_match(
        self,
        force_match_request: "ForceMatchRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "ForceMatchResponse":
        return await self._unary_unary(
            "/zk.gateway.v1.GatewaySimulatorAdminService/ForceMatch",
            force_match_request,
            ForceMatchResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def inject_error(
        self,
        inject_error_request: "InjectErrorRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "InjectErrorResponse":
        return await self._unary_unary(
            "/zk.gateway.v1.GatewaySimulatorAdminService/InjectError",
            inject_error_request,
            InjectErrorResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def list_injected_errors(
        self,
        list_injected_errors_request: "ListInjectedErrorsRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "ListInjectedErrorsResponse":
        return await self._unary_unary(
            "/zk.gateway.v1.GatewaySimulatorAdminService/ListInjectedErrors",
            list_injected_errors_request,
            ListInjectedErrorsResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def clear_injected_error(
        self,
        clear_injected_error_request: "ClearInjectedErrorRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "ClearInjectedErrorResponse":
        return await self._unary_unary(
            "/zk.gateway.v1.GatewaySimulatorAdminService/ClearInjectedError",
            clear_injected_error_request,
            ClearInjectedErrorResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def reset_simulator(
        self,
        reset_simulator_request: "ResetSimulatorRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "ResetSimulatorResponse":
        return await self._unary_unary(
            "/zk.gateway.v1.GatewaySimulatorAdminService/ResetSimulator",
            reset_simulator_request,
            ResetSimulatorResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def set_account_state(
        self,
        set_account_state_request: "SetAccountStateRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "SetAccountStateResponse":
        return await self._unary_unary(
            "/zk.gateway.v1.GatewaySimulatorAdminService/SetAccountState",
            set_account_state_request,
            SetAccountStateResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def submit_synthetic_tick(
        self,
        submit_synthetic_tick_request: "SubmitSyntheticTickRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "SubmitSyntheticTickResponse":
        return await self._unary_unary(
            "/zk.gateway.v1.GatewaySimulatorAdminService/SubmitSyntheticTick",
            submit_synthetic_tick_request,
            SubmitSyntheticTickResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def list_open_orders(
        self,
        list_open_orders_request: "ListOpenOrdersRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "ListOpenOrdersResponse":
        return await self._unary_unary(
            "/zk.gateway.v1.GatewaySimulatorAdminService/ListOpenOrders",
            list_open_orders_request,
            ListOpenOrdersResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def pause_matching(
        self,
        pause_matching_request: "PauseMatchingRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "MatchingStateResponse":
        return await self._unary_unary(
            "/zk.gateway.v1.GatewaySimulatorAdminService/PauseMatching",
            pause_matching_request,
            MatchingStateResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def resume_matching(
        self,
        resume_matching_request: "ResumeMatchingRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "MatchingStateResponse":
        return await self._unary_unary(
            "/zk.gateway.v1.GatewaySimulatorAdminService/ResumeMatching",
            resume_matching_request,
            MatchingStateResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def set_match_policy(
        self,
        set_match_policy_request: "SetMatchPolicyRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "SetMatchPolicyResponse":
        return await self._unary_unary(
            "/zk.gateway.v1.GatewaySimulatorAdminService/SetMatchPolicy",
            set_match_policy_request,
            SetMatchPolicyResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def advance_time(
        self,
        advance_time_request: "AdvanceTimeRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "AdvanceTimeResponse":
        return await self._unary_unary(
            "/zk.gateway.v1.GatewaySimulatorAdminService/AdvanceTime",
            advance_time_request,
            AdvanceTimeResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def get_simulator_state(
        self,
        get_simulator_state_request: "GetSimulatorStateRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "GetSimulatorStateResponse":
        return await self._unary_unary(
            "/zk.gateway.v1.GatewaySimulatorAdminService/GetSimulatorState",
            get_simulator_state_request,
            GetSimulatorStateResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )


class GatewayServiceBase(ServiceBase):

    async def place_order(
        self, send_order_request: "SendOrderRequest"
    ) -> "GatewayResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def batch_place_orders(
        self, batch_send_orders_request: "BatchSendOrdersRequest"
    ) -> "GatewayResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def cancel_order(
        self, cancel_order_request: "CancelOrderRequest"
    ) -> "GatewayResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def batch_cancel_orders(
        self, batch_cancel_orders_request: "BatchCancelOrdersRequest"
    ) -> "GatewayResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def query_account_balance(
        self, query_account_request: "QueryAccountRequest"
    ) -> "AccountResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def query_position(
        self, query_position_request: "QueryPositionRequest"
    ) -> "PositionResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def query_order_details(
        self, query_order_detail_request: "QueryOrderDetailRequest"
    ) -> "OrderDetailResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def query_open_orders(
        self, query_open_order_request: "QueryOpenOrderRequest"
    ) -> "OrderDetailResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def query_account_fees(
        self, query_fee_request: "QueryFeeRequest"
    ) -> "FeeResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def query_order_trades(
        self, query_order_trades_request: "QueryOrderTradesRequest"
    ) -> "OrderTradesResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def generic_rpc_call(
        self, generic_request: "GenericRequest"
    ) -> "GenericResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def health_check(
        self, common_v1_dummy_request: "__common_v1__.DummyRequest"
    ) -> "__common_v1__.ServiceHealthResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def __rpc_place_order(
        self, stream: "grpclib.server.Stream[SendOrderRequest, GatewayResponse]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.place_order(request)
        await stream.send_message(response)

    async def __rpc_batch_place_orders(
        self, stream: "grpclib.server.Stream[BatchSendOrdersRequest, GatewayResponse]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.batch_place_orders(request)
        await stream.send_message(response)

    async def __rpc_cancel_order(
        self, stream: "grpclib.server.Stream[CancelOrderRequest, GatewayResponse]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.cancel_order(request)
        await stream.send_message(response)

    async def __rpc_batch_cancel_orders(
        self, stream: "grpclib.server.Stream[BatchCancelOrdersRequest, GatewayResponse]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.batch_cancel_orders(request)
        await stream.send_message(response)

    async def __rpc_query_account_balance(
        self, stream: "grpclib.server.Stream[QueryAccountRequest, AccountResponse]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.query_account_balance(request)
        await stream.send_message(response)

    async def __rpc_query_position(
        self, stream: "grpclib.server.Stream[QueryPositionRequest, PositionResponse]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.query_position(request)
        await stream.send_message(response)

    async def __rpc_query_order_details(
        self,
        stream: "grpclib.server.Stream[QueryOrderDetailRequest, OrderDetailResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.query_order_details(request)
        await stream.send_message(response)

    async def __rpc_query_open_orders(
        self,
        stream: "grpclib.server.Stream[QueryOpenOrderRequest, OrderDetailResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.query_open_orders(request)
        await stream.send_message(response)

    async def __rpc_query_account_fees(
        self, stream: "grpclib.server.Stream[QueryFeeRequest, FeeResponse]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.query_account_fees(request)
        await stream.send_message(response)

    async def __rpc_query_order_trades(
        self,
        stream: "grpclib.server.Stream[QueryOrderTradesRequest, OrderTradesResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.query_order_trades(request)
        await stream.send_message(response)

    async def __rpc_generic_rpc_call(
        self, stream: "grpclib.server.Stream[GenericRequest, GenericResponse]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.generic_rpc_call(request)
        await stream.send_message(response)

    async def __rpc_health_check(
        self,
        stream: "grpclib.server.Stream[__common_v1__.DummyRequest, __common_v1__.ServiceHealthResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.health_check(request)
        await stream.send_message(response)

    def __mapping__(self) -> Dict[str, grpclib.const.Handler]:
        return {
            "/zk.gateway.v1.GatewayService/PlaceOrder": grpclib.const.Handler(
                self.__rpc_place_order,
                grpclib.const.Cardinality.UNARY_UNARY,
                SendOrderRequest,
                GatewayResponse,
            ),
            "/zk.gateway.v1.GatewayService/BatchPlaceOrders": grpclib.const.Handler(
                self.__rpc_batch_place_orders,
                grpclib.const.Cardinality.UNARY_UNARY,
                BatchSendOrdersRequest,
                GatewayResponse,
            ),
            "/zk.gateway.v1.GatewayService/CancelOrder": grpclib.const.Handler(
                self.__rpc_cancel_order,
                grpclib.const.Cardinality.UNARY_UNARY,
                CancelOrderRequest,
                GatewayResponse,
            ),
            "/zk.gateway.v1.GatewayService/BatchCancelOrders": grpclib.const.Handler(
                self.__rpc_batch_cancel_orders,
                grpclib.const.Cardinality.UNARY_UNARY,
                BatchCancelOrdersRequest,
                GatewayResponse,
            ),
            "/zk.gateway.v1.GatewayService/QueryAccountBalance": grpclib.const.Handler(
                self.__rpc_query_account_balance,
                grpclib.const.Cardinality.UNARY_UNARY,
                QueryAccountRequest,
                AccountResponse,
            ),
            "/zk.gateway.v1.GatewayService/QueryPosition": grpclib.const.Handler(
                self.__rpc_query_position,
                grpclib.const.Cardinality.UNARY_UNARY,
                QueryPositionRequest,
                PositionResponse,
            ),
            "/zk.gateway.v1.GatewayService/QueryOrderDetails": grpclib.const.Handler(
                self.__rpc_query_order_details,
                grpclib.const.Cardinality.UNARY_UNARY,
                QueryOrderDetailRequest,
                OrderDetailResponse,
            ),
            "/zk.gateway.v1.GatewayService/QueryOpenOrders": grpclib.const.Handler(
                self.__rpc_query_open_orders,
                grpclib.const.Cardinality.UNARY_UNARY,
                QueryOpenOrderRequest,
                OrderDetailResponse,
            ),
            "/zk.gateway.v1.GatewayService/QueryAccountFees": grpclib.const.Handler(
                self.__rpc_query_account_fees,
                grpclib.const.Cardinality.UNARY_UNARY,
                QueryFeeRequest,
                FeeResponse,
            ),
            "/zk.gateway.v1.GatewayService/QueryOrderTrades": grpclib.const.Handler(
                self.__rpc_query_order_trades,
                grpclib.const.Cardinality.UNARY_UNARY,
                QueryOrderTradesRequest,
                OrderTradesResponse,
            ),
            "/zk.gateway.v1.GatewayService/GenericRpcCall": grpclib.const.Handler(
                self.__rpc_generic_rpc_call,
                grpclib.const.Cardinality.UNARY_UNARY,
                GenericRequest,
                GenericResponse,
            ),
            "/zk.gateway.v1.GatewayService/HealthCheck": grpclib.const.Handler(
                self.__rpc_health_check,
                grpclib.const.Cardinality.UNARY_UNARY,
                __common_v1__.DummyRequest,
                __common_v1__.ServiceHealthResponse,
            ),
        }


class GatewaySimulatorAdminServiceBase(ServiceBase):

    async def force_match(
        self, force_match_request: "ForceMatchRequest"
    ) -> "ForceMatchResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def inject_error(
        self, inject_error_request: "InjectErrorRequest"
    ) -> "InjectErrorResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def list_injected_errors(
        self, list_injected_errors_request: "ListInjectedErrorsRequest"
    ) -> "ListInjectedErrorsResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def clear_injected_error(
        self, clear_injected_error_request: "ClearInjectedErrorRequest"
    ) -> "ClearInjectedErrorResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def reset_simulator(
        self, reset_simulator_request: "ResetSimulatorRequest"
    ) -> "ResetSimulatorResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def set_account_state(
        self, set_account_state_request: "SetAccountStateRequest"
    ) -> "SetAccountStateResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def submit_synthetic_tick(
        self, submit_synthetic_tick_request: "SubmitSyntheticTickRequest"
    ) -> "SubmitSyntheticTickResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def list_open_orders(
        self, list_open_orders_request: "ListOpenOrdersRequest"
    ) -> "ListOpenOrdersResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def pause_matching(
        self, pause_matching_request: "PauseMatchingRequest"
    ) -> "MatchingStateResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def resume_matching(
        self, resume_matching_request: "ResumeMatchingRequest"
    ) -> "MatchingStateResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def set_match_policy(
        self, set_match_policy_request: "SetMatchPolicyRequest"
    ) -> "SetMatchPolicyResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def advance_time(
        self, advance_time_request: "AdvanceTimeRequest"
    ) -> "AdvanceTimeResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def get_simulator_state(
        self, get_simulator_state_request: "GetSimulatorStateRequest"
    ) -> "GetSimulatorStateResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def __rpc_force_match(
        self, stream: "grpclib.server.Stream[ForceMatchRequest, ForceMatchResponse]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.force_match(request)
        await stream.send_message(response)

    async def __rpc_inject_error(
        self, stream: "grpclib.server.Stream[InjectErrorRequest, InjectErrorResponse]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.inject_error(request)
        await stream.send_message(response)

    async def __rpc_list_injected_errors(
        self,
        stream: "grpclib.server.Stream[ListInjectedErrorsRequest, ListInjectedErrorsResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.list_injected_errors(request)
        await stream.send_message(response)

    async def __rpc_clear_injected_error(
        self,
        stream: "grpclib.server.Stream[ClearInjectedErrorRequest, ClearInjectedErrorResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.clear_injected_error(request)
        await stream.send_message(response)

    async def __rpc_reset_simulator(
        self,
        stream: "grpclib.server.Stream[ResetSimulatorRequest, ResetSimulatorResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.reset_simulator(request)
        await stream.send_message(response)

    async def __rpc_set_account_state(
        self,
        stream: "grpclib.server.Stream[SetAccountStateRequest, SetAccountStateResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.set_account_state(request)
        await stream.send_message(response)

    async def __rpc_submit_synthetic_tick(
        self,
        stream: "grpclib.server.Stream[SubmitSyntheticTickRequest, SubmitSyntheticTickResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.submit_synthetic_tick(request)
        await stream.send_message(response)

    async def __rpc_list_open_orders(
        self,
        stream: "grpclib.server.Stream[ListOpenOrdersRequest, ListOpenOrdersResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.list_open_orders(request)
        await stream.send_message(response)

    async def __rpc_pause_matching(
        self,
        stream: "grpclib.server.Stream[PauseMatchingRequest, MatchingStateResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.pause_matching(request)
        await stream.send_message(response)

    async def __rpc_resume_matching(
        self,
        stream: "grpclib.server.Stream[ResumeMatchingRequest, MatchingStateResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.resume_matching(request)
        await stream.send_message(response)

    async def __rpc_set_match_policy(
        self,
        stream: "grpclib.server.Stream[SetMatchPolicyRequest, SetMatchPolicyResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.set_match_policy(request)
        await stream.send_message(response)

    async def __rpc_advance_time(
        self, stream: "grpclib.server.Stream[AdvanceTimeRequest, AdvanceTimeResponse]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.advance_time(request)
        await stream.send_message(response)

    async def __rpc_get_simulator_state(
        self,
        stream: "grpclib.server.Stream[GetSimulatorStateRequest, GetSimulatorStateResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.get_simulator_state(request)
        await stream.send_message(response)

    def __mapping__(self) -> Dict[str, grpclib.const.Handler]:
        return {
            "/zk.gateway.v1.GatewaySimulatorAdminService/ForceMatch": grpclib.const.Handler(
                self.__rpc_force_match,
                grpclib.const.Cardinality.UNARY_UNARY,
                ForceMatchRequest,
                ForceMatchResponse,
            ),
            "/zk.gateway.v1.GatewaySimulatorAdminService/InjectError": grpclib.const.Handler(
                self.__rpc_inject_error,
                grpclib.const.Cardinality.UNARY_UNARY,
                InjectErrorRequest,
                InjectErrorResponse,
            ),
            "/zk.gateway.v1.GatewaySimulatorAdminService/ListInjectedErrors": grpclib.const.Handler(
                self.__rpc_list_injected_errors,
                grpclib.const.Cardinality.UNARY_UNARY,
                ListInjectedErrorsRequest,
                ListInjectedErrorsResponse,
            ),
            "/zk.gateway.v1.GatewaySimulatorAdminService/ClearInjectedError": grpclib.const.Handler(
                self.__rpc_clear_injected_error,
                grpclib.const.Cardinality.UNARY_UNARY,
                ClearInjectedErrorRequest,
                ClearInjectedErrorResponse,
            ),
            "/zk.gateway.v1.GatewaySimulatorAdminService/ResetSimulator": grpclib.const.Handler(
                self.__rpc_reset_simulator,
                grpclib.const.Cardinality.UNARY_UNARY,
                ResetSimulatorRequest,
                ResetSimulatorResponse,
            ),
            "/zk.gateway.v1.GatewaySimulatorAdminService/SetAccountState": grpclib.const.Handler(
                self.__rpc_set_account_state,
                grpclib.const.Cardinality.UNARY_UNARY,
                SetAccountStateRequest,
                SetAccountStateResponse,
            ),
            "/zk.gateway.v1.GatewaySimulatorAdminService/SubmitSyntheticTick": grpclib.const.Handler(
                self.__rpc_submit_synthetic_tick,
                grpclib.const.Cardinality.UNARY_UNARY,
                SubmitSyntheticTickRequest,
                SubmitSyntheticTickResponse,
            ),
            "/zk.gateway.v1.GatewaySimulatorAdminService/ListOpenOrders": grpclib.const.Handler(
                self.__rpc_list_open_orders,
                grpclib.const.Cardinality.UNARY_UNARY,
                ListOpenOrdersRequest,
                ListOpenOrdersResponse,
            ),
            "/zk.gateway.v1.GatewaySimulatorAdminService/PauseMatching": grpclib.const.Handler(
                self.__rpc_pause_matching,
                grpclib.const.Cardinality.UNARY_UNARY,
                PauseMatchingRequest,
                MatchingStateResponse,
            ),
            "/zk.gateway.v1.GatewaySimulatorAdminService/ResumeMatching": grpclib.const.Handler(
                self.__rpc_resume_matching,
                grpclib.const.Cardinality.UNARY_UNARY,
                ResumeMatchingRequest,
                MatchingStateResponse,
            ),
            "/zk.gateway.v1.GatewaySimulatorAdminService/SetMatchPolicy": grpclib.const.Handler(
                self.__rpc_set_match_policy,
                grpclib.const.Cardinality.UNARY_UNARY,
                SetMatchPolicyRequest,
                SetMatchPolicyResponse,
            ),
            "/zk.gateway.v1.GatewaySimulatorAdminService/AdvanceTime": grpclib.const.Handler(
                self.__rpc_advance_time,
                grpclib.const.Cardinality.UNARY_UNARY,
                AdvanceTimeRequest,
                AdvanceTimeResponse,
            ),
            "/zk.gateway.v1.GatewaySimulatorAdminService/GetSimulatorState": grpclib.const.Handler(
                self.__rpc_get_simulator_state,
                grpclib.const.Cardinality.UNARY_UNARY,
                GetSimulatorStateRequest,
                GetSimulatorStateResponse,
            ),
        }
# legacy-betterproto-compat-start
# Compatibility aliases for older BetterProto output.
type.__setattr__(FillMode.__class__, "FILL_MODE_UNSPECIFIED", FillMode.UNSPECIFIED)
FillMode._member_map_["FILL_MODE_UNSPECIFIED"] = FillMode.UNSPECIFIED
type.__setattr__(FillMode.__class__, "FILL_MODE_FULL", FillMode.FULL)
FillMode._member_map_["FILL_MODE_FULL"] = FillMode.FULL
type.__setattr__(FillMode.__class__, "FILL_MODE_PARTIAL", FillMode.PARTIAL)
FillMode._member_map_["FILL_MODE_PARTIAL"] = FillMode.PARTIAL
type.__setattr__(ErrorScope.__class__, "ERROR_SCOPE_UNSPECIFIED", ErrorScope.UNSPECIFIED)
ErrorScope._member_map_["ERROR_SCOPE_UNSPECIFIED"] = ErrorScope.UNSPECIFIED
type.__setattr__(ErrorScope.__class__, "ERROR_SCOPE_PLACE_ORDER", ErrorScope.PLACE_ORDER)
ErrorScope._member_map_["ERROR_SCOPE_PLACE_ORDER"] = ErrorScope.PLACE_ORDER
type.__setattr__(ErrorScope.__class__, "ERROR_SCOPE_CANCEL_ORDER", ErrorScope.CANCEL_ORDER)
ErrorScope._member_map_["ERROR_SCOPE_CANCEL_ORDER"] = ErrorScope.CANCEL_ORDER
type.__setattr__(ErrorScope.__class__, "ERROR_SCOPE_QUERY_ACCOUNT_BALANCE", ErrorScope.QUERY_ACCOUNT_BALANCE)
ErrorScope._member_map_["ERROR_SCOPE_QUERY_ACCOUNT_BALANCE"] = ErrorScope.QUERY_ACCOUNT_BALANCE
type.__setattr__(ErrorScope.__class__, "ERROR_SCOPE_QUERY_ORDER_DETAIL", ErrorScope.QUERY_ORDER_DETAIL)
ErrorScope._member_map_["ERROR_SCOPE_QUERY_ORDER_DETAIL"] = ErrorScope.QUERY_ORDER_DETAIL
type.__setattr__(TriggerPolicy.__class__, "TRIGGER_POLICY_UNSPECIFIED", TriggerPolicy.UNSPECIFIED)
TriggerPolicy._member_map_["TRIGGER_POLICY_UNSPECIFIED"] = TriggerPolicy.UNSPECIFIED
type.__setattr__(TriggerPolicy.__class__, "TRIGGER_POLICY_ONCE", TriggerPolicy.ONCE)
TriggerPolicy._member_map_["TRIGGER_POLICY_ONCE"] = TriggerPolicy.ONCE
type.__setattr__(TriggerPolicy.__class__, "TRIGGER_POLICY_TIMES", TriggerPolicy.TIMES)
TriggerPolicy._member_map_["TRIGGER_POLICY_TIMES"] = TriggerPolicy.TIMES
type.__setattr__(TriggerPolicy.__class__, "TRIGGER_POLICY_UNTIL_CLEARED", TriggerPolicy.UNTIL_CLEARED)
TriggerPolicy._member_map_["TRIGGER_POLICY_UNTIL_CLEARED"] = TriggerPolicy.UNTIL_CLEARED
type.__setattr__(MutationMode.__class__, "MUTATION_MODE_UNSPECIFIED", MutationMode.UNSPECIFIED)
MutationMode._member_map_["MUTATION_MODE_UNSPECIFIED"] = MutationMode.UNSPECIFIED
type.__setattr__(MutationMode.__class__, "MUTATION_MODE_UPSERT", MutationMode.UPSERT)
MutationMode._member_map_["MUTATION_MODE_UPSERT"] = MutationMode.UPSERT
type.__setattr__(MutationMode.__class__, "MUTATION_MODE_REMOVE", MutationMode.REMOVE)
MutationMode._member_map_["MUTATION_MODE_REMOVE"] = MutationMode.REMOVE
# legacy-betterproto-compat-end
