# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: oms.proto
# plugin: python-betterproto
# This file has been @generated

from dataclasses import dataclass
from typing import List

import betterproto

from .. import common as _common__


class OrderStatus(betterproto.Enum):
    UNSPECIFIED = 0
    PENDING = 1
    BOOKED = 2
    PARTIALLY_FILLED = 3
    FILLED = 4
    CANCELLED = 5
    REJECTED = 6


class ExecType(betterproto.Enum):
    UNSPECIFIED = 0
    CANCEL = 1
    PLACING_ORDER = 2


@dataclass(eq=False, repr=False)
class Account(betterproto.Message):
    account_id: int = betterproto.int64_field(1)
    account_code: str = betterproto.string_field(2)
    exch_account_code: str = betterproto.string_field(3)
    per_account_setting: "_common__.ExtraData" = betterproto.message_field(4)


@dataclass(eq=False, repr=False)
class OrderRequest(betterproto.Message):
    order_id: int = betterproto.int64_field(1)
    account_id: int = betterproto.int64_field(2)
    instrument_code: str = betterproto.string_field(3)
    buy_sell_type: "_common__.BuySellType" = betterproto.enum_field(4)
    open_close_type: "_common__.OpenCloseType" = betterproto.enum_field(5)
    order_type: "_common__.BasicOrderType" = betterproto.enum_field(6)
    time_inforce_type: "_common__.TimeInForceType" = betterproto.enum_field(13)
    extra_order_tags: List["_common__.ExtraOrderTagType"] = betterproto.enum_field(14)
    price: float = betterproto.double_field(7)
    qty: float = betterproto.double_field(8)
    source_id: str = betterproto.string_field(9)
    timestamp: int = betterproto.int64_field(10)
    leverage: float = betterproto.double_field(11)
    extra_properties: "_common__.ExtraData" = betterproto.message_field(12)


@dataclass(eq=False, repr=False)
class OrderCancelRequest(betterproto.Message):
    order_id: int = betterproto.int64_field(1)
    exch_order_ref: str = betterproto.string_field(2)
    extra_info_required: "_common__.ExtraData" = betterproto.message_field(3)
    source_id: str = betterproto.string_field(7)
    timestamp: int = betterproto.int64_field(8)


@dataclass(eq=False, repr=False)
class Order(betterproto.Message):
    order_id: int = betterproto.int64_field(1)
    exch_order_ref: str = betterproto.string_field(2)
    gw_key: str = betterproto.string_field(16)
    account_id: int = betterproto.int64_field(18)
    snapshot_version: int = betterproto.int32_field(3)
    """
    greater version number means more up-to-date snapshot
     any order processor should discard order snapshot 
     with smaller version than currently held version
    """

    order_status: "OrderStatus" = betterproto.enum_field(15)
    instrument: str = betterproto.string_field(4)
    instrument_exch: str = betterproto.string_field(17)
    buy_sell_type: "_common__.BuySellType" = betterproto.enum_field(5)
    open_close_type: "_common__.OpenCloseType" = betterproto.enum_field(6)
    price: float = betterproto.double_field(7)
    qty: float = betterproto.double_field(8)
    filled_qty: float = betterproto.double_field(9)
    filled_avg_price: float = betterproto.double_field(10)
    error_msg: str = betterproto.string_field(11)
    source_id: str = betterproto.string_field(12)
    created_at: int = betterproto.int64_field(13)
    updated_at: int = betterproto.int64_field(14)


@dataclass(eq=False, repr=False)
class Fee(betterproto.Message):
    order_id: int = betterproto.int64_field(1)
    fee_symbol: str = betterproto.string_field(2)
    fee_amount: float = betterproto.double_field(3)
    fee_type: "_common__.FeeType" = betterproto.enum_field(4)
    fee_ts: int = betterproto.int64_field(5)


@dataclass(eq=False, repr=False)
class Trade(betterproto.Message):
    order_id: int = betterproto.int64_field(1)
    ext_order_ref: str = betterproto.string_field(2)
    ext_trade_id: str = betterproto.string_field(3)
    filled_qty: float = betterproto.double_field(4)
    filled_price: float = betterproto.double_field(5)
    filled_ts: int = betterproto.int64_field(6)
    buy_sell_type: "_common__.BuySellType" = betterproto.enum_field(7)
    fill_type: "_common__.FillType" = betterproto.enum_field(10)
    instrument: str = betterproto.string_field(8)
    account_id: int = betterproto.int64_field(9)
    fees: List["Fee"] = betterproto.message_field(11)
    exch_pnl: float = betterproto.double_field(12)


@dataclass(eq=False, repr=False)
class ExecMessage(betterproto.Message):
    """
    exec message is used to deliver operation result (by default failure only)
     such as: order cancel (failure); order replace (failure) etc.
    """

    order_id: int = betterproto.int64_field(1)
    exch_order_ref: str = betterproto.string_field(2)
    timestamp: int = betterproto.int64_field(3)
    exec_type: "ExecType" = betterproto.enum_field(4)
    exec_success: bool = betterproto.bool_field(5)
    error_msg: str = betterproto.string_field(6)
    rejection_info: "_common__.Rejection" = betterproto.message_field(7)


@dataclass(eq=False, repr=False)
class Position(betterproto.Message):
    account_id: int = betterproto.int64_field(1)
    instrument_code: str = betterproto.string_field(2)
    long_short_type: "_common__.LongShortType" = betterproto.enum_field(3)
    instrument_type: "_common__.InstrumentType" = betterproto.enum_field(4)
    total_qty: float = betterproto.double_field(5)
    frozen_qty: float = betterproto.double_field(6)
    avail_qty: float = betterproto.double_field(7)
    contract_size: float = betterproto.double_field(12)
    contract_size_adjusted: bool = betterproto.bool_field(14)
    margin_pos_info: "_common__.MarginPositionInfo" = betterproto.message_field(13)
    sync_timestamp: int = betterproto.int64_field(8)
    update_timestamp: int = betterproto.int64_field(9)
    is_from_exch: bool = betterproto.bool_field(10)
    exch_data_raw: str = betterproto.string_field(11)


@dataclass(eq=False, repr=False)
class OrderUpdateEvent(betterproto.Message):
    order_id: int = betterproto.int64_field(1)
    account_id: int = betterproto.int64_field(2)
    order_snapshot: "Order" = betterproto.message_field(3)
    order_inferred_trade: "Trade" = betterproto.message_field(9)
    last_trade: "Trade" = betterproto.message_field(4)
    last_fee: "Fee" = betterproto.message_field(5)
    exec_message: "ExecMessage" = betterproto.message_field(6)
    timestamp: int = betterproto.int64_field(7)
    order_source_id: str = betterproto.string_field(8)


@dataclass(eq=False, repr=False)
class PositionUpdateEvent(betterproto.Message):
    account_id: int = betterproto.int64_field(1)
    position_snapshots: List["Position"] = betterproto.message_field(2)
    timestamp: int = betterproto.int64_field(4)


@dataclass(eq=False, repr=False)
class OmsSystemEvent(betterproto.Message):
    timestamp: int = betterproto.int64_field(1)
    oms_id: str = betterproto.string_field(2)
    event_type: str = betterproto.string_field(3)
    event_message: str = betterproto.string_field(4)
# legacy-betterproto-compat-start
# Compatibility aliases for older BetterProto output.
OMSSystemEvent = OmsSystemEvent
type.__setattr__(OrderStatus.__class__, "ORDER_STATUS_UNSPECIFIED", OrderStatus.UNSPECIFIED)
OrderStatus._member_map_["ORDER_STATUS_UNSPECIFIED"] = OrderStatus.UNSPECIFIED
type.__setattr__(OrderStatus.__class__, "ORDER_STATUS_PENDING", OrderStatus.PENDING)
OrderStatus._member_map_["ORDER_STATUS_PENDING"] = OrderStatus.PENDING
type.__setattr__(OrderStatus.__class__, "ORDER_STATUS_BOOKED", OrderStatus.BOOKED)
OrderStatus._member_map_["ORDER_STATUS_BOOKED"] = OrderStatus.BOOKED
type.__setattr__(OrderStatus.__class__, "ORDER_STATUS_PARTIALLY_FILLED", OrderStatus.PARTIALLY_FILLED)
OrderStatus._member_map_["ORDER_STATUS_PARTIALLY_FILLED"] = OrderStatus.PARTIALLY_FILLED
type.__setattr__(OrderStatus.__class__, "ORDER_STATUS_FILLED", OrderStatus.FILLED)
OrderStatus._member_map_["ORDER_STATUS_FILLED"] = OrderStatus.FILLED
type.__setattr__(OrderStatus.__class__, "ORDER_STATUS_CANCELLED", OrderStatus.CANCELLED)
OrderStatus._member_map_["ORDER_STATUS_CANCELLED"] = OrderStatus.CANCELLED
type.__setattr__(OrderStatus.__class__, "ORDER_STATUS_REJECTED", OrderStatus.REJECTED)
OrderStatus._member_map_["ORDER_STATUS_REJECTED"] = OrderStatus.REJECTED
type.__setattr__(ExecType.__class__, "EXEC_TYPE_UNSPECIFIED", ExecType.UNSPECIFIED)
ExecType._member_map_["EXEC_TYPE_UNSPECIFIED"] = ExecType.UNSPECIFIED
type.__setattr__(ExecType.__class__, "EXEC_TYPE_CANCEL", ExecType.CANCEL)
ExecType._member_map_["EXEC_TYPE_CANCEL"] = ExecType.CANCEL
type.__setattr__(ExecType.__class__, "EXEC_TYPE_PLACING_ORDER", ExecType.PLACING_ORDER)
ExecType._member_map_["EXEC_TYPE_PLACING_ORDER"] = ExecType.PLACING_ORDER
# legacy-betterproto-compat-end
