# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: zk/engine/v1/engine_service.proto
# plugin: python-betterproto
# This file has been @generated

from dataclasses import dataclass
from typing import (
    TYPE_CHECKING,
    Dict,
    Optional,
)

import betterproto
import grpclib
from betterproto.grpc.grpclib_server import ServiceBase

from ...common import v1 as __common_v1__

if TYPE_CHECKING:
    import grpclib.server
    from betterproto.grpc.grpclib_client import MetadataLike
    from grpclib.metadata import Deadline


@dataclass(eq=False, repr=False)
class StartEngineRequest(betterproto.Message):
    instance_id: str = betterproto.string_field(1)
    strategy_id: str = betterproto.string_field(2)
    execution_id: str = betterproto.string_field(3)
    config_json: str = betterproto.string_field(4)
    audit_meta: "__common_v1__.AuditMeta" = betterproto.message_field(5)


@dataclass(eq=False, repr=False)
class StopEngineRequest(betterproto.Message):
    instance_id: str = betterproto.string_field(1)
    execution_id: str = betterproto.string_field(2)
    reason: str = betterproto.string_field(3)
    audit_meta: "__common_v1__.AuditMeta" = betterproto.message_field(4)


@dataclass(eq=False, repr=False)
class PauseEngineRequest(betterproto.Message):
    instance_id: str = betterproto.string_field(1)
    execution_id: str = betterproto.string_field(2)
    audit_meta: "__common_v1__.AuditMeta" = betterproto.message_field(3)


@dataclass(eq=False, repr=False)
class ResumeEngineRequest(betterproto.Message):
    instance_id: str = betterproto.string_field(1)
    execution_id: str = betterproto.string_field(2)
    audit_meta: "__common_v1__.AuditMeta" = betterproto.message_field(3)


@dataclass(eq=False, repr=False)
class EngineStatusRequest(betterproto.Message):
    instance_id: str = betterproto.string_field(1)


@dataclass(eq=False, repr=False)
class EngineStatusResponse(betterproto.Message):
    instance_id: str = betterproto.string_field(1)
    execution_id: str = betterproto.string_field(2)
    state: str = betterproto.string_field(3)
    detail: str = betterproto.string_field(4)
    uptime_ms: int = betterproto.int64_field(5)


class EngineServiceStub(betterproto.ServiceStub):
    async def start(
        self,
        start_engine_request: "StartEngineRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "__common_v1__.CommandAck":
        return await self._unary_unary(
            "/zk.engine.v1.EngineService/Start",
            start_engine_request,
            __common_v1__.CommandAck,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def stop(
        self,
        stop_engine_request: "StopEngineRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "__common_v1__.CommandAck":
        return await self._unary_unary(
            "/zk.engine.v1.EngineService/Stop",
            stop_engine_request,
            __common_v1__.CommandAck,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def pause(
        self,
        pause_engine_request: "PauseEngineRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "__common_v1__.CommandAck":
        return await self._unary_unary(
            "/zk.engine.v1.EngineService/Pause",
            pause_engine_request,
            __common_v1__.CommandAck,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def resume(
        self,
        resume_engine_request: "ResumeEngineRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "__common_v1__.CommandAck":
        return await self._unary_unary(
            "/zk.engine.v1.EngineService/Resume",
            resume_engine_request,
            __common_v1__.CommandAck,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def get_status(
        self,
        engine_status_request: "EngineStatusRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "EngineStatusResponse":
        return await self._unary_unary(
            "/zk.engine.v1.EngineService/GetStatus",
            engine_status_request,
            EngineStatusResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def health_check(
        self,
        common_v1_dummy_request: "__common_v1__.DummyRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "__common_v1__.ServiceHealthResponse":
        return await self._unary_unary(
            "/zk.engine.v1.EngineService/HealthCheck",
            common_v1_dummy_request,
            __common_v1__.ServiceHealthResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )


class EngineServiceBase(ServiceBase):

    async def start(
        self, start_engine_request: "StartEngineRequest"
    ) -> "__common_v1__.CommandAck":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def stop(
        self, stop_engine_request: "StopEngineRequest"
    ) -> "__common_v1__.CommandAck":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def pause(
        self, pause_engine_request: "PauseEngineRequest"
    ) -> "__common_v1__.CommandAck":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def resume(
        self, resume_engine_request: "ResumeEngineRequest"
    ) -> "__common_v1__.CommandAck":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def get_status(
        self, engine_status_request: "EngineStatusRequest"
    ) -> "EngineStatusResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def health_check(
        self, common_v1_dummy_request: "__common_v1__.DummyRequest"
    ) -> "__common_v1__.ServiceHealthResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def __rpc_start(
        self,
        stream: "grpclib.server.Stream[StartEngineRequest, __common_v1__.CommandAck]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.start(request)
        await stream.send_message(response)

    async def __rpc_stop(
        self,
        stream: "grpclib.server.Stream[StopEngineRequest, __common_v1__.CommandAck]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.stop(request)
        await stream.send_message(response)

    async def __rpc_pause(
        self,
        stream: "grpclib.server.Stream[PauseEngineRequest, __common_v1__.CommandAck]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.pause(request)
        await stream.send_message(response)

    async def __rpc_resume(
        self,
        stream: "grpclib.server.Stream[ResumeEngineRequest, __common_v1__.CommandAck]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.resume(request)
        await stream.send_message(response)

    async def __rpc_get_status(
        self, stream: "grpclib.server.Stream[EngineStatusRequest, EngineStatusResponse]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.get_status(request)
        await stream.send_message(response)

    async def __rpc_health_check(
        self,
        stream: "grpclib.server.Stream[__common_v1__.DummyRequest, __common_v1__.ServiceHealthResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.health_check(request)
        await stream.send_message(response)

    def __mapping__(self) -> Dict[str, grpclib.const.Handler]:
        return {
            "/zk.engine.v1.EngineService/Start": grpclib.const.Handler(
                self.__rpc_start,
                grpclib.const.Cardinality.UNARY_UNARY,
                StartEngineRequest,
                __common_v1__.CommandAck,
            ),
            "/zk.engine.v1.EngineService/Stop": grpclib.const.Handler(
                self.__rpc_stop,
                grpclib.const.Cardinality.UNARY_UNARY,
                StopEngineRequest,
                __common_v1__.CommandAck,
            ),
            "/zk.engine.v1.EngineService/Pause": grpclib.const.Handler(
                self.__rpc_pause,
                grpclib.const.Cardinality.UNARY_UNARY,
                PauseEngineRequest,
                __common_v1__.CommandAck,
            ),
            "/zk.engine.v1.EngineService/Resume": grpclib.const.Handler(
                self.__rpc_resume,
                grpclib.const.Cardinality.UNARY_UNARY,
                ResumeEngineRequest,
                __common_v1__.CommandAck,
            ),
            "/zk.engine.v1.EngineService/GetStatus": grpclib.const.Handler(
                self.__rpc_get_status,
                grpclib.const.Cardinality.UNARY_UNARY,
                EngineStatusRequest,
                EngineStatusResponse,
            ),
            "/zk.engine.v1.EngineService/HealthCheck": grpclib.const.Handler(
                self.__rpc_health_check,
                grpclib.const.Cardinality.UNARY_UNARY,
                __common_v1__.DummyRequest,
                __common_v1__.ServiceHealthResponse,
            ),
        }
