// @generated
// This file is @generated by prost-build.
// ===== Messages (from exch-gateway.proto, field numbers preserved) =====

#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OrderInfo {
    #[prost(string, tag="1")]
    pub exch_order_ref: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub client_order_id: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub instrument: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub exch_account_id: ::prost::alloc::string::String,
    #[prost(enumeration="super::super::common::v1::BuySellType", tag="5")]
    pub buy_sell_type: i32,
    #[prost(double, tag="6")]
    pub place_qty: f64,
    #[prost(double, tag="7")]
    pub place_price: f64,
}
/// deprecated; use zk.common.v1.Rejection instead
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ExchErrorInfo {
    #[prost(int32, tag="1")]
    pub error_code: i32,
    #[prost(string, tag="2")]
    pub error_message: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OrderReport {
    #[prost(string, tag="1")]
    pub exch_order_ref: ::prost::alloc::string::String,
    #[prost(int64, tag="2")]
    pub order_id: i64,
    #[prost(string, tag="3")]
    pub exchange: ::prost::alloc::string::String,
    #[prost(message, repeated, tag="4")]
    pub order_report_entries: ::prost::alloc::vec::Vec<OrderReportEntry>,
    #[prost(int64, tag="5")]
    pub account_id: i64,
    #[prost(int64, tag="6")]
    pub update_timestamp: i64,
    #[prost(string, tag="7")]
    pub extra_order_id: ::prost::alloc::string::String,
    #[prost(enumeration="OrderSourceType", tag="8")]
    pub order_source_type: i32,
    /// local_ns() at GW gRPC handler entry; 0 if not set
    #[prost(int64, tag="9")]
    pub gw_received_at_ns: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OrderReportEntry {
    #[prost(enumeration="OrderReportType", tag="1")]
    pub report_type: i32,
    #[prost(oneof="order_report_entry::Report", tags="7, 8, 9, 10, 11")]
    pub report: ::core::option::Option<order_report_entry::Report>,
}
/// Nested message and enum types in `OrderReportEntry`.
pub mod order_report_entry {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Report {
        #[prost(message, tag="7")]
        TradeReport(super::TradeReport),
        #[prost(message, tag="8")]
        OrderStateReport(super::OrderStateReport),
        #[prost(message, tag="9")]
        OrderIdLinkageReport(super::OrderIdLinkageReport),
        #[prost(message, tag="10")]
        FeeReport(super::FeeReport),
        #[prost(message, tag="11")]
        ExecReport(super::ExecReport),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct OrderIdLinkageReport {
    #[prost(string, tag="1")]
    pub exch_order_ref: ::prost::alloc::string::String,
    #[prost(int64, tag="2")]
    pub order_id: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OrderStateReport {
    #[prost(enumeration="ExchangeOrderStatus", tag="1")]
    pub exch_order_status: i32,
    #[prost(double, tag="2")]
    pub filled_qty: f64,
    #[prost(double, tag="3")]
    pub unfilled_qty: f64,
    #[prost(double, tag="4")]
    pub avg_price: f64,
    #[prost(message, optional, tag="6")]
    pub order_info: ::core::option::Option<OrderInfo>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TradeReport {
    #[prost(string, tag="1")]
    pub exch_trade_id: ::prost::alloc::string::String,
    #[prost(double, tag="2")]
    pub filled_qty: f64,
    #[prost(double, tag="3")]
    pub filled_price: f64,
    #[prost(enumeration="super::super::common::v1::FillType", tag="4")]
    pub fill_type: i32,
    #[prost(int64, tag="5")]
    pub filled_ts: i64,
    #[prost(double, tag="6")]
    pub exch_pnl: f64,
    #[prost(message, optional, tag="7")]
    pub order_info: ::core::option::Option<OrderInfo>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FeeReport {
    #[prost(enumeration="FeeUnitType", tag="1")]
    pub fee_unit_type: i32,
    #[prost(double, tag="2")]
    pub fee_qty: f64,
    #[prost(string, tag="3")]
    pub fee_symbol: ::prost::alloc::string::String,
    #[prost(enumeration="super::super::common::v1::FeeType", tag="4")]
    pub fee_type: i32,
    #[prost(int64, tag="5")]
    pub fee_ts: i64,
    #[prost(string, tag="6")]
    pub inst_symbol: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ExecReport {
    #[prost(string, tag="1")]
    pub exec_id: ::prost::alloc::string::String,
    #[prost(enumeration="ExchExecType", tag="2")]
    pub exec_type: i32,
    #[prost(string, tag="3")]
    pub exec_message: ::prost::alloc::string::String,
    /// deprecated
    #[prost(message, optional, tag="4")]
    pub error_info: ::core::option::Option<ExchErrorInfo>,
    #[prost(message, optional, tag="5")]
    pub rejection_info: ::core::option::Option<super::super::common::v1::Rejection>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PositionReport {
    #[prost(string, tag="1")]
    pub instrument_code: ::prost::alloc::string::String,
    #[prost(enumeration="super::super::common::v1::InstrumentType", tag="2")]
    pub instrument_type: i32,
    #[prost(enumeration="super::super::common::v1::LongShortType", tag="3")]
    pub long_short_type: i32,
    #[prost(string, tag="4")]
    pub exch_account_code: ::prost::alloc::string::String,
    #[prost(double, tag="5")]
    pub qty: f64,
    #[prost(double, tag="6")]
    pub avail_qty: f64,
    #[prost(double, tag="7")]
    pub value: f64,
    #[prost(int64, tag="13")]
    pub update_timestamp: i64,
    #[prost(string, tag="14")]
    pub message_raw: ::prost::alloc::string::String,
    #[prost(int64, tag="15")]
    pub account_id: i64,
    #[prost(message, optional, tag="22")]
    pub margin_pos_info: ::core::option::Option<super::super::common::v1::MarginPositionInfo>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BalanceUpdate {
    #[prost(message, repeated, tag="1")]
    pub balances: ::prost::alloc::vec::Vec<PositionReport>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GatewaySystemEvent {
    #[prost(string, tag="1")]
    pub gw_name: ::prost::alloc::string::String,
    #[prost(enumeration="GatewayEventType", tag="2")]
    pub event_type: i32,
    #[prost(string, tag="3")]
    pub service_endpoint: ::prost::alloc::string::String,
    #[prost(int64, tag="4")]
    pub event_timestamp: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AccountSummaryEntry {
    #[prost(string, tag="1")]
    pub account_code: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub cash_asset: ::prost::alloc::string::String,
    #[prost(double, tag="3")]
    pub total_avail_value: f64,
    #[prost(double, tag="4")]
    pub total_value: f64,
    #[prost(double, tag="5")]
    pub total_frozen_value: f64,
    #[prost(double, tag="6")]
    pub unrealized_pnl: f64,
    #[prost(double, tag="7")]
    pub leverage: f64,
    #[prost(enumeration="MarginModeType", tag="8")]
    pub margin_mode_type: i32,
    #[prost(double, tag="9")]
    pub total_margin: f64,
    #[prost(int64, tag="14")]
    pub update_timestamp: i64,
    #[prost(string, tag="15")]
    pub original_info: ::prost::alloc::string::String,
    #[prost(double, tag="16")]
    pub buying_power: f64,
    #[prost(double, tag="17")]
    pub maintenance_margin: f64,
    #[prost(double, tag="18")]
    pub net_liquidation_value: f64,
    #[prost(enumeration="super::super::common::v1::AccountType", tag="19")]
    pub account_type: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AccountSettingEntry {
    #[prost(string, tag="1")]
    pub exch_account_id: ::prost::alloc::string::String,
    #[prost(double, tag="2")]
    pub long_leverage: f64,
    #[prost(double, tag="3")]
    pub short_leverage: f64,
    #[prost(enumeration="MarginModeType", tag="4")]
    pub margin_mode_type: i32,
    #[prost(string, tag="5")]
    pub instrument: ::prost::alloc::string::String,
    #[prost(enumeration="super::super::common::v1::BrokerType", tag="6")]
    pub broker_type: i32,
    #[prost(enumeration="super::super::common::v1::AccountType", tag="7")]
    pub account_type: i32,
    #[prost(string, tag="8")]
    pub base_currency: ::prost::alloc::string::String,
    #[prost(string, tag="9")]
    pub regulatory_info: ::prost::alloc::string::String,
    #[prost(map="string, string", tag="10")]
    pub extra_settings: ::std::collections::HashMap<::prost::alloc::string::String, ::prost::alloc::string::String>,
}
// ===== Enums (from exch-gateway.proto, values preserved) =====

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum FeeUnitType {
    FeeTypeUnspecified = 0,
    FeeFiat = 1,
    FeeValueCoin = 2,
    FeeGasCoin = 3,
}
impl FeeUnitType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::FeeTypeUnspecified => "FEE_TYPE_UNSPECIFIED",
            Self::FeeFiat => "FEE_FIAT",
            Self::FeeValueCoin => "FEE_VALUE_COIN",
            Self::FeeGasCoin => "FEE_GAS_COIN",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "FEE_TYPE_UNSPECIFIED" => Some(Self::FeeTypeUnspecified),
            "FEE_FIAT" => Some(Self::FeeFiat),
            "FEE_VALUE_COIN" => Some(Self::FeeValueCoin),
            "FEE_GAS_COIN" => Some(Self::FeeGasCoin),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum OrderReportType {
    OrderRepTypeUnspecified = 0,
    OrderRepTypeTrade = 1,
    OrderRepTypeState = 2,
    OrderRepTypeFee = 3,
    OrderRepTypeLinkage = 4,
    OrderRepTypeExec = 5,
}
impl OrderReportType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::OrderRepTypeUnspecified => "ORDER_REP_TYPE_UNSPECIFIED",
            Self::OrderRepTypeTrade => "ORDER_REP_TYPE_TRADE",
            Self::OrderRepTypeState => "ORDER_REP_TYPE_STATE",
            Self::OrderRepTypeFee => "ORDER_REP_TYPE_FEE",
            Self::OrderRepTypeLinkage => "ORDER_REP_TYPE_LINKAGE",
            Self::OrderRepTypeExec => "ORDER_REP_TYPE_EXEC",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "ORDER_REP_TYPE_UNSPECIFIED" => Some(Self::OrderRepTypeUnspecified),
            "ORDER_REP_TYPE_TRADE" => Some(Self::OrderRepTypeTrade),
            "ORDER_REP_TYPE_STATE" => Some(Self::OrderRepTypeState),
            "ORDER_REP_TYPE_FEE" => Some(Self::OrderRepTypeFee),
            "ORDER_REP_TYPE_LINKAGE" => Some(Self::OrderRepTypeLinkage),
            "ORDER_REP_TYPE_EXEC" => Some(Self::OrderRepTypeExec),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ExchangeOrderStatus {
    ExchOrderStatusUnspecified = 0,
    ExchOrderStatusBooked = 1,
    ExchOrderStatusPartialFilled = 2,
    ExchOrderStatusFilled = 3,
    ExchOrderStatusCancelled = 4,
    ExchOrderStatusExchRejected = 5,
    ExchOrderStatusExpired = 6,
}
impl ExchangeOrderStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::ExchOrderStatusUnspecified => "EXCH_ORDER_STATUS_UNSPECIFIED",
            Self::ExchOrderStatusBooked => "EXCH_ORDER_STATUS_BOOKED",
            Self::ExchOrderStatusPartialFilled => "EXCH_ORDER_STATUS_PARTIAL_FILLED",
            Self::ExchOrderStatusFilled => "EXCH_ORDER_STATUS_FILLED",
            Self::ExchOrderStatusCancelled => "EXCH_ORDER_STATUS_CANCELLED",
            Self::ExchOrderStatusExchRejected => "EXCH_ORDER_STATUS_EXCH_REJECTED",
            Self::ExchOrderStatusExpired => "EXCH_ORDER_STATUS_EXPIRED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "EXCH_ORDER_STATUS_UNSPECIFIED" => Some(Self::ExchOrderStatusUnspecified),
            "EXCH_ORDER_STATUS_BOOKED" => Some(Self::ExchOrderStatusBooked),
            "EXCH_ORDER_STATUS_PARTIAL_FILLED" => Some(Self::ExchOrderStatusPartialFilled),
            "EXCH_ORDER_STATUS_FILLED" => Some(Self::ExchOrderStatusFilled),
            "EXCH_ORDER_STATUS_CANCELLED" => Some(Self::ExchOrderStatusCancelled),
            "EXCH_ORDER_STATUS_EXCH_REJECTED" => Some(Self::ExchOrderStatusExchRejected),
            "EXCH_ORDER_STATUS_EXPIRED" => Some(Self::ExchOrderStatusExpired),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ExchExecType {
    Unspecified = 0,
    Rejected = 1,
    CancelReject = 2,
    Replaced = 3,
    Restated = 4,
}
impl ExchExecType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "EXCH_EXEC_TYPE_UNSPECIFIED",
            Self::Rejected => "EXCH_EXEC_TYPE_REJECTED",
            Self::CancelReject => "EXCH_EXEC_TYPE_CANCEL_REJECT",
            Self::Replaced => "EXCH_EXEC_TYPE_REPLACED",
            Self::Restated => "EXCH_EXEC_TYPE_RESTATED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "EXCH_EXEC_TYPE_UNSPECIFIED" => Some(Self::Unspecified),
            "EXCH_EXEC_TYPE_REJECTED" => Some(Self::Rejected),
            "EXCH_EXEC_TYPE_CANCEL_REJECT" => Some(Self::CancelReject),
            "EXCH_EXEC_TYPE_REPLACED" => Some(Self::Replaced),
            "EXCH_EXEC_TYPE_RESTATED" => Some(Self::Restated),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum OrderSourceType {
    OrderSourceUnspecified = 0,
    OrderSourceTq = 1,
    OrderSourceNonTq = 2,
    OrderSourceUnknown = 3,
}
impl OrderSourceType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::OrderSourceUnspecified => "ORDER_SOURCE_UNSPECIFIED",
            Self::OrderSourceTq => "ORDER_SOURCE_TQ",
            Self::OrderSourceNonTq => "ORDER_SOURCE_NON_TQ",
            Self::OrderSourceUnknown => "ORDER_SOURCE_UNKNOWN",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "ORDER_SOURCE_UNSPECIFIED" => Some(Self::OrderSourceUnspecified),
            "ORDER_SOURCE_TQ" => Some(Self::OrderSourceTq),
            "ORDER_SOURCE_NON_TQ" => Some(Self::OrderSourceNonTq),
            "ORDER_SOURCE_UNKNOWN" => Some(Self::OrderSourceUnknown),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum MarginModeType {
    MarginUnspecified = 0,
    MarginCross = 1,
    MarginIsolated = 2,
    MarginUnknown = 3,
}
impl MarginModeType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::MarginUnspecified => "MARGIN_UNSPECIFIED",
            Self::MarginCross => "MARGIN_CROSS",
            Self::MarginIsolated => "MARGIN_ISOLATED",
            Self::MarginUnknown => "MARGIN_UNKNOWN",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "MARGIN_UNSPECIFIED" => Some(Self::MarginUnspecified),
            "MARGIN_CROSS" => Some(Self::MarginCross),
            "MARGIN_ISOLATED" => Some(Self::MarginIsolated),
            "MARGIN_UNKNOWN" => Some(Self::MarginUnknown),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum GatewayEventType {
    GwEventStarted = 0,
    GwEventExchDisconnected = 1,
}
impl GatewayEventType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::GwEventStarted => "GW_EVENT_STARTED",
            Self::GwEventExchDisconnected => "GW_EVENT_EXCH_DISCONNECTED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "GW_EVENT_STARTED" => Some(Self::GwEventStarted),
            "GW_EVENT_EXCH_DISCONNECTED" => Some(Self::GwEventExchDisconnected),
            _ => None,
        }
    }
}
// @@protoc_insertion_point(module)
