# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from zk.common.v1 import common_pb2 as zk_dot_common_dot_v1_dot_common__pb2
from zk.oms.v1 import oms_pb2 as zk_dot_oms_dot_v1_dot_oms__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in zk/oms/v1/oms_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class OMSServiceStub(object):
    """OMSService — replaces legacy OrderManagerService in tqrpc_oms.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PlaceOrder = channel.unary_unary(
                '/zk.oms.v1.OMSService/PlaceOrder',
                request_serializer=zk_dot_oms_dot_v1_dot_oms__pb2.PlaceOrderRequest.SerializeToString,
                response_deserializer=zk_dot_oms_dot_v1_dot_oms__pb2.OMSResponse.FromString,
                _registered_method=True)
        self.BatchPlaceOrders = channel.unary_unary(
                '/zk.oms.v1.OMSService/BatchPlaceOrders',
                request_serializer=zk_dot_oms_dot_v1_dot_oms__pb2.BatchPlaceOrdersRequest.SerializeToString,
                response_deserializer=zk_dot_oms_dot_v1_dot_oms__pb2.OMSResponse.FromString,
                _registered_method=True)
        self.CancelOrder = channel.unary_unary(
                '/zk.oms.v1.OMSService/CancelOrder',
                request_serializer=zk_dot_oms_dot_v1_dot_oms__pb2.CancelOrderRequest.SerializeToString,
                response_deserializer=zk_dot_oms_dot_v1_dot_oms__pb2.OMSResponse.FromString,
                _registered_method=True)
        self.BatchCancelOrders = channel.unary_unary(
                '/zk.oms.v1.OMSService/BatchCancelOrders',
                request_serializer=zk_dot_oms_dot_v1_dot_oms__pb2.BatchCancelOrdersRequest.SerializeToString,
                response_deserializer=zk_dot_oms_dot_v1_dot_oms__pb2.OMSResponse.FromString,
                _registered_method=True)
        self.ExecuteAlgoOrder = channel.unary_unary(
                '/zk.oms.v1.OMSService/ExecuteAlgoOrder',
                request_serializer=zk_dot_oms_dot_v1_dot_oms__pb2.AlgoOrderRequest.SerializeToString,
                response_deserializer=zk_dot_oms_dot_v1_dot_oms__pb2.OMSResponse.FromString,
                _registered_method=True)
        self.CancelAlgoOrder = channel.unary_unary(
                '/zk.oms.v1.OMSService/CancelAlgoOrder',
                request_serializer=zk_dot_oms_dot_v1_dot_oms__pb2.CancelAlgoOrderRequest.SerializeToString,
                response_deserializer=zk_dot_oms_dot_v1_dot_oms__pb2.OMSResponse.FromString,
                _registered_method=True)
        self.Panic = channel.unary_unary(
                '/zk.oms.v1.OMSService/Panic',
                request_serializer=zk_dot_oms_dot_v1_dot_oms__pb2.PanicRequest.SerializeToString,
                response_deserializer=zk_dot_oms_dot_v1_dot_oms__pb2.OMSResponse.FromString,
                _registered_method=True)
        self.DontPanic = channel.unary_unary(
                '/zk.oms.v1.OMSService/DontPanic',
                request_serializer=zk_dot_oms_dot_v1_dot_oms__pb2.DontPanicRequest.SerializeToString,
                response_deserializer=zk_dot_oms_dot_v1_dot_oms__pb2.OMSResponse.FromString,
                _registered_method=True)
        self.QueryPosition = channel.unary_unary(
                '/zk.oms.v1.OMSService/QueryPosition',
                request_serializer=zk_dot_oms_dot_v1_dot_oms__pb2.QueryPositionRequest.SerializeToString,
                response_deserializer=zk_dot_oms_dot_v1_dot_oms__pb2.PositionResponse.FromString,
                _registered_method=True)
        self.QueryBalances = channel.unary_unary(
                '/zk.oms.v1.OMSService/QueryBalances',
                request_serializer=zk_dot_oms_dot_v1_dot_oms__pb2.QueryBalancesRequest.SerializeToString,
                response_deserializer=zk_dot_oms_dot_v1_dot_oms__pb2.QueryBalancesResponse.FromString,
                _registered_method=True)
        self.QueryOpenOrders = channel.unary_unary(
                '/zk.oms.v1.OMSService/QueryOpenOrders',
                request_serializer=zk_dot_oms_dot_v1_dot_oms__pb2.QueryOpenOrderRequest.SerializeToString,
                response_deserializer=zk_dot_oms_dot_v1_dot_oms__pb2.OrderDetailResponse.FromString,
                _registered_method=True)
        self.QueryOrderDetails = channel.unary_unary(
                '/zk.oms.v1.OMSService/QueryOrderDetails',
                request_serializer=zk_dot_oms_dot_v1_dot_oms__pb2.QueryOrderDetailRequest.SerializeToString,
                response_deserializer=zk_dot_oms_dot_v1_dot_oms__pb2.OrderDetailResponse.FromString,
                _registered_method=True)
        self.QueryTradeDetails = channel.unary_unary(
                '/zk.oms.v1.OMSService/QueryTradeDetails',
                request_serializer=zk_dot_oms_dot_v1_dot_oms__pb2.QueryTradeDetailRequest.SerializeToString,
                response_deserializer=zk_dot_oms_dot_v1_dot_oms__pb2.TradeDetailResponse.FromString,
                _registered_method=True)
        self.QueryInstrumentRefdata = channel.unary_unary(
                '/zk.oms.v1.OMSService/QueryInstrumentRefdata',
                request_serializer=zk_dot_oms_dot_v1_dot_oms__pb2.QueryInstrumentRefdataRequest.SerializeToString,
                response_deserializer=zk_dot_oms_dot_v1_dot_oms__pb2.QueryInstrumentRefdataResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/zk.oms.v1.OMSService/HealthCheck',
                request_serializer=zk_dot_common_dot_v1_dot_common__pb2.DummyRequest.SerializeToString,
                response_deserializer=zk_dot_common_dot_v1_dot_common__pb2.ServiceHealthResponse.FromString,
                _registered_method=True)


class OMSServiceServicer(object):
    """OMSService — replaces legacy OrderManagerService in tqrpc_oms.
    """

    def PlaceOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchPlaceOrders(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchCancelOrders(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteAlgoOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelAlgoOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Panic(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DontPanic(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryPosition(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryBalances(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryOpenOrders(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryOrderDetails(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryTradeDetails(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryInstrumentRefdata(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OMSServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PlaceOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.PlaceOrder,
                    request_deserializer=zk_dot_oms_dot_v1_dot_oms__pb2.PlaceOrderRequest.FromString,
                    response_serializer=zk_dot_oms_dot_v1_dot_oms__pb2.OMSResponse.SerializeToString,
            ),
            'BatchPlaceOrders': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchPlaceOrders,
                    request_deserializer=zk_dot_oms_dot_v1_dot_oms__pb2.BatchPlaceOrdersRequest.FromString,
                    response_serializer=zk_dot_oms_dot_v1_dot_oms__pb2.OMSResponse.SerializeToString,
            ),
            'CancelOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelOrder,
                    request_deserializer=zk_dot_oms_dot_v1_dot_oms__pb2.CancelOrderRequest.FromString,
                    response_serializer=zk_dot_oms_dot_v1_dot_oms__pb2.OMSResponse.SerializeToString,
            ),
            'BatchCancelOrders': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchCancelOrders,
                    request_deserializer=zk_dot_oms_dot_v1_dot_oms__pb2.BatchCancelOrdersRequest.FromString,
                    response_serializer=zk_dot_oms_dot_v1_dot_oms__pb2.OMSResponse.SerializeToString,
            ),
            'ExecuteAlgoOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteAlgoOrder,
                    request_deserializer=zk_dot_oms_dot_v1_dot_oms__pb2.AlgoOrderRequest.FromString,
                    response_serializer=zk_dot_oms_dot_v1_dot_oms__pb2.OMSResponse.SerializeToString,
            ),
            'CancelAlgoOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelAlgoOrder,
                    request_deserializer=zk_dot_oms_dot_v1_dot_oms__pb2.CancelAlgoOrderRequest.FromString,
                    response_serializer=zk_dot_oms_dot_v1_dot_oms__pb2.OMSResponse.SerializeToString,
            ),
            'Panic': grpc.unary_unary_rpc_method_handler(
                    servicer.Panic,
                    request_deserializer=zk_dot_oms_dot_v1_dot_oms__pb2.PanicRequest.FromString,
                    response_serializer=zk_dot_oms_dot_v1_dot_oms__pb2.OMSResponse.SerializeToString,
            ),
            'DontPanic': grpc.unary_unary_rpc_method_handler(
                    servicer.DontPanic,
                    request_deserializer=zk_dot_oms_dot_v1_dot_oms__pb2.DontPanicRequest.FromString,
                    response_serializer=zk_dot_oms_dot_v1_dot_oms__pb2.OMSResponse.SerializeToString,
            ),
            'QueryPosition': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryPosition,
                    request_deserializer=zk_dot_oms_dot_v1_dot_oms__pb2.QueryPositionRequest.FromString,
                    response_serializer=zk_dot_oms_dot_v1_dot_oms__pb2.PositionResponse.SerializeToString,
            ),
            'QueryBalances': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryBalances,
                    request_deserializer=zk_dot_oms_dot_v1_dot_oms__pb2.QueryBalancesRequest.FromString,
                    response_serializer=zk_dot_oms_dot_v1_dot_oms__pb2.QueryBalancesResponse.SerializeToString,
            ),
            'QueryOpenOrders': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryOpenOrders,
                    request_deserializer=zk_dot_oms_dot_v1_dot_oms__pb2.QueryOpenOrderRequest.FromString,
                    response_serializer=zk_dot_oms_dot_v1_dot_oms__pb2.OrderDetailResponse.SerializeToString,
            ),
            'QueryOrderDetails': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryOrderDetails,
                    request_deserializer=zk_dot_oms_dot_v1_dot_oms__pb2.QueryOrderDetailRequest.FromString,
                    response_serializer=zk_dot_oms_dot_v1_dot_oms__pb2.OrderDetailResponse.SerializeToString,
            ),
            'QueryTradeDetails': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryTradeDetails,
                    request_deserializer=zk_dot_oms_dot_v1_dot_oms__pb2.QueryTradeDetailRequest.FromString,
                    response_serializer=zk_dot_oms_dot_v1_dot_oms__pb2.TradeDetailResponse.SerializeToString,
            ),
            'QueryInstrumentRefdata': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryInstrumentRefdata,
                    request_deserializer=zk_dot_oms_dot_v1_dot_oms__pb2.QueryInstrumentRefdataRequest.FromString,
                    response_serializer=zk_dot_oms_dot_v1_dot_oms__pb2.QueryInstrumentRefdataResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=zk_dot_common_dot_v1_dot_common__pb2.DummyRequest.FromString,
                    response_serializer=zk_dot_common_dot_v1_dot_common__pb2.ServiceHealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'zk.oms.v1.OMSService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('zk.oms.v1.OMSService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OMSService(object):
    """OMSService — replaces legacy OrderManagerService in tqrpc_oms.
    """

    @staticmethod
    def PlaceOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/zk.oms.v1.OMSService/PlaceOrder',
            zk_dot_oms_dot_v1_dot_oms__pb2.PlaceOrderRequest.SerializeToString,
            zk_dot_oms_dot_v1_dot_oms__pb2.OMSResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchPlaceOrders(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/zk.oms.v1.OMSService/BatchPlaceOrders',
            zk_dot_oms_dot_v1_dot_oms__pb2.BatchPlaceOrdersRequest.SerializeToString,
            zk_dot_oms_dot_v1_dot_oms__pb2.OMSResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/zk.oms.v1.OMSService/CancelOrder',
            zk_dot_oms_dot_v1_dot_oms__pb2.CancelOrderRequest.SerializeToString,
            zk_dot_oms_dot_v1_dot_oms__pb2.OMSResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchCancelOrders(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/zk.oms.v1.OMSService/BatchCancelOrders',
            zk_dot_oms_dot_v1_dot_oms__pb2.BatchCancelOrdersRequest.SerializeToString,
            zk_dot_oms_dot_v1_dot_oms__pb2.OMSResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteAlgoOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/zk.oms.v1.OMSService/ExecuteAlgoOrder',
            zk_dot_oms_dot_v1_dot_oms__pb2.AlgoOrderRequest.SerializeToString,
            zk_dot_oms_dot_v1_dot_oms__pb2.OMSResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelAlgoOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/zk.oms.v1.OMSService/CancelAlgoOrder',
            zk_dot_oms_dot_v1_dot_oms__pb2.CancelAlgoOrderRequest.SerializeToString,
            zk_dot_oms_dot_v1_dot_oms__pb2.OMSResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Panic(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/zk.oms.v1.OMSService/Panic',
            zk_dot_oms_dot_v1_dot_oms__pb2.PanicRequest.SerializeToString,
            zk_dot_oms_dot_v1_dot_oms__pb2.OMSResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DontPanic(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/zk.oms.v1.OMSService/DontPanic',
            zk_dot_oms_dot_v1_dot_oms__pb2.DontPanicRequest.SerializeToString,
            zk_dot_oms_dot_v1_dot_oms__pb2.OMSResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryPosition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/zk.oms.v1.OMSService/QueryPosition',
            zk_dot_oms_dot_v1_dot_oms__pb2.QueryPositionRequest.SerializeToString,
            zk_dot_oms_dot_v1_dot_oms__pb2.PositionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryBalances(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/zk.oms.v1.OMSService/QueryBalances',
            zk_dot_oms_dot_v1_dot_oms__pb2.QueryBalancesRequest.SerializeToString,
            zk_dot_oms_dot_v1_dot_oms__pb2.QueryBalancesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryOpenOrders(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/zk.oms.v1.OMSService/QueryOpenOrders',
            zk_dot_oms_dot_v1_dot_oms__pb2.QueryOpenOrderRequest.SerializeToString,
            zk_dot_oms_dot_v1_dot_oms__pb2.OrderDetailResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryOrderDetails(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/zk.oms.v1.OMSService/QueryOrderDetails',
            zk_dot_oms_dot_v1_dot_oms__pb2.QueryOrderDetailRequest.SerializeToString,
            zk_dot_oms_dot_v1_dot_oms__pb2.OrderDetailResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryTradeDetails(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/zk.oms.v1.OMSService/QueryTradeDetails',
            zk_dot_oms_dot_v1_dot_oms__pb2.QueryTradeDetailRequest.SerializeToString,
            zk_dot_oms_dot_v1_dot_oms__pb2.TradeDetailResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryInstrumentRefdata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/zk.oms.v1.OMSService/QueryInstrumentRefdata',
            zk_dot_oms_dot_v1_dot_oms__pb2.QueryInstrumentRefdataRequest.SerializeToString,
            zk_dot_oms_dot_v1_dot_oms__pb2.QueryInstrumentRefdataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/zk.oms.v1.OMSService/HealthCheck',
            zk_dot_common_dot_v1_dot_common__pb2.DummyRequest.SerializeToString,
            zk_dot_common_dot_v1_dot_common__pb2.ServiceHealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
