# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: zk/discovery/v1/discovery.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'zk/discovery/v1/discovery.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fzk/discovery/v1/discovery.proto\x12\x0fzk.discovery.v1\"I\n\x11TransportEndpoint\x12\x10\n\x08protocol\x18\x01 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\t\x12\x11\n\tauthority\x18\x03 \x01(\t\"\xe2\x02\n\x13ServiceRegistration\x12\x14\n\x0cservice_type\x18\x01 \x01(\t\x12\x12\n\nservice_id\x18\x02 \x01(\t\x12\x13\n\x0binstance_id\x18\x03 \x01(\t\x12\x34\n\x08\x65ndpoint\x18\x04 \x01(\x0b\x32\".zk.discovery.v1.TransportEndpoint\x12\x13\n\x0b\x61\x63\x63ount_ids\x18\x05 \x03(\x03\x12\r\n\x05venue\x18\x06 \x01(\t\x12\x14\n\x0c\x63\x61pabilities\x18\x07 \x03(\t\x12\x17\n\x0flease_expiry_ms\x18\x08 \x01(\x03\x12\x15\n\rupdated_at_ms\x18\t \x01(\x03\x12>\n\x05\x61ttrs\x18\n \x03(\x0b\x32/.zk.discovery.v1.ServiceRegistration.AttrsEntry\x1a,\n\nAttrsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'zk.discovery.v1.discovery_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SERVICEREGISTRATION_ATTRSENTRY']._loaded_options = None
  _globals['_SERVICEREGISTRATION_ATTRSENTRY']._serialized_options = b'8\001'
  _globals['_TRANSPORTENDPOINT']._serialized_start=52
  _globals['_TRANSPORTENDPOINT']._serialized_end=125
  _globals['_SERVICEREGISTRATION']._serialized_start=128
  _globals['_SERVICEREGISTRATION']._serialized_end=482
  _globals['_SERVICEREGISTRATION_ATTRSENTRY']._serialized_start=438
  _globals['_SERVICEREGISTRATION_ATTRSENTRY']._serialized_end=482
# @@protoc_insertion_point(module_scope)
