# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: rpc-refdata.proto
# plugin: python-betterproto
# This file has been @generated

from dataclasses import dataclass
from typing import (
    TYPE_CHECKING,
    Dict,
    List,
    Optional,
)

import betterproto
import grpclib
from betterproto.grpc.grpclib_server import ServiceBase

from .. import common as _common__

if TYPE_CHECKING:
    import grpclib.server
    from betterproto.grpc.grpclib_client import MetadataLike
    from grpclib.metadata import Deadline


@dataclass(eq=False, repr=False)
class InstrumentDataQueryRequest(betterproto.Message):
    instrument_code: List[str] = betterproto.string_field(1)


@dataclass(eq=False, repr=False)
class InstrumentDataQueryResponse(betterproto.Message):
    instrument_ref_data: List["_common__.InstrumentRefData"] = (
        betterproto.message_field(1)
    )


@dataclass(eq=False, repr=False)
class TradingPairsResponse(betterproto.Message):
    pairs: List[str] = betterproto.string_field(1)


class RefDataServiceStub(betterproto.ServiceStub):
    async def query_instrument_ref_data(
        self,
        instrument_data_query_request: "InstrumentDataQueryRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "InstrumentDataQueryResponse":
        return await self._unary_unary(
            "/tqrpc_ref.RefDataService/QueryInstrumentRefData",
            instrument_data_query_request,
            InstrumentDataQueryResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def query_trading_pairs(
        self,
        common_dummy_request: "_common__.DummyRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "TradingPairsResponse":
        return await self._unary_unary(
            "/tqrpc_ref.RefDataService/QueryTradingPairs",
            common_dummy_request,
            TradingPairsResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )


class RefDataServiceBase(ServiceBase):

    async def query_instrument_ref_data(
        self, instrument_data_query_request: "InstrumentDataQueryRequest"
    ) -> "InstrumentDataQueryResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def query_trading_pairs(
        self, common_dummy_request: "_common__.DummyRequest"
    ) -> "TradingPairsResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def __rpc_query_instrument_ref_data(
        self,
        stream: "grpclib.server.Stream[InstrumentDataQueryRequest, InstrumentDataQueryResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.query_instrument_ref_data(request)
        await stream.send_message(response)

    async def __rpc_query_trading_pairs(
        self,
        stream: "grpclib.server.Stream[_common__.DummyRequest, TradingPairsResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.query_trading_pairs(request)
        await stream.send_message(response)

    def __mapping__(self) -> Dict[str, grpclib.const.Handler]:
        return {
            "/tqrpc_ref.RefDataService/QueryInstrumentRefData": grpclib.const.Handler(
                self.__rpc_query_instrument_ref_data,
                grpclib.const.Cardinality.UNARY_UNARY,
                InstrumentDataQueryRequest,
                InstrumentDataQueryResponse,
            ),
            "/tqrpc_ref.RefDataService/QueryTradingPairs": grpclib.const.Handler(
                self.__rpc_query_trading_pairs,
                grpclib.const.Cardinality.UNARY_UNARY,
                _common__.DummyRequest,
                TradingPairsResponse,
            ),
        }
